### ISSUE TITLE
ModManager doesn't work after the Forces update

### ISSUE THREAD

**Issue by PhilipS02** [thesupersonic16/HedgeModManager#10]
The game crashes now after i start it with the modmanager

**Comment by slashiee** [comment]
we're fully aware of it.

**Comment by thesupersonic16** [comment]
Yeah, I'm aware of it, The update came out 10 minutes before the time I planed to goto bed, And stayed up to 1AM working on it. So far its still unfinished.

**Comment by thesupersonic16** [comment]
A version you can test: 
https://ci.appveyor.com/api/buildjobs/mb3kum0wbkfev63h/artifacts/HedgeModManager%2Fbin%2FHedgeModManager%206.1-009_r101%20%5BRelease%5D.zip

**Comment by thesupersonic16** [comment]
Closing as the CodeLoader has already been updated for a while now, Reopen if you still have the issue.
