### ISSUE TITLE
[Bug] Generations crashing after a couple seconds of loading

### ISSUE THREAD

**Issue by ezidro3** [thesupersonic16/HedgeModManager#100]
Hi, I'm trying to launch some mods for Generations and the game crashes a couple seconds after I select Continue on the title screen. I don't get any error messages, the game just boots me back to the desktop after a bit. I do have both SonicGMI and HedgeModManager installed, but I've started to have this problem recently. One instance of this is the Unleashed Project, where it worked once with HMM and now it'll only boot if I use SonicGMI. Another was Grand Metropolis which has never worked for me on HMM. I've already tried validating the files through Steam. re-installing the game completely, deleting Codes.dat, running the game through Steam instead of HMM, and clearing up my mods folder of mods I wasn't using, and I get the same problem. I do run the game at a low resolution (640x400) to get an acceptable frame rate, but I don't think it would be causing problems since Unleashed Project worked fine through SonicGMI.

**Comment by ezidro3** [comment]
Quick update: I installed BetterFxPipeline and that fixed the Unleashed Project, Sky Rail (by SonicHyuga), and Windy Walley 1 (by Sky the Destroyer) crashing. Grand Metropolis 1.0.3 (by Blackened Angel) and Tropical Resort All in One (by brianuuu) still crash at the loading screen.

**Comment by thesupersonic16** [comment]
Can you try load one mod at a time to see if any are conflicting? I also tested `Tropical Resort All in One` that you mentioned along with other mods and it worked perfectly fine.
While at it can you send a screenshot of HMM's settings and the mod order you have and make sure you read the mods READMEs. 

Also before doing these, can you delete cpkredir.dll so HMM can write the newest version back.

**Comment by ezidro3** [comment]
Well it turns out I was forgetting some Sound and Movie files for those mods. Putting them in fixed my issues. Ignore my stupidity lol.
