### ISSUE TITLE
HedgeModManager.exe fails to start on Linux using Wine

### ISSUE THREAD

**Issue by felixactually** [thesupersonic16/HedgeModManager#101]
I don't know if this is something you can fix, but I tried running the executable with Wine (I haven't tried Proton yet), and it gives this error if I run it in the terminal:
`The entry point method could not be loaded due to Could not load file or assembly 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. assembly:PresentationFramework, Version=4.0.0.0, Culture=neutral`

Or perhaps I just need one of the Windows components/DLLs selectable in Winetricks?

Edit: Attempted running it with Proton 5.0-7 and nothing happened, so I assume it has the same issue. Also, the version of Wine used was 4.0.2

**Comment by Sajidur78** [comment]
As its current state HMM cannot run on wine because it is running on wpf. to be able to run HMM on wine/linux it needs to be ported to .Net Core.

**Comment by felixactually** [comment]
I see, and is that a possibility in the future? I'd really like to be able to use mods in Sonic Generations.

**Comment by Sajidur78** [comment]
There's a possibility in the near future for HMM to target both .Net Framework and .Net Core. But for now I will be closing this issue as there's nothing that can be done currently and is not a focus of the project.
