### ISSUE TITLE
Select Mods Not Loading

### ISSUE THREAD

**Issue by ButtSavage** [thesupersonic16/HedgeModManager#103]
Hi, certain mods like voice mods except the real jason griffith mod are loading and the mod loader is not loading other voice mods, or even the quickstep fix (I even re installed the mods and it still isn't).

**Comment by MarioTainaka** [comment]
Hi there, i'm the creator of the real jason griffh voice mod, the mod already includes a version with the quickstep fix for when playing generations vanilla. It has a version specifically made for that. The quickstep fix mod by itself won't work with other mods that they aren't designed for.

**Comment by ButtSavage** [comment]
What's odd is that it only started not loading the quickstep as of recently, did you update it to make it do such recently? (it usually worked fine with the normal one instead of the vanilla game version)
