### ISSUE TITLE
[Gens] Mods and Codes don't work (crashes game)

### ISSUE THREAD

**Issue by SonShadSilver21** [thesupersonic16/HedgeModManager#104]
## Description

So I recently migrated to HMM from Sonic GMI and tried to use the codes and better fxpipeline mod. Anytime I use either of the 2, the game crashes. All the other mods work fine. I tried to fix it by reinstalling sonic generations, but I still have the same issues. just like before reinstalling, with better fxpipelin enabled, it shows a black screen when launched and then closes itself. When using codes, it crashes on loading screen (or when the code is going to be used such as when trying to do the sweepkick, it crashes). I made sure to remove all cpkredir files and GMI stuff before using HMM but it still does not work. 

## Current and Expected Behaviour

I thought the mods and codes would work but they did not.

## Steps to Reproduce

I am not sure; I just have HMM installed (in the same folder as generations) and apotos adventure pack unleashed and normal enabled, real unleashed exp enabled, unleashed HUD, and better fxpipeline with longer blue trail, empty boost gauge, and sweepkick codes.

**Comment by MarioTainaka** [comment]
The game requires the later version of the game which was the latest update for the game version 1.0.t

**Comment by SonShadSilver21** [comment]
How do I check my version?

**Comment by SonShadSilver21** [comment]
Okay, so my version of generations was actually up to date. The problem was that I had made a copy of the generations folder in another drive (I don't know why). So, I had 2 folders of gens and also the mod loader was just in my documents folder. So, I removed the copy (leaving the one in the steam directory left) and put the mod loader in the gens folder and everything worked!
