### ISSUE TITLE
[Forces] Mods and Codes don't seem to work.

### ISSUE THREAD

**Issue by ghost** [thesupersonic16/HedgeModManager#115]
Bought Forces from the Steam Summer Sale.

Started my first playthrough with the "CFR's Wispon Tweaks" and "Classic Sonic Improvement Mod + Modern Tweaks" mods, along with the "Disable Wispon Boundaries" code.

Though I quickly realised that nor the mods or code that I had on actually worked. I'm sure of it.

I've tried uninstalling and reinstalling twice, along with getting rid of possible leftover HMM files from my Generations folder when I used to use HMM for Generations incase it thinks it's trying to do stuff for Generations and not Forces.

I am using the latest HMM version also. (7.2-4)

Edit: I tried the Infinite Boost code, and that works, so that makes this situation much more confusing.

**Comment by ghost** [comment]
By the way, I've ran into a problem when loading into Mission 25 for the first time when using said mods and code due to the cutscene.

[ForcesModLoader] [ERROR] [criErr_Notify1] Level: 1 -  W2007060103:Reading error occurred. (err = 998)

**Comment by thesupersonic16** [comment]
That error message is unrelated. Can you try each code on their own and see if they work?

**Comment by ghost** [comment]
Well, I've tried a majority of the codes already, and only the Wispon Boundaries one seems bad.

Honestly at this point, I'm not sure if these mods are working or not, because I'm still having a bad time with the game.
