### ISSUE TITLE
HedgeMod Manager stops Forces

### ISSUE THREAD

**Issue by rhonddaboy13** [thesupersonic16/HedgeModManager#116]
Hey all,
This is a new issue I have come across and wondering if you guys can help.
When I open and run the Mod Manager, choose my mods, and select 'Save and Play' the game will begin to load, on Steam it will say 'running' and then stop. However when I uninstall the mod loader the game works fine. I am using the most up to date version of the Mod loader (7.2-4) and game.
Any help would be greatly appreciated.

**Comment by thesupersonic16** [comment]
Can you check if you have [Microsoft Visual C++ Redistributable for 2019 x64](https://aka.ms/vs/16/release/vc_redist.x64.exe) installed?

**Comment by rhonddaboy13** [comment]
That worked, thank you very much
