### ISSUE TITLE
there are no changes in the game

### ISSUE THREAD

**Issue by Hyper279** [thesupersonic16/HedgeModManager#12]
In hedgehogmodmanager I install it well, the mods and everything come out, but in the game there are no changes, help xd

**Comment by thesupersonic16** [comment]
Do you have wars_mods.cpk in your disk folder?

**Comment by thesupersonic16** [comment]
Also Can you run this and send me the .log file after running it? https://drive.google.com/open?id=1mTNnEN65Ddub7X6dvLKd7KX_tVs25BZ4

**Comment by Hyper279** [comment]
I'm talking about sonic forces, and I do not have those files in the folders you describe, where do I find them?

**Comment by Hyper279** [comment]
I'm talking about sonic forces, the file wars_mods.cpk if I have it in that folder, but the CpkMaker.dll is not where it is

**Comment by Hyper279** [comment]
cancel it xD, I've found it and it works, thanks for the help
