### ISSUE TITLE
McAfee found a Virus

### ISSUE THREAD

**Issue by LegoLoco7** [thesupersonic16/HedgeModManager#120]
I'm not saying this has an _intentional_ virus, but I tried updating HedgeModManager to the latest version (7.2-5) and it opened the new version but after a few seconds it was suspended by McAfee and moved to Quarantined Files. (I've tried this more than once and the same thing happens every time) I wrote down the information here:
[VirusReport.txt](https://github.com/thesupersonic16/HedgeModManager/files/4941221/VirusReport.txt)
But then I tried downloading the 7.2-4 version from GameBanana and tried opening it and McAfee _instantly_ Suspended it and moved it to Quarantine. I don't know how to fix this myself so I figured this was a bug with HedgeModManager. (even though I didn't put this in the Mods category) For now I'll stick with Sonic GMI.

**Comment by Sajidur78** [comment]
This is a false positive. As you can see HMM is an open source project, that fact alone proves that it would be impossible to hide a virus and thus the threat being a false positive. Closed.

**Comment by thesupersonic16** [comment]
It's a false positive. You should beable to set it as an exception.

**Comment by Sajidur78** [comment]
According to [VirusTotal](https://www.virustotal.com/gui/file/e08f7ad2efdf560d3dcdb3c5526b72685d3e86b3b4f5f19e45777c20b92eb1e4/detection) McAfee doesn't find HMM malicious.
![image](https://user-images.githubusercontent.com/16513942/87847191-ebfe2480-c8f7-11ea-9720-532547c01f17.png)

**Comment by LegoLoco7** [comment]
Well it's true. And I don't know how to stop it other than uninstalling McAfee. 😢
