### ISSUE TITLE
Sonic Forces doesn't start with mod loader installed

### ISSUE THREAD

**Issue by jobukkit** [thesupersonic16/HedgeModManager#128]
When the mod loader is installed (even if it's disabled), Sonic Forces simply doesn't start at all. No error message, so I have no idea what details I can provide. Uninstalling lets the game be played again. Happens both with GitHub and AppVeyor version.

**Comment by Sajidur78** [comment]
Install Visual C++ 2019 64bit

**Comment by jobukkit** [comment]
Thanks for the instant response, that was indeed it. Gotta love Windows. Maybe the Readme should mention this.
