### ISSUE TITLE
[Forces] Detect Special K local installation and install to a different spot

### ISSUE THREAD

**Issue by slashiee** [thesupersonic16/HedgeModManager#13]
This can be done if someone has Special K installed for Forces, and wants to use the mod loader. (by detecting dxgi.dll in the exec folder)

ATM, both cause conflicts causing the game to crash at launch. However, uninstalling the mod loader makes Special K work fine.

In Special K, there's an option to load up the official ReShade at launch, which is what we can override.
![2017-12-03_16-41-23](https://user-images.githubusercontent.com/15317421/33532074-f04ffc16-d84a-11e7-8c70-374939ddeb54.png)

The dll has to be put at an location like this:
`
C:\Users\{USER_NAME}\Documents\My Mods\SpecialK\PlugIns\ThirdParty\ReShade\ReShade64.dll
`

But the user has to be warned that if they have a ReShade installation there, it has to be overwritten.

**Comment by thesupersonic16** [comment]
Could we make a Plugin like ReShade? But instead of loading ReShade, We could get them to load the CodeLoaders.

**Comment by AdamMatthews93** [comment]
No need to replace the ReShade dll, you can rename d3d11.dll and manually add it to SpecialK's Forces profile, example 

[Import.HedgeModManager]
Architecture=x64
Role=ThirdParty
When=Early
Filename=d3d11_HMM.dll

I tried both global and local SK installs and it only works with local unfortunately

**Comment by thesupersonic16** [comment]
Thats what I'm pretty much saying. lol

**Comment by slashiee** [comment]
Oh, good to know. Will it also allow for ReShade?

**Comment by Adam-M93** [comment]
I just tried it myself, the official ReShade loaded as a Third-party Plug-In is fine, the unofficial one that's part of SK loads but only works in menus, it stops working during stages. Neither worked for me when set to Early load order.
