### ISSUE TITLE
Sonic Forces refuses to load after Hedgemodmanager installs [Bug] 

### ISSUE THREAD

**Issue by Hypershadicguy64** [thesupersonic16/HedgeModManager#131]
## Describe the issue/bug
I downloaded the HedgeModManager, installed the mods folder for Sonic Forces, and then the game REFUSES to open, it doesn't even show up in the Task Manager.

## Expected Behaviour
I honestly expected it to work as easily as everyone says, but that obviously isn't the case.

## Additional Context
I don't know if there's any other way to play this on PC, but just in case, I'm using a verified Steam purchase of Sonic Forces.

**Comment by thesupersonic16** [comment]
Can you make sure you have [Visual C++ Redistributable 2019](https://aka.ms/vs/16/release/vc_redist.x64.exe) Installed?

**Comment by Hypershadicguy64** [comment]
I'm going to try it now.

**Comment by Hypershadicguy64** [comment]
It's working now! Thank you so much!
