### ISSUE TITLE
Sonic Forces refuses to launch. 

### ISSUE THREAD

**Issue by pastelaura** [thesupersonic16/HedgeModManager#134]
I'm having an issue where Forces just refuses to launch. When I select a mod in the manager, then "Save and Play", the cmd window pops up, but the game itself never does. 
I've tried this with other mods as well. They all gave the same result.

**Comment by thesupersonic16** [comment]
Can you please check if you are running HMM version 7.2-6 and can you try see if the game boots with no mods installed.

**Comment by pastelaura** [comment]
> Can you please check if you are running HMM version 7.2-6 and can you try see if the game boots with no mods installed.

I am using the latest version of HMM - 7.2-6. Just tried running the game through HMM with none of the mods checked and still the same result.

**Comment by thesupersonic16** [comment]
Can you check if there is a file with the like "Sonic Forces.exe.\<bunch a number\>.dmp" in `%localappdata%\CrashDumps`? I do not need you to upload it.

**Comment by pastelaura** [comment]
> Can you check if there is a file with the like "Sonic Forces.exe.<bunch a number>.dmp" in `%localappdata%\CrashDumps`? I do not need you to upload it.

There doesn't seem to be one with Forces. The only one I can see is a .dmp file with HMM in the file name.

**Comment by thesupersonic16** [comment]
I forgot to ask, did you try restarting your PC?

**Comment by pastelaura** [comment]
> I forgot to ask, did you try restarting your PC?

Yep

**Comment by thesupersonic16** [comment]
Maybe resetting the configs might solve the issue, to do that follow these steps:
1. Make sure HedgeModManager is closed
2. Delete `d3d11.dll` and `cpkredir.ini` from the exec folder
3. In the mods folder delete `ModsDB.ini` and `Codes.dll`
4. Start HedgeModManager and in settings click "Install Mod Loader"
5. Press "Save and Play"

A console window should appear with some text and after a bit of time more text should appear then the game window. The console window should stay open.

**Comment by pastelaura** [comment]
> Maybe resetting the configs might solve the issue, to do that follow these steps:
> 
> 1. Make sure HedgeModManager is closed
> 2. Delete `d3d11.dll` and `cpkredir.ini` from the exec folder
> 3. In the mods folder delete `ModsDB.ini` and `Codes.dll`
> 4. Start HedgeModManager and in settings click "Install Mod Loader"
> 5. Press "Save and Play"
> 
> A console window should appear with some text and after a bit of time more text should appear then the game window. The console window should stay open.

Resetting the configs didn't seem to help. The issue still persists.

**Comment by thesupersonic16** [comment]
Does any information appear in the console window when you start the game? if so, can you send it here. And are you using a legit version of Sonic Forces from Steam?

**Comment by pastelaura** [comment]
> Does any information appear in the console window when you start the game? if so, can you send it here. And are you using a legit version of Sonic Forces from Steam?

I've attached a text file containing what the console window says. I am using a legit version from Steam. 

[forces.txt](https://github.com/thesupersonic16/HedgeModManager/files/5150139/forces.txt)

**Comment by thesupersonic16** [comment]
Can you do the same but with no mods and codes selected and send the new log here? I want to rule out the mods causing the issue.

**Comment by pastelaura** [comment]
> Can you do the same but with no mods and codes selected and send the new log here? I want to rule out the mods causing the issue.

Here you go:

[forces - no mods or codes.txt](https://github.com/thesupersonic16/HedgeModManager/files/5150178/forces.-.no.mods.or.codes.txt)

**Comment by thesupersonic16** [comment]
It seems to be showing something I never seen before. Does the game work fine without the modloader?

**Comment by pastelaura** [comment]
> It seems to be showing something I never seen before. Does the game work fine without the modloader?

It sure does.

**Comment by thesupersonic16** [comment]
I'm not really sure whats really going on. Can you try
1. Deleting `Codes.dll`
2. Install [MSVC++ 2019](https://aka.ms/vs/16/release/vc_redist.x64.exe)
3. Start Forces using Steam (**Without** pressing Save or Save and Play)

**Comment by pastelaura** [comment]
> I'm not really sure whats really going on. Can you try
> 
> 1. Deleting `Codes.dll`
> 2. Install [MSVC++ 2019](https://aka.ms/vs/16/release/vc_redist.x64.exe)
> 3. Start Forces using Steam (**Without** pressing Save or Save and Play)

Already had MSCV++ 2019, but I reinstalled it just to make sure.
Deleting codes.dll and starting Forces straight through Steam seemed to have made it work.

**Comment by thesupersonic16** [comment]
Can you try replace the dll with what I have in this zip and see if the game still boots?

[Codes.zip](https://github.com/thesupersonic16/HedgeModManager/files/5150316/Codes.zip)

**Comment by pastelaura** [comment]
> Can you try replace the dll with what I have in this zip and see if the game still boots?
> 
> [Codes.zip](https://github.com/thesupersonic16/HedgeModManager/files/5150316/Codes.zip)

Does not boot with the new .dll
Upon further testing, it seems like deleting the codes.dll file will make the mod loader work, but only through Steam and if no codes or mods are selected.

**Comment by thesupersonic16** [comment]
Sounds like an issue with CommonLoader which isn't my code. Best I can suggest at the moment is checking if [.NET Framework 4.8](https://go.microsoft.com/fwlink/?linkid=2088631) is installed which should be by default.

I will have to talk to someone else about this issue.

**Comment by pastelaura** [comment]
> Sounds like an issue with CommonLoader which isn't my code. Best I can suggest at the moment is checking if [.NET Framework 4.8](https://go.microsoft.com/fwlink/?linkid=2088631) is installed which should be by default.
> 
> I will have to talk to someone else about this issue.

Just checked and .NET Framework 4.8 is indeed installed. 

Alright.

**Comment by supersonicmaker** [comment]
I've been having the same problem, though I found out that d3d11.dll won't let the game start.

**Comment by thesupersonic16** [comment]
@pastelaura This version has CommonLoader disabled so we can see if it is really at fault. To try this:

1. Close HedgeModManager.
2. Navigate to your exec folder.
3. Delete `d3d11` if it still exists
4. Paste the file inside the zip attached into your `exec` folder and rename it as `d3d11`
5. Open HedgeModManager and press "Save & Play"

[ForcesModLoader.zip](https://github.com/thesupersonic16/HedgeModManager/files/5162186/ForcesModLoader.zip)

**Comment by pastelaura** [comment]
> @pastelaura This version has CommonLoader disabled so we can see if it is really at fault. To try this:
> 
> 1. Close HedgeModManager.
> 2. Navigate to your exec folder.
> 3. Delete `d3d11` if it still exists
> 4. Paste the file inside the zip attached into your `exec` folder and rename it as `d3d11`
> 5. Open HedgeModManager and press "Save & Play"
> 
> [ForcesModLoader.zip](https://github.com/thesupersonic16/HedgeModManager/files/5162186/ForcesModLoader.zip)

This is what I get now with CommonLoader disabled:

[sonic forces commonloader disabled..txt](https://github.com/thesupersonic16/HedgeModManager/files/5165548/sonic.forces.commonloader.disabled.txt)

Same as before, Forces still doesn't want to boot.

**Comment by thesupersonic16** [comment]
Does this issue still occur on the latest HedgeModManager and loaders?

**Comment by pastelaura** [comment]
> Does this issue still occur on the latest HedgeModManager and loaders?

It launched one time when I first tried it on the newest version, but haven't been able to launch it again after that. HedgeModManager does say "Starting Sonic Forces" on the top right when I click "Save and Play" and that message stays for a few seconds before going away, but that's it.

**Comment by thesupersonic16** [comment]
Does the game work when loading the exe file or using the Steam launcher?

**Comment by pastelaura** [comment]
Only if HedgeModManager isn't installed, but if it is installed, no it doesn't.

**Comment by thesupersonic16** [comment]
Does other games like Sonic Generations work with the mod loader installed?

**Comment by pastelaura** [comment]
Yes. It's just Sonic Forces that I have an issue with.

**Comment by thesupersonic16** [comment]
Can you press Shift + F1 in HMM and send the file it selects? The file will contain your config files which I may need to take a look at.

**Comment by pastelaura** [comment]
[HMM_Snapshot_00112021192305.txt](https://github.com/thesupersonic16/HedgeModManager/files/7607296/HMM_Snapshot_00112021192305.txt)

Sure, here you go.

**Comment by thesupersonic16** [comment]
I don't really see anything wrong in the config files.
Since the loader is different than before, can you try disable all mods and codes and see if the game loads up? Make sure the mod loader is still installed.

**Comment by pastelaura** [comment]
Just did that, still the same problem. I have noticed that the game does actually show in task manager when I boot it with HedgeModManager, it just doesn't show on the screen.

**Comment by thesupersonic16** [comment]
I have noticed you have files called `d3d11_shaders.ini` and  `dinput8.dll`. Do you know what these are for? Also can you uninstall SFMI, it has been made obsolete years ago.

**Comment by pastelaura** [comment]
I don't recall what they are for and done.

**Comment by thesupersonic16** [comment]
I guess remove `dinput8.dll` and try start the game again, its the only thing I can think of that would conflict with the ML.

**Comment by pastelaura** [comment]
Can confirm that dinput8.dll was the thing that was preventing the game from booting with HedgeModManager. It's fully working now.

**Comment by thesupersonic16** [comment]
No idea what that is for. As for the `d3d11_shaders.ini`, if you intend to install ReShade you can follow the instructions [here](https://github.com/thesupersonic16/HedgeModManager/wiki/Loading-DirectX-Dlls).

Since you said the game is now working I will now close this issue. Feel free to comment if you still have the issue.
