### ISSUE TITLE
Game crashes with Horizontal Stomp Code enabled

### ISSUE THREAD

**Issue by ghost** [thesupersonic16/HedgeModManager#137]
Randomly after the game starts, the game crashes with the "Stomp Keeps Horizontal Recovery" code enabled. Often happens soon after entering a level and playing the game normally after a few seconds. Does not seem to affect Classic Sonic. Can confirm this happens with no other mods or codes enabled.

**Comment by Sajidur78** [comment]
make sure your code list is updated

**Comment by ghost** [comment]
It is.

**Comment by thesupersonic16** [comment]
Does this issue still occur on the latest HedgeModManager and loaders?

**Comment by ghost** [comment]
No. Turns out the issue is compatibility between the Horizontal Stomp Code and the BetterGenerationsConfigTool project. I no longer use that project, so it isn't an issue anymore.

https://github.com/PTKickass/BetterGenerationsConfigTool

**Comment by PTKay** [comment]
You should switch to using the rewrite instead of the modified version

https://github.com/PTKickass/GenerationsConfigTool_Rewrite
