### ISSUE TITLE
Project Unleashed won't load past first level.

### ISSUE THREAD

**Issue by rocketsocket204** [thesupersonic16/HedgeModManager#139]
I know this issue has to do with renaming the pam000 file, and I did, but the game still doesn't load and crashes after the first level. My graphics card is an NVIDIA GeForce GTX 1660 Ti.

**Comment by thesupersonic16** [comment]
Not a HedgeModManager issue. Closing.

I recommend checking the [RTX Fix](https://gamebanana.com/gamefiles/12115) as the NVIDIA GeForce GTX 1660 Ti is a Turing based GPU.
