### ISSUE TITLE
[Forces] New Feature Request !

### ISSUE THREAD

**Issue by Raphpower** [thesupersonic16/HedgeModManager#14]
It will be good to have in Mods / Codes a 100% Save Game works !
Because the game just deleted my save , but my records stay in Multiplayer.
It happens not just for me but for friends too , that's why i ask this feature.
Thanks in advance !

**Comment by StreakSharpshot** [comment]
Same thing happened to me initially, But I just beat the game again. It's really short.

**Comment by thesupersonic16** [comment]
I might add a feature that will backup your save file, But I don't want to have to store a 100% save file in the Manager, If you need a 100% save file, You will have to find one and Re-Encrypt it yourself.

Also we don't fully understand the Save file yet, Only the Encryption and a little about the flags

**Comment by Sajidur78** [comment]
Closed due to feature not being related to the mod manager or the mod loader
