### ISSUE TITLE
HedgeModManager doesn't recognize Sonic Generations anymore and it requires me to download the Runtime 2019 every time I click on save and play

### ISSUE THREAD

**Issue by JustMonikaBlyat420** [thesupersonic16/HedgeModManager#146]
[HMM_Snapshot_00102020182755.txt](https://github.com/thesupersonic16/HedgeModManager/files/5355937/HMM_Snapshot_00102020182755.txt)
HMM Info:
```
    Version: 7.2-6
    Args: 
    StartDir: H:\Games\Sonic Generations\
    Process Level: Administrator
    Game: Unnamed Game
```

Exception:
```
    Type: UnauthorizedAccessException
    Message: Access to the path 'C:\Users\pdls\AppData\Local\Temp\tmp605A.tmp' is denied.
    Source: mscorlib
    Function: Void WinIOError(Int32, System.String)
    StackTrace: 
       at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
       at System.IO.File.InternalDelete(String path, Boolean checkHost)
       at System.IO.File.Delete(String path)
       at HedgeModManager.HedgeApp.GetCPKREDIRFileVersion(Nullable`1 packed)
       at HedgeModManager.HedgeApp.Main(String[] args)
    InnerException: 
```

**Comment by thesupersonic16** [comment]
Give this build a try and let me know if this resolves your issue.

[HedgeModManager.zip](https://github.com/thesupersonic16/HedgeModManager/files/5356001/HedgeModManager.zip)

**Comment by JustMonikaBlyat420** [comment]
Sadly no. This is what pops up now
[image: image.png]


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by thesupersonic16** [comment]
Sounds like your anti virus is preventing HMM from performing a CPKREDIR check. Also I can not see the image. 

The best I can suggest right now is try set HMM as an exception in your anti virus and see if that fixes the issue.

**Comment by thesupersonic16** [comment]
As a note to this issue closure, we do not support non-Steam/pirated versions of Sonic Generations. Please install the game normally using Steam.
