### ISSUE TITLE
[Forces] Not responding.

### ISSUE THREAD

**Issue by greggrules23** [thesupersonic16/HedgeModManager#15]
Everytime i add a mod of sonic forces the game just crashes and says sonic forces is not responding.
i even installed the code loader or whatever that thing is

**Comment by thesupersonic16** [comment]
idk What would cause that issue, Can you please archive your wars_mods.cpk into a 7z and send it here, so I can see whats happening in it?

**Comment by thesupersonic16** [comment]
We have updated the Manager and the Loader, Can you please confirm if this issue still exists on the newest version?

**Comment by thesupersonic16** [comment]
Closing this as ForcesCodeLoader has changed alot and we had a new update, Reopen If Issue continues.
