### ISSUE TITLE
[Sonic Generations] its my first time getting this issue so im not sure exactly whats going on here. does anyone know what i have to do to fix this?

### ISSUE THREAD

**Issue by iwuhfu9ahs** [thesupersonic16/HedgeModManager#153]
HMM Info:
```
    Version: 7.2-6
    Args: 
    StartDir: C:\Program Files (x86)\Steam\steamapps\common\Sonic Generations\
    Process Level: User
    Game: Sonic Generations
    SteamGame: Sonic Generations
```

Exception:
```
    Type: ArgumentException
    Message: Illegal characters in path.
    Source: mscorlib
    Function: Void CheckInvalidPathChars(System.String, Boolean)
    StackTrace: 
       at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
       at System.IO.Path.InternalGetDirectoryName(String path)
       at HedgeModManager.HedgeApp.FindAndSetLocalGame()
       at HedgeModManager.HedgeApp.Main(String[] args)
    InnerException: 
```

**Comment by thesupersonic16** [comment]
Can you send the snapshot file that was generated when you posted this issue report? it should be in the same folder as HedgeModManager.exe and should look something like `HMM_Snapshot_060112020052110`

**Comment by iwuhfu9ahs** [comment]
![bilde](https://user-images.githubusercontent.com/74077393/98439135-08fd7400-20f0-11eb-9ed5-c6f0d0bea064.png)
is it this one?

**Comment by iwuhfu9ahs** [comment]
this was the only file that got generated when i tried submiting the report.

**Comment by Sajidur78** [comment]
Thats the file

**Comment by iwuhfu9ahs** [comment]
[HMM_Snapshot_00112020115426.txt](https://github.com/thesupersonic16/HedgeModManager/files/5504642/HMM_Snapshot_00112020115426.txt)
hopefully this is it if not then ill try again.

**Comment by thesupersonic16** [comment]
You have a bad configuration file. Delete the cpkredir.ini file (the file with the paper with a single gear icon)

Let me know if this fixes the issue and if you ever encounter the issue again in the future please reply back so we can look into what might have gone wrong.

**Comment by iwuhfu9ahs** [comment]
alright will do

**Comment by iwuhfu9ahs** [comment]
![bilde](https://user-images.githubusercontent.com/74077393/98441742-8df08980-2100-11eb-8fd2-de3844daa003.png)

**Comment by iwuhfu9ahs** [comment]
it works now! thank you so much for the help both of you!

**Comment by thesupersonic16** [comment]
Good to hear. Reopen the issue if you encounter the issue again.

**Comment by iwuhfu9ahs** [comment]
will do!
