### ISSUE TITLE
[Sonic Generations] Mods nor Codes work 

### ISSUE THREAD

**Issue by Wario-Dude** [thesupersonic16/HedgeModManager#155]
Whenever I open the game with the Hedgehog Mod Manager, the mods and codes that I have selected will not load, which causes the game to be the same old vanilla Sonic Generations. I tried replacing both the ModsDB file, as well as the cpkredir file, despite my efforts, both the mods and the codes refuse to work. I would appreciate it if you were to respond soon.

**Comment by Sajidur78** [comment]
Sorry for the late response, is this issue still happening?
