### ISSUE TITLE
[Bug] HMM isn't allowing me to download some files from gamebanana.com

### ISSUE THREAD

**Issue by MyNameIsSTHB** [thesupersonic16/HedgeModManager#156]
## Describe the issue/bug

I was just downloading a bunch of mods of Sonic Forces to juice up things, and yesterday it crashed, I clicked at around 10 mods, so I didn't blame the HMM, but today I was with only 3 and it "ran into a fatal error!".

## Expected Behaviour

I expected it to download and extract the mod files as it usually does, but it didn't even finish the download.

## Additional Context

My laptop only has 4 GB of RAM, so considering that I had a lot of Google Chrome tabs and also Discord running, maybe that had something to do? I'll attach both logs from yesterday and the one from today.
[HMM_Snapshot_00122020011350.txt](https://github.com/thesupersonic16/HedgeModManager/files/5660709/HMM_Snapshot_00122020011350.txt)
[HMM_Snapshot_00122020120815.txt](https://github.com/thesupersonic16/HedgeModManager/files/5660710/HMM_Snapshot_00122020120815.txt)

**Comment by thesupersonic16** [comment]
Sorry for the late reply, if you can still reproduce the crash can you also include the crash information?
