### ISSUE TITLE
Compatibility issues with D3DOverrider

### ISSUE THREAD

**Issue by BrazilianDood** [thesupersonic16/HedgeModManager#157]
Like the title says, the HedgeModManager somehow breaks D3DO which is an important tool to get rid of screen tearing in the game (in my case being Sonic Generations), without having to use the terrible vsync option that comes in the vanilla configuration tool. 
At first I thought the mods I was using were related to this issue, but even if I launch Sonic Generations without any mods applied it still doesn't work with D3DO, the only way to make it work again is to uninstall the mod loader...
I must also add that GMI didn't have this issue, D3DO worked normally alongside it, but GMI is just outdated and doesn't work with many new mods, oh and I also tried to apply vsync using AMD's tool, but that also didn't work...

**Comment by thesupersonic16** [comment]
You may have to make a mod to inject the application. 

You should beable to do this by clicking "Add Mod" and selecting "Making one (for developers!)" then adding the name of the dll that D3DOverrider uses. After that give the mod a name and click OK and a folder should open up. In that folder copy the dll for the application.

This is assuming the application you are using injects using d3d9.dll like what HedgeModManager uses
