### ISSUE TITLE
[Forces] Can't change mods folder location

### ISSUE THREAD

**Issue by ccateni** [thesupersonic16/HedgeModManager#16]
It just shows a nonexistent folder, and I can't select the folder I want to go to.

**Comment by thesupersonic16** [comment]
We have not implemented this into Forces yet.

**Comment by EnderPreston** [comment]
Well, shoot. Wish i knew that BEFORE I wrote my version of this complaint.

**Comment by thesupersonic16** [comment]
Implementing it shouldn't be too hard, I just never gotten around to it.
I will try to add it for the next release which I have no idea when I'll release it.

**Comment by thesupersonic16** [comment]
Added in 5c949467dac9f7f869fb8b68df09b83040f5e003 and f2bc8005d8af1206e7d5c52d3e0abb3866b08ff2
