### ISSUE TITLE
Mods crashing the game

### ISSUE THREAD

**Issue by ghost** [thesupersonic16/HedgeModManager#165]
I just tried a mod i havent tried before and it crashes my game. I have no idea why or how this keeps happening. The mod that crashes it is the STH2006 project demo 3.

I expect it to load fine like it does with other mods.

This is annoying. I feel i might have made an issue with this but i dont remember doing so.

**Comment by ghost** [comment]
how do i stop mods crashing the game?

**Comment by thesupersonic16** [comment]
Not a HedgeModManager issue. You have mentioned in the past you have a GTX 1660 Ti which uses the Turing architecture which is known to crash many old Sonic Generations mods. 

Unfortunately we can't do anything to resolve your issue. You might have to find/make a fix for every mod with the same issue or replace the GPU with something that's not in the 2000s and 1660.

Some other mods however has RTX fixes which may help like for Unleashed Project. I hope you understand.

Edit: I was told Ampere cards (3000s) also has the same issue.

**Comment by ghost** [comment]
How do i replace the gpu? Do i have to take my pc apart to replace it?
