### ISSUE TITLE
[Sonic Generations] Codes are not working

### ISSUE THREAD

**Issue by ShadoWorld69** [thesupersonic16/HedgeModManager#166]
If I try to play Sonic Generations with some of the codes on, it crashes right on startup. Sometimes, however, I manage to get into the hub world with some particular, but any stage I select makes it crash.

When first using HMM, I expected the codes to work completely fine, but it crashed. I try again, then the game crashed. And when I tried using mods, they worked completely fine.

**Comment by Sajidur78** [comment]
Please specify what codes cause crashes.
