### ISSUE TITLE
[Bug] Sonic Lost World asm crashes the game

### ISSUE THREAD

**Issue by Muzzarino** [thesupersonic16/HedgeModManager#169]
When a custom assembley injection code is executed, even when the opcodes point to the correct address, the game crashes after one line on the codecave is executed. The codes specified in the hook on Lost World is supposed to be executing properly like Generations and Forces, but isn't doing so on Lost World as the main reason for it doesn't make the allocated address executable.

Example: string code = @"nop"

**Comment by Sajidur78** [comment]
Hi, Thanks for the report! The issue has been fixed as of da1d91c7198eccc31c2c0ba07d906a1a8f461ab5. Make sure to update the code loader when prompted.
