### ISSUE TITLE
HedgeModManager: No Trick Rainbow Ring

### ISSUE THREAD

**Issue by TheKoldK1** [thesupersonic16/HedgeModManager#170]
When I enable the 'no trick rainbow ring' code, it does not play the sound effect when you go through one. Is there a way that it can be fixed?

**Comment by PTKay** [comment]
This is the code's normal behaviour. The game's missing the sound for that specific type of Rainbow Ring, so it plays no sound. To enable sound you'd need to edit the Sonic Generations game files to include the missing sound file. An example of that can be seen on [this mod](https://drive.google.com/file/d/1GlKge8TS1FFX2bySZQK9X-iNVawSG6yB/view), which includes the missing sound alongside its other modifications.

**Comment by TheKoldK1** [comment]
Which programs would be suitable to use to edit those game files?

**Comment by Sajidur78** [comment]
You don't need to edit the game files, just get the mod linked above and you should be good to go. Here's the link again if you missed it. https://drive.google.com/file/d/1GlKge8TS1FFX2bySZQK9X-iNVawSG6yB/view
