### ISSUE TITLE
AWB Streaming Missing in The Latest Version

### ISSUE THREAD

**Issue by MarioTainaka** [thesupersonic16/HedgeModManager#18]
AWB Streaming is missing so all the music dies. ACB's are read though.
![skyth](https://user-images.githubusercontent.com/32436919/35128790-7fdf3086-fc9f-11e7-814a-38b023ec0c38.png)

**Comment by slashiee** [comment]
Solved as of aa0b257e752a502c26439dec0efaf8ce885c658b

**Comment by thesupersonic16** [comment]
Forgot you can do that

**Comment by MarioTainaka** [comment]
good job guys
