### ISSUE TITLE
Codes Not Working 

### ISSUE THREAD

**Issue by JoeMama100** [thesupersonic16/HedgeModManager#181]
Ive Tried Everything and my Hotplugging Support And Always Can Activate Super Codes wont work

**Comment by thesupersonic16** [comment]
Does other codes work?

**Comment by JoeMama100** [comment]
nope

**Comment by thesupersonic16** [comment]
Did you make sure GCL is installed in the Setting tab?

**Comment by JoeMama100** [comment]
whats is  GCL

**Comment by thesupersonic16** [comment]
Generations Code Loader. Make sure its enabled.

**Comment by JoeMama100** [comment]
it is

**Comment by thesupersonic16** [comment]
Are you selecting the codes and then pressing Save & Play?

**Comment by JoeMama100** [comment]
yeah

**Comment by thesupersonic16** [comment]
Please send me a screenshot of the Settings tab on HedgeModManager.

**Comment by JoeMama100** [comment]
![Screenshot (14)](https://user-images.githubusercontent.com/79614824/110410109-61b92b00-8056-11eb-9d84-b29e95a489b1.png)

**Comment by thesupersonic16** [comment]
Does the game still load mods?

**Comment by JoeMama100** [comment]
yes

**Comment by thesupersonic16** [comment]
Can you press Shift + F1 on HedgeModManager and send the file it generates? It should start with `HMM_Snapshot_`

**Comment by JoeMama100** [comment]
[HMM_Snapshot_00032021002953.txt](https://github.com/thesupersonic16/HedgeModManager/files/6106056/HMM_Snapshot_00032021002953.txt)
you mean this

**Comment by thesupersonic16** [comment]
I have just taken a look at the report and I don't see any issues. Can you check if `Codes.dll` exists in the mods folder? You don't need to send it, just need to know its there.

**Comment by JoeMama100** [comment]
yup

**Comment by thesupersonic16** [comment]
What Anti-Virus does your computer use?

**Comment by JoeMama100** [comment]
avast free antivirus

**Comment by thesupersonic16** [comment]
Try temporarily turning it off.

**Comment by JoeMama100** [comment]
turned it off

**Comment by thesupersonic16** [comment]
Does codes work now?

**Comment by JoeMama100** [comment]
no
