### ISSUE TITLE
can i use this on puyo puyo tetris 2

### ISSUE THREAD

**Issue by RagdollClash** [thesupersonic16/HedgeModManager#186]

**Comment by Sajidur78** [comment]
its not sonic

**Comment by RagdollClash** [comment]
but its hedgehog engine 2 :(

**Comment by Sajidur78** [comment]
but it aint a hedge

**Comment by RagdollClash** [comment]
bro..

**Comment by PTKay** [comment]
![Captura de ecrã 2021-03-23 224334](https://user-images.githubusercontent.com/20132880/112228455-3a06bd00-8c29-11eb-89f9-4f643e9fffa2.png)

**Comment by RagdollClash** [comment]
but thats a loser
<img alt="2021-03-23_15-27-54_PuyoPuyoTetris2" src="https://user-images.githubusercontent.com/15317421/112228510-a4e6d280-8bee-11eb-8699-66b7c787f9e6.png">

**Comment by blueskythlikesclouds** [comment]
this is truly a brother moment

**Comment by thesupersonic16** [comment]
Hi

**Comment by RagdollClash** [comment]
epic

**Comment by thesupersonic16** [comment]
Incase anyone wants a clear answer.


Yes.
