### ISSUE TITLE
[Puyo Puyo Tetris 2] (Suggestion) Merging pacs' diffs

### ISSUE THREAD

**Issue by ArMM1998** [thesupersonic16/HedgeModManager#189]
So there are many .pac files that have all the art for characters, like say charaselect_1p_2p.pac which has all portraits in the character select screen.
This generates conflict if you're trying to use two different character mods. I think the way this could be fixed is by allowing to merge the .pacs. Maybe only the diffs?

Though there are also other .pac files (like character select icons) that have all the character art in a single texture, so it would conflict there too...
Maybe those textures can also be merged with diffs?

**Comment by Sajidur78** [comment]
Hi, while this is a great idea, we currently don't have any plans for a feature like this.
