### ISSUE TITLE
Error d3d11createdeviceandswapchain Win 8.1

### ISSUE THREAD

**Issue by Bufekni** [thesupersonic16/HedgeModManager#19]
Hello
i use the HedgeModManager But when I press it to save & play it starts a cmd which I think is normal but then I get an error of a thing called d3d11createdeviceandswapchain in the d3d10_1 dll and I do not know how to fix it.
I can not find a way to fix this error and that is why I report it here.

**Comment by thesupersonic16** [comment]
Can you please attach a screenshot of the error?

**Comment by Bufekni** [comment]
Yes, Yes.... The Only Problem is that my pc is in Spanish since I am from Chile but I still pass the screenshot.
I'm using google translator 
![tajegia](https://user-images.githubusercontent.com/36089219/35773022-614896fc-0925-11e8-93cf-8f9a2cb27712.png)

**Comment by thesupersonic16** [comment]
The export is in d3d11.dll, Does the game work without the mod loader?

**Comment by Bufekni** [comment]
Yes, the game work whithout the mod loader

**Comment by thesupersonic16** [comment]
I'll send you a build

**Comment by Bufekni** [comment]
ok.

**Comment by thesupersonic16** [comment]
[Download](https://github.com/thesupersonic16/HedgeModManager/files/1692333/d3d11.zip) Let me know if this works or not.

**Comment by Bufekni** [comment]
I can not put the dll, I skip a message saying that I need permission to put it.
I'm putting the file in System32

**Comment by thesupersonic16** [comment]
Don't put it in System32
Just log off and log back in

**Comment by thesupersonic16** [comment]
The Dll I sent links to the dll in System32, Putting it in System32 will make things much worse.

**Comment by Bufekni** [comment]
Ok, so I just leave it in place other than System32?

Ah yes, maybe suddenly I can get to answer a little late but I will try to answer you as fast as I can.

**Comment by Bufekni** [comment]
Hello, The HedgeModManager Now Works in my pc :)
Thanks.
