### ISSUE TITLE
[Bug] help I cant I can't close the window :(

### ISSUE THREAD

**Issue by Radfordhound** [thesupersonic16/HedgeModManager#196]
## Describe the issue/bug

I try to close thwe window but the button is gone
## Expected Behaviour

I remember there used to be an X and my son (he's really good with all of that tech stuff) told me "always click the X to close the window" so I would always just click the X but now the X is gone.

what did you do to the X

where is he

I just want the X back
## Additional Context

I think also the text in the about menu has a speech impediment now sometimes?!? I asked my son but he isn't sure

**Comment by Knuxfan24** [comment]
Just press ALT-F4 bro.

**Comment by thesupersonic16** [comment]
Thanks for the heads-up, the issue will be looked at as soon as possible.

**Comment by Radfordhound** [comment]
:joy: 👍

**Comment by Radfordhound** [comment]
hey wait a minute I didn't mean to close the issue I was  just trying to close the window

**Comment by RagdollClash** [comment]
delete system31
