### ISSUE TITLE
hedgemodmanager has a white theme and words are all messed up

### ISSUE THREAD

**Issue by oof24** [thesupersonic16/HedgeModManager#197]
this what hedgemodmanager looks like for me, How do I fix it?
![help](https://user-images.githubusercontent.com/81753322/113288132-881c6000-92bc-11eb-86ba-b3eb649529e0.PNG)
![help 2](https://user-images.githubusercontent.com/81753322/113288156-910d3180-92bc-11eb-8be2-63f8871f7e99.PNG)

**Comment by thesupersonic16** [comment]
Its an April Fools joke. It will revert back after the day ends in your time zone.

The white theme is also planned to be carried over in newer HMM versions but with an option so you can enable it if you were to like it.

**Comment by oof24** [comment]
ok thanks

**Comment by RagdollClash** [comment]
closing since this is just an april fools joke
