### ISSUE TITLE
[Gens] Mod Not Working Correctly

### ISSUE THREAD

**Issue by johnbb10** [thesupersonic16/HedgeModManager#20]
Whenever I try running the Unleashed Project, it doesn't work and Sonic Generations runs as normal. But when I go into say Green Hill, Windmill Isle plays, or Savannah Citadel in Chemical plant. The Unleashed music is all there but the levels themselves are not. How do I resolve this issue?

**Comment by marcussacana** [comment]
This will take a time, for now i have only tested the mod with the Sonic Force...

**Comment by marcussacana** [comment]
you can give-me download link to this 2 games to my email?
ddtank.marcus@gmail.com

**Comment by thesupersonic16** [comment]
On the Settings tab does it say CPKREDIR is installed?

**Comment by Sajidur78** [comment]
Closed for inactivity and this was a CPKREDIR bug.
