### ISSUE TITLE
Hedgemodmanager keeps getting deleted  by free microsoft antivirus 

### ISSUE THREAD

**Issue by oof24** [thesupersonic16/HedgeModManager#210]
I keep trying to download it but It keeps getting deleted. pls help

**Comment by thesupersonic16** [comment]
Try making sure your Windows Defender definitions are up to date.

You can do this by opening "Windows Security" and selecting "Virus & threat protection" then clicking the link "Check for updates" then the button "Check for updates".

**Comment by oof24** [comment]
ok

**Comment by thesupersonic16** [comment]
Issue is old, but has already been solved with current Windows Security definitions.
