### ISSUE TITLE
[Sonic Generations] Mods not loading

### ISSUE THREAD

**Issue by JudiiDoodle** [thesupersonic16/HedgeModManager#211]
## Describe the issue/bug

After playing a few mods on the manager, I've noticed that the mods I select on the mod loader don't load anymore.

## Expected Behaviour

I expected it to work for at least a little longer than like, a day.
## Additional Context

There are no error messages, the vanilla game just loads up normally.

**Comment by Sajidur78** [comment]
Hi, could you provide us some more details? mostly, provide a snapshot. On the HMM window press `Shift + F1`. It will generate a snapshot txt file.
