### ISSUE TITLE
[Forces] Suggestion

### ISSUE THREAD

**Issue by KaleTheFox14** [thesupersonic16/HedgeModManager#22]
Can there be an option for the Command prompt to NOT need to stay open?

**Comment by slashiee** [comment]
cpkredir has an option similar to this `LogType=console` so I don't see why this shouldn't be an option

**Comment by thesupersonic16** [comment]
I can add that option, Just never gotten around to it.

**Comment by thesupersonic16** [comment]
Added to ForcesModLoader 6.3

Sorry for the huge delay

**Comment by thesupersonic16** [comment]
Re opening due to lack of testing on FML 6.3 sorry.

**Comment by thesupersonic16** [comment]
Forgot to close after the release of FML 6.4 and FML 6.5
