### ISSUE TITLE
Cutscenes crashing the game (Sonic Generations)

### ISSUE THREAD

**Issue by Hydrocity544** [thesupersonic16/HedgeModManager#225]
Whenever I finish an Act 2 or a boss for almost any boss the game freezes in its tracks and refuses to play the cutscene. This has happened prominenly in Rooftop Run Act 2, Seaside Hill Act 2, Chemical Plant Act 2, and Vs. Chaos. I thought it might've have done something to do with the 720p cutscenes mod, but after restoring the original cutscenes it still does this. It is very inconsistent as well because some mod combinations make certain cutscenes start while other cutscenes might also crash.

**Comment by thesupersonic16** [comment]
Does this still happen after completing the following steps?
1. Verify the game files for corrupted files by opening the steam URL and waiting for Steam to finish downloading `steam://validate/71340`
2. Making sure all mods and codes are unchecked.
