### ISSUE TITLE
I cant open Hedgemod Manager 

### ISSUE THREAD

**Issue by Mylocoistoopoco** [thesupersonic16/HedgeModManager#231]
HMM Info:
    Version: 7.3-3
    Args: 
    StartDir: C:\Users\pilot\Favorites\Downloads\
    Process Level: User
    Game: Unnamed Game

Exception:
    Type: TypeInitializationException
    Message: The type initializer for 'HedgeModManager.RegistryConfig' threw an exception.
    Source: HedgeModManager
    Function: Void Load()
    StackTrace: 
       at HedgeModManager.RegistryConfig.Load()
       at HedgeModManager.HedgeApp.Main(String[] args)
    InnerException: System.UnauthorizedAccessException: Access to the registry key 'HKEY_CURRENT_USER\SOFTWARE\HEDGEMM' is denied.
   at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.CreateSubKeyInternal(String subkey, RegistryKeyPermissionCheck permissionCheck, Object registrySecurityObj, RegistryOptions registryOptions)
   at Microsoft.Win32.RegistryKey.CreateSubKey(String subkey)
   at HedgeModManager.RegistryConfig.Load()
   at HedgeModManager.RegistryConfig..cctor()

**Comment by thesupersonic16** [comment]
Are you using any Anti-Virus besides Windows Defender?

**Comment by Mylocoistoopoco** [comment]
I am using Macafee as my Anti-Virus

**Comment by thesupersonic16** [comment]
Maybe try add HedgeModManager as an exception on that.

**Comment by Mylocoistoopoco** [comment]
I did that and it still crashed with the same exception.

**Comment by thesupersonic16** [comment]
It might be possible there is a permission issue in your registry. Does running the application as admin work?

**Comment by Mylocoistoopoco** [comment]
That worked. Thank You!

**Comment by thesupersonic16** [comment]
I would not rely on running HedgeModManager as administrator. It will work fine, but its not what this application is designed to run as.

The best I can suggest that might help fix it is maybe try redownloading HedgeModManager in another folder like the game folder or your desktop. and if you know how to use regedit, delete the `HEDGEMM` subkey from `HKEY_CURRENT_USER\SOFTWARE`

**Comment by Mylocoistoopoco** [comment]
I moved the installation onto a External Drive which did fix it. Thanks for the help!
