### ISSUE TITLE
Github has dropped TLSv1 support, breaking updates.

### ISSUE THREAD

**Issue by FateForWindows** [thesupersonic16/HedgeModManager#24]
As of February 22nd, Github has removed TLSv1 support, which breaks many applications and has a pretty big effect on console homebrew applications. It also seems to cause HedgeModManager to fail to update properly.

**Comment by slashiee** [comment]
@thesupersonic16

**Comment by thesupersonic16** [comment]
I was wondering why the GitHub Api wasn't working.

**Comment by slashiee** [comment]
1cc21a6e325f377de7d261a40aef111afa317b54
