### ISSUE TITLE
Trying to Launch HMM for the first time on a newly-built system with Generations installed. Have all the dependencies already installed

### ISSUE THREAD

**Issue by danielzx2** [thesupersonic16/HedgeModManager#251]
[HMM]([HMM_Snapshot_00062021080201.txt](https://github.com/thesupersonic16/HedgeModManager/files/6636184/HMM_Snapshot_00062021080201.txt)) Info:
```
    Version: 7.4-2
    Args: 
    StartDir: L:\
    Process Level: User
    Game: Unnamed Game
```

Exception:
```
    Type: NullReferenceException
    Message: Object reference not set to an instance of an object.
    Source: HedgeModManager
    Function: System.Collections.Generic.List`1[HedgeModManager.SteamGame] SearchForGames(System.String)
    StackTrace: 
       at HedgeModManager.Steam.SearchForGames(String preference)
       at HedgeModManager.HedgeApp.Main(String[] args)
    InnerException: 
```

**Comment by Sajidur78** [comment]
Hi, you're using 7.4-2, this issue was fixed in 7.4-3.

**Comment by thesupersonic16** [comment]
Update to 7.4-3 using this link [HedgeModManager.exe](https://github.com/thesupersonic16/HedgeModManager/releases/download/7.4-3/HedgeModManager.exe).

Reopen this issue if the issue was not resolved.

**Comment by danielzx2** [comment]
You can close this issue now. It works for me without issues after downloading the new version.

Thank you for everything!
