### ISSUE TITLE
New version is a "Virus"

### ISSUE THREAD

**Issue by Anavereagesonicfan** [thesupersonic16/HedgeModManager#253]
Google and Microsoft say it's a virus when I download it and it's probably not

**Comment by Anavereagesonicfan** [comment]
I have use previous versions before and they were fine, in fact I updated from a previous version.

**Comment by thesupersonic16** [comment]
Thanks for letting us know, If this continues to later today I will send a sample to Microsoft which should allow you to download the new version again. Can't do much for Google unless you mean it saying "Failed - Virus detected" in Chrome.

**Comment by Anavereagesonicfan** [comment]
![image](https://user-images.githubusercontent.com/85766102/121766675-aff53300-cb4b-11eb-9498-4d46c11c0744.png)
It looks like this when I download it (only one download was made)

**Comment by thesupersonic16** [comment]
HedgeModManager should no longer be flagged as malware. Make sure your definitions are up to date and HedgeModManager should update smoothly.

If there are still any related issues, feel free to send a comment.

Edit: well MS claims they fixed it.
