### ISSUE TITLE
[Puyo Puyo Tetris 2] 

### ISSUE THREAD

**Issue by ValVoice** [thesupersonic16/HedgeModManager#257]
## Describe the issue/bug

Installing the Mod Loader prevents the game from booting up.

## Expected Behaviour

I expected HedgeModManager to boot into the game with the mods applied.

## Additional Context

The issue also happens with no mods enabled.

**Comment by thesupersonic16** [comment]
Can you please follow the following steps:
1. Open Steam
2. Right click "Puyo Puyo Tetris 2"
3. Click on "Properties"
4. A window will show up, click on "Local Files"
5. Click "Verify integrity of game files..."
6. After the process is finished, Open HedgeModManager
7. Go to the Settings tab
8. Ensure "Puyo Puyo Tetris 2" is selected
9. If the button on the left says "Uninstall Mod Loader", click it
10. Click "Install Mod Loader"
11. Enable "Enable debug console"
12. Start the game on Steam

If the game still does not run after following the steps, please describe what you saw including if you saw any text in a black window. Also in HedgeModManager press Shift + F1 and HedgeModManager should show a message to include a file to this issue and a file explorer window should show up with the needed file selected. This file contains a little bit of info about your game install and all of the mod configs.

**Comment by ValVoice** [comment]
Well, I’ve made sure that the game files are in their original state, and the debug window closes shortly after trying to boot the game without a peep.

Why does the mod loader seem to require Steam in the first place? Besides the functionality to restore game files to their unmodified state (which they are in), it’s unnecessary for a *mod loader*. PPT1’s mod loader had no such restrictions.

Will update with that Shift F1 trick tomorrow morning.

**Comment by thesupersonic16** [comment]
> Why does the mod loader seem to require Steam in the first place? Besides the functionality to restore game files to their unmodified state (which they are in), it’s unnecessary for a mod loader. PPT1’s mod loader had no such restrictions.

The modloader does not require Steam. The game requires Steam to run correctly. And in the instructions I wanted to make sure the game files are fully up to date.

EDIT: Also the modloader **only** works on the newest version of PPT2 at the time writing this. Which is why I'm asking.

**Comment by ValVoice** [comment]
I pressed Shift+F1 on HMM and nothing happened.

This is what shows up before it fails to boot the game:
![CCTn5geAXV](https://user-images.githubusercontent.com/86004740/122321504-ecb39680-cf5e-11eb-94eb-1025b0e48d75.png)

**Comment by RagdollClash** [comment]
Is your game updated to the latest PPT2 version?

**Comment by ValVoice** [comment]
> Is your game updated to the latest PPT2 version?

How do you check?

**Comment by thesupersonic16** [comment]
> How do you check?

If the instructions are followed correctly, the game will be up to date. 

> I pressed Shift+F1 on HMM and nothing happened.

That's weird. Maybe try again. While looking at the mod list hold any one of the shift keys on your keyboard then press the F1 key.

**Comment by ValVoice** [comment]
> If the instructions are followed correctly, the game will be up to date.

Then it is up to date.

> That's weird. Maybe try again. While looking at the mod list hold any one of the shift keys on your keyboard then press the F1 key.

[Does not work.](https://www.youtube.com/watch?v=OmMaSFlNQPw)

**Comment by thesupersonic16** [comment]
Maybe try running Steamless on your game exe. This will rule out any DRM issues.
After running Steamless make sure to rename `PuyoPuyoTetris2.unpacked.exe` to `PuyoPuyoTetris2.exe`

[Steamless GitHub Releases](https://github.com/atom0s/Steamless/releases)

**Comment by ValVoice** [comment]
> Maybe try running Steamless on your game exe. This will rule out any DRM issues.
> After running Steamless make sure to rename `PuyoPuyoTetris2.unpacked.exe` to `PuyoPuyoTetris2.exe`

![image](https://user-images.githubusercontent.com/86004740/122528544-6929a080-d057-11eb-8286-4528fd4bef64.png)

Unpacking seems to fail

**Comment by thesupersonic16** [comment]
Thats weird, never seen it fail.

@ActualMandM Do you have any idea what may be the issue?

**Comment by thesupersonic16** [comment]
It seems to work fine for me and some others. 

Can you ensure the exe hash is: 6FBA333F58581FFCFE37462353DAAF46A6311E81F9A773D07014E9068312F209 (SHA256)
You can check using 7-Zip by right clicking the exe and under CRC SHA then clicking SHA-256. If this does not match, your exe might have been tampered or is corrupt and needs to be redownloaded.

![image](https://user-images.githubusercontent.com/25761885/122567443-030b4080-d08c-11eb-9448-702730bbc37a.png)

**Comment by ValVoice** [comment]
![image](https://user-images.githubusercontent.com/86004740/122626703-e4866300-d0e6-11eb-97c9-30dea627ebe4.png)

**Comment by thesupersonic16** [comment]
That looks right. I might need to look into your crash dumps for any ideas.
They are located in `%localappdata%\CrashDumps` Just run the game again with mods and send me the newest file that starts with `PuyoPuyoTetris2.exe`

You can either post the crash dump here as a zip, send it to me using Discord or email it.

**Comment by ValVoice** [comment]
There's no such folder named CrashDumps, only CrashRpt

**Comment by thesupersonic16** [comment]
Weird. Maybe try this
https://stackoverflow.com/questions/54513815/no-crashdumps-minidumps-are-saved

**Comment by ValVoice** [comment]
I've done some digging around in Visual Studio, and I'm thinking there's some sort of incompatibility with the Tenpex Mod Loader DLL, but there's no source for that as far as I can tell, so I can't do anything about it.

**Comment by thesupersonic16** [comment]
If your willing, you could try compile the DLL as debug and load the crash dump in VS.

The source is at https://github.com/thesupersonic16/TenpexModLoader

**Comment by thesupersonic16** [comment]
TenpexModLoader has had some major updates since this issue has been active, does it still cause any crashes?

**Comment by ValVoice** [comment]
i uninstalled the game because the mod loader was a nonfunctional piece of garbage

**Comment by ActualMandM** [comment]
okay asshole
