### ISSUE TITLE
HedgeModManager: "The calling thread must be STA, because many UI components require this." error.

### ISSUE THREAD

**Issue by SanicBoi74** [thesupersonic16/HedgeModManager#263]
I noticed that whenever I try downloading a mod from GameBanana, it opens HedgeModManager, I click download, and it starts installing the mod, but once it is finished downloading, it gives me an error saying: "Failed to download mod: The calling thread must be STA, because many UI components require this.". This error seems to be happening to me every single time I try downloading any mod for Sonic Lost World and Sonic Forces, and as for Sonic Generations, this has only happened once. What is going on? What does that mean? Why is this error happening whenever I try downloading a mod? supersonic16, if you are reading this right now, please respond to me immediately and please tell me how to fix it, because I do not know how to fix this glitch. I also find it weird how it is only happening with Sonic Lost World and Sonic Forces, and not any of the other games supported by the mod loader. If anyone can provide a fix for this problem, please tell me how to fix it and I could possibly try to fix it. But, if this is a problem that only supersonic16 can fix, I'll let him do the work, instead of me, because I have no expertise doing any of this stuff. Here is a screenshot of what is happening whenever I try downloading a mod, for reference for supersonic16, specifically so that he knows what the problem is. I have also seen and heard of many other programs unrelated to this, but are in the same format, a mod loader, having this same problem, but I have seen no reports for HedgeModManager as of yet. Here is the screenshot for supersonic16's reference to help fix this problem.
![screenshot error](https://user-images.githubusercontent.com/85211610/123854567-b9b0c180-d8d3-11eb-9ff6-a3b4a18ae17d.PNG)

**Comment by thesupersonic16** [comment]
You don't need to throw my name all over the place. We are currently trying to find out the issue.

**Comment by SanicBoi74** [comment]
Sorry, if it's such a problem I'll take the post down. I was just trying to talk to you.

**Comment by SanicBoi74** [comment]
The thing is, though, is that nobody else has reported this issue here and I'm literally the only one who actually reported it. Sorry.

**Comment by ghost** [comment]
I was downloading mods just fine and suddenly started having the same problem.

**Comment by thesupersonic16** [comment]
Does HedgeModManager detect the game your installing mods for?

**Comment by ghost** [comment]
It should since Generations is the only game I have out of the list of games that work for it.

**Comment by thesupersonic16** [comment]
Is the error exactly the same as the image in the original post?

**Comment by ghost** [comment]
Yes.

**Comment by ghost** [comment]
@SanicBoi74 have you managed to get this to work yet?

**Comment by thesupersonic16** [comment]
The cause of this issue was recently discovered and has been fixed in fa7176234a48d8863ca25c161d573c8e8d3a4373. It was an issue trying to show a message asking to install 7-Zip or WinRAR.

7-Zip can be downloaded by clicking this [link](https://www.7-zip.org/a/7z2107-x64.exe).

This issue will be closed on the next release. For now please install either one of the programs mentioned.
