### ISSUE TITLE
Missing Runtime

### ISSUE THREAD

**Issue by Fivavoa** [thesupersonic16/HedgeModManager#270]
Version: 7.5-0
    Game: Sonic Generations

For some reason, I keep getting a Missing Runtime error despite having that runtime. The game launches just fine after I tell it to "install" it.

**Comment by thesupersonic16** [comment]
Does running HedgeModManager as administrator help?

**Comment by Fivavoa** [comment]
It does not unfortunately, and I suppose to provide more information; I have to consistently accept, wait for the download, then the game will run regardless of if I do anything on the install window or not.

**Comment by thesupersonic16** [comment]
Can you check this location in your computer's registry? To do this open your start menu and type `regedit` then press enter, then on the top of the window paste the location and press enter.
`Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\VisualStudio\14.0\VC\Runtimes`

For now, I need to know if the location exists or not, you will hear an error sound if it does not exist.

**Comment by Fivavoa** [comment]
I do have the location, here's a screenshot if it helps:

![Capture](https://user-images.githubusercontent.com/29827600/125014637-4cb3cf00-e02b-11eb-8122-65aea864d1b1.PNG)

**Comment by thesupersonic16** [comment]
Can you select X86 and send a screenshot again?

**Comment by Fivavoa** [comment]
Sure, here you go:

![Capture](https://user-images.githubusercontent.com/29827600/125154138-cc1dcd00-e115-11eb-857e-91bb58912bd8.PNG)

**Comment by thesupersonic16** [comment]
Yeah your runtime seems to be out of date, might be possible the installer is failing.

You can manually install it from here: https://aka.ms/vs/16/release/vc_redist.x86.exe
