### ISSUE TITLE
Sonic Lost World crashing on startup with mods

### ISSUE THREAD

**Issue by rcarberry72** [thesupersonic16/HedgeModManager#273]
I'm trying to launch sonic lost world from steam using Hedgemodmanager but game crashes upon startup when loading the cell shading mod, improvement mod, and Yoshi's Island Zone restoration. Is there a fix to this?

**Comment by Sajidur78** [comment]
Can you upload a snapshot? On the HedgeModManager window press Shift + F1.

**Comment by rcarberry72** [comment]
![Screenshot 2021-07-10 084525](https://user-images.githubusercontent.com/77164661/125163448-36a52c00-e15b-11eb-8af9-0611677577da.png)

Is this what you are talking about?

**Comment by thesupersonic16** [comment]
Sorry, in this case "snapshot" is a file that contains most of your configuration for HedgeModManager. I understand the confusion.

While on that window, hold your left shift key down then press F1 and then release your shift key. A window saying to attach a file should show up. Attach the file it says.

**Comment by rcarberry72** [comment]
[HMM_Snapshot_00072021102712.txt](https://github.com/thesupersonic16/HedgeModManager/files/6795432/HMM_Snapshot_00072021102712.txt)

This?

**Comment by Sajidur78** [comment]
@HighIntensity727 Could you check if there are any files starting with `slw.exe` in `%localappdata%\CrashDumps`. Also, at what point during startup does the game crash?

**Comment by rcarberry72** [comment]
Yes, there are quite a few slw.exe's in my crashdumps folder. The game would crash right after the Pegi 7 logo and sometimes during the SEGA logo

**Comment by Sajidur78** [comment]
Could you upload one of the files named slw.exe?

**Comment by rcarberry72** [comment]
I can't seem to upload it. The file ends in .dmp. The full name of the file is "slw.exe.3240.dmp"

**Comment by Sajidur78** [comment]
That's the file. Pack it into a zip and GitHub should let you upload it.

**Comment by rcarberry72** [comment]
[slw.exe.3240.dmp.zip](https://github.com/thesupersonic16/HedgeModManager/files/6795469/slw.exe.3240.dmp.zip)

**Comment by Sajidur78** [comment]
Looks like the source of the crash is Razer Cortex of all things. Can you disable that and see if the game functions fine?

**Comment by rcarberry72** [comment]
Sorry for the late response. My cell shading and Yoshi's island mods are working properly, the only mod that doesn't seem to work is my lost world improvement mod.

**Comment by Sajidur78** [comment]
If it's a mod compatibility issue then you will have to contact the mod author.

**Comment by marwansaad1272** [comment]
the game crashes for me even without mods I uninstalled 4 times 2 times the game and 2 times the mod loader

**Comment by thesupersonic16** [comment]
Don't think this issue is related to yours. Are you using the most up to date build from Steam?

**Comment by marwansaad1272** [comment]
I have installed the game from steam and not downloading it again

**Comment by thesupersonic16** [comment]
Does the game crash after removing d3d9.dll from the `Sonic Lost World` folder? If so, sounds like an issue unrelated to HMM.

**Comment by marwansaad1272** [comment]
d3d9 is just there so Am I supposed to delete it or what
