### ISSUE TITLE
How to choose custom mods directory?

### ISSUE THREAD

**Issue by EnderPreston** [thesupersonic16/HedgeModManager#28]
You may think I'm a noob, but i need an expert's assistance. I can't seem to click the checkbox that says "custom mods directory". I tried different options, but it just won't work. I had a folder that i want to use that has mods and everything, but i can't use it, because the darn checkbox won't work. Please help me out.

Update: someone had the same issue, and the creator said it wasn't implemented yet for Sonic Forces. Could someone ask him when it will happen?

**Comment by thesupersonic16** [comment]
Duplicate Issue #16
