### ISSUE TITLE
Sonic Generations crashes when I put the code to lock the game at 30 fps

### ISSUE THREAD

**Issue by SBETAXD** [thesupersonic16/HedgeModManager#281]
When I activate the code to be able to block the game at 30 fps when I start it, it closes immediately

I was expecting the game to run at 30fps but instead it quits

**Comment by thesupersonic16** [comment]
Does other codes work?

**Comment by SBETAXD** [comment]
Yes, except for the codes that lock the fps (sorry for answering so late and for my english)
