### ISSUE TITLE
[Forces] Stage 10 Crash Fix code request

### ISSUE THREAD

**Issue by KirbyJoe** [thesupersonic16/HedgeModManager#29]
In the updated Steam version of Sonic Forces, many players experiencing the game crash at nearby of the first tube in Stage 10 (Green Hill). Some players are passing the stage by modified save files. I don't want to modify the save file by the hacked ones because it's nearly dangerous. I want to make the players progress the game without hacking the save data to play the entire stage, and progress it. The code is the one of gameplay improvement codes like the ERZ Super Sonic Ability fix code seen in Mania Mod Loader (by @thesupersonic16 ). This is my request to help and support the Sonic Forces players getting stuck by latest update's unfixed crash glitch. Thank you.

**Comment by thesupersonic16** [comment]
I'm sorry, I was not able to reproduce the crash, Can you show where it crashes at?

**Comment by KirbyJoe** [comment]
It crashes at 50 seconds mark in SuperMoonKnight's gameplay of PS4 version that found on YouTube (https://www.youtube.com/watch?v=nKM2OqpjpbA&t=50s).

**Comment by slashiee** [comment]
My guess is that the trigger for putting CSonic into a rolling state is crashing the game. A level layout edit might be able to fix the issue, but who knows if it's possible to clear that part of the stage with the godawful physics that the game has.

**Comment by slashiee** [comment]
Rereading the main issue, I might try removing particles and sound triggers around that area.

**Comment by thesupersonic16** [comment]
This isn't something I can fix nor even reproduce, I will leave it to Slash.
