### ISSUE TITLE
Mods won't work in Puyo Puyo Tetris 2

### ISSUE THREAD

**Issue by solipsplosion** [thesupersonic16/HedgeModManager#295]
On June 30th there was a bug fix update for Puyo Puyo Tetris 2, after this update mods would no longer load when opening from the Mod Manager.

**Comment by RagdollClash** [comment]
Is the mod loader updated to the latest version?

**Comment by solipsplosion** [comment]
Yes it is.

**Comment by thesupersonic16** [comment]
What version of the mod loader are you using?

**Comment by Tetriser** [comment]
Had the same problem, I'm currently using the latest version of it

**Comment by RagdollClash** [comment]
@solipsplosion, @Tetriser:
Can you try using the [latest compile](https://nightly.link/thesupersonic16/HedgeModManager/workflows/build/rewrite/HedgeModManager-Release.zip) of HedgeModManager and reinstalling the mod loader? Just uninstall and install via the Settings tab. It should be on HE2ModLoader v1.0.2 after doing that.
