### ISSUE TITLE
[Bug] No Games - Exception 

### ISSUE THREAD

**Issue by dreamsyntax** [thesupersonic16/HedgeModManager#296]
## Describe the issue/bug
Open Steam with no supported games installed.
Start download for a supported game but do not let it finish.
Open HedgeModManager and wait a few moments. After the no game supported message, another window will appear and an exception will occur.

## Expected Behavior
No exception should occur.

## Additional Context
HMM Info:
```
    Version: 7.5-0
    Args: 
    StartDir: 
    Process Level: User
    Game: Unnamed Game
    SteamGame: 
```

Exception:
```
    Type: ArgumentNullException
    Message: Value cannot be null.
Parameter name: path1
    Source: mscorlib
    Function: System.String Combine(System.String, System.String)
    StackTrace: 
       at System.IO.Path.Combine(String path1, String path2)
       at HedgeModManager.MainWindow.RefreshProfiles() in C:\Users\SuperSonic16\source\repos\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 73
    InnerException: 
```

**Comment by RagdollClash** [comment]
Due to how Steam installs games, you have to wait for it to finish installing first before using HedgeModManager.
