### ISSUE TITLE
An error occured! See "HedgeModManager.log" for more info and report the file if possible

### ISSUE THREAD

**Issue by AnotherBlob** [thesupersonic16/HedgeModManager#30]
I uninstalled Sonic Forces and later reinstalled it (and never changed anything with the mod or HedgeMod folder besides starting it sometimes without the game) so when I started it again with the game, it says an error has occured but I don't see any errors in the log.

======== New Session ========

[2018.02.10 00:42:00]: Starting Hedge Mod Manager (v6.1-019)...
[2018.02.10 00:42:00]: Running Hedge Mod Manager in D:\Program Files (x86)\Steam\steamapps\common\SonicForces\HedgeModManager
[2018.02.10 00:42:00]: Writing cpkredir.ini
[2018.02.10 00:42:09]: Reading VDF: d:/program files (x86)/steam\steamapps\libraryfolders.vdf
[2018.02.10 00:42:27]: Creating Shortcut for Sonic Forces
[2018.02.10 00:42:27]:     Done.

[2018.02.10 00:42:29]: The form has been closed.

**Comment by AnotherBlob** [comment]
Never mind, seems like it's because I reinstalled Forces with the other folders being already in there.
I guess, I have to try it myself first.

**Comment by AnotherBlob** [comment]
Nope, didn't fix it...

**Comment by KTE2399** [comment]
Have you tried removing all files related to the mod loader then installing it back?

**Comment by AnotherBlob** [comment]
@KTE2399 This issue isn't fixed, why did you close it??

**Comment by AnotherBlob** [comment]
I've tried installing the game again, putting the old files back in, didn't work.
I've tried installing the game and starting it and THEN putting the old files back in, didn't work.
I haven't tried redoing the whole "installing the mod manager" process yet after installing and starting up the game though...

**Comment by AnotherBlob** [comment]
Okay, I finally got it to work by reinstalling Forces starting it, closing it, doing the whole installing process for HedgeMod manager and now it finally works. Took about 10 tedious hours of uninstalling and reinstalling but now it works.
