### ISSUE TITLE
No .exe file?

### ISSUE THREAD

**Issue by Dawsauce** [thesupersonic16/HedgeModManager#31]
I downloaded the latest version of the hedgemod manager from here but there's no .exe file included

**Comment by karitham** [comment]
What is .exe ?

**Comment by Sajidur78** [comment]
.exe is a common filename extension denoting an executable file (the main execution point of a computer program) for Microsoft Windows.

There are several file formats which may be used by a file with a .exe extension:

16-bit DOS MZ executable
The original DOS executable file format. These formats can be identified by the letters "MZ" at the beginning of the file in ASCII. All later formats have an MZ DOS stub header.[citation needed]

16-bit New Executable
Introduced with the multitasking MS-DOS 4.0 and also used by 16-bit OS/2 and Windows, NE can be identified by the "NE" in ASCII.

OS/2:
32-bit Linear Executable
Introduced with OS/2 2.0, these can be identified by the "LX" in ASCII. These can only be run by OS/2 2.0 and higher. They are also used by some DOS extenders.

Mixed 16/32-bit Linear Executable
Introduced with OS/2 2.0, these can be identified by the "LE" in ASCII. This format is used for VxD drivers under Windows 3.x, OS/2, and Windows 9x; it is also used by some DOS extenders.

Windows:
When a 16-bit or 32-bit Windows executable is run by Windows, execution starts at either the NE or the PE, and ignores the MZ code known as DOS stub. Started in DOS the stub typically displays a message "This program cannot be run in DOS mode" (or similar) before exiting cleanly, this thereby constituting a minimal form of fat binary. A few dual-mode programs (MZ-NE or MZ-PE) such as regedit and older WinZIP self extractors include a more functional DOS section.

32-bit Portable Executable
Introduced with Windows NT, these can be identified by the "PE" in ASCII (although not at the beginning; these files also begin with "MZ").
64-bit Portable Executable (PE32+)
Introduced by 64-bit versions of Windows, this is a PE file with wider fields. In most cases, code can be written to simply work as either a 32 or 64-bit PE file.
