### ISSUE TITLE
stops when i merely open it

### ISSUE THREAD

**Issue by ZippyZolton** [thesupersonic16/HedgeModManager#329]
HMM Info:
```
    Version: 7.2-5
    Args: 
    StartDir: E:\SteamLibrary\steamapps\common\Sonic Generations\
    Process Level: User
    Game: Unnamed Game
```

Exception:
```
    Type: NullReferenceException
    Message: Object reference not set to an instance of an object.
    Source: HedgeModManager
    Function: System.Collections.Generic.List`1[HedgeModManager.SteamGame] SearchForGames(System.String)
    StackTrace: 
       at HedgeModManager.Steam.SearchForGames(String preference)
       at HedgeModManager.HedgeApp.Main(String[] args)
    InnerException: 
```
[HMM_Snapshot_00102021015307.txt](https://github.com/thesupersonic16/HedgeModManager/files/7358957/HMM_Snapshot_00102021015307.txt)

**Comment by thesupersonic16** [comment]
Update HedgeModManager to 7.6

[Download](https://github.com/thesupersonic16/HedgeModManager/releases/download/7.6/HedgeModManager.exe)


As for why: Steam made an update for their file format a while back, and 7.2 (which is really old) did not support the new format.
