### ISSUE TITLE
[Gens] HedgeModManager claims that mods have been loaded, when the game runs at it's vanilla state

### ISSUE THREAD

**Issue by Ephemeralic** [thesupersonic16/HedgeModManager#33]
fresh installed a few times now, deleted my mods folder and re-added everything ran as admin, even reinstalled Generations, nothing will trigger HedgeModManager to load the game with the applied mods. cpkredir is installed.

**Comment by thesupersonic16** [comment]
Sorry for the late reply Github doesn't notify me.

Anyways, Did you make sure you installed CPKREDIR? When you open HMM this should show up 
![image](https://user-images.githubusercontent.com/25761885/47250234-fc0a7b00-d469-11e8-9d20-88d835fc9096.png)
If you do get this, Click Yes, if not then check Settings and make sure it says "Sonic Generations: Installed" Like as shown on this image
![image](https://user-images.githubusercontent.com/25761885/47250252-2e1bdd00-d46a-11e8-80a0-f7e591912968.png)
After that Make sure enable the mods you want and Press Save and Play.

**Comment by Ephemeralic** [comment]
Yep, this is the exact steps I take. Still does not run with mods.

**Comment by thesupersonic16** [comment]
Wow that was a quick reply, What mods are you enabling and Can you send me your cpkredir.ini(From the Sonic Generations Folder) and ModsDb.ini(From the mods folder) file?

**Comment by Sajidur78** [comment]
This issue is now irrelevant.
