### ISSUE TITLE
Sonic Lost World crashes upon launching

### ISSUE THREAD

**Issue by pastelaura** [thesupersonic16/HedgeModManager#333]
I have an issue when I start Sonic Lost World with Hedge Mod Manager- the game completely crashes when mods are either enabled or disabled completely. I have also tried deleting the codes to no avail. The game itself runs fine without Hedge Mod Manager installed. If someone could help me get Hedge Mod Manager running with my game, I'd really appreciate it.

I am using the legit version of the game on Steam.

**Comment by Sajidur78** [comment]
Could you get a snapshot? Press Shift+F1 when you're on the mods list.

**Comment by pastelaura** [comment]
[HMM_Snapshot_00102021001713.txt](https://github.com/thesupersonic16/HedgeModManager/files/7389316/HMM_Snapshot_00102021001713.txt)
Here you go.

**Comment by Sajidur78** [comment]
Can you check `%localappdata%\CrashDumps` for any files named slw.exe? And if there are any files upload one of them.

**Comment by pastelaura** [comment]
There are 2, but they were made on the 9th of this month when I didn't have Hedge Mod Manager installed.

**Comment by pastelaura** [comment]
Never mind I got it working.

**Comment by Sajidur78** [comment]
Could you explain what you did? it sounds like a very specific issue.

**Comment by pastelaura** [comment]
What ended up fixing it was restarting the PC. Restarting the PC never came to my mind before, so that was my bad.
