### ISSUE TITLE
No Matter What, Vanilla [Gens] Sonic loads

### ISSUE THREAD

**Issue by hyperhunt621** [thesupersonic16/HedgeModManager#34]
I've had this issue in both GMI and HedgeModManager for the past few days; 

Everytime I load up some mods, no matter what they are, character mods don't work. 
Stages do--I'm running the Unleashed Project with no issues, thankfully, but whenever I want to swap out Sonic for someone else (or even just his Black Knight appearance, for example) nothing changes; I'm left with the usual Gens model and Roger Craig Smith voice, no matter what.

**Comment by thesupersonic16** [comment]
Sorry to hear about this issue, And It doesn't seem to be an issue with the mod manager, But I would like to help fix the issue, But I need to know more info about the mods you have and
What version of CPKREDIR(cpkredir.dll) you have.
And if possible can you also send me your modsDB.ini file so I can see if HMM is writing the Paths correctly?

**Comment by hyperhunt621** [comment]
Sorry for the slow reply, but to answer your questions:

In terms of the mods I have altogether, there's a lot to say the least. I mean, to generalize it, I've got the usual stage mods--Unleashed Project, Unleashed's DLC stages, some Heroes stages, etc.--and a collection of character mods, like the aforementioned Black Knight Sonic, and then the usuals. Shadow, Tails, Knuckles, Super Mario Generations...Forgive me if that's not the best way of telling you what mods I have. XD

But as for CPKREDIR, I have the one that came with the latest release of HMM, so...0.5.0.8, according to Properties? And no, even with nothing else turned on, Black Knight Sonic doesn't load. Still just RCS Sonic.

Oh, and here's here's my modsDB.ini for you to check:
[ModsDB.zip](https://github.com/thesupersonic16/HedgeModManager/files/2520917/ModsDB.zip)

Thanks!!

**Comment by thesupersonic16** [comment]
Delete ModsDB.ini and the LEGO Sonic Level Pack Generations mod then Open HMM up again.

**Comment by thesupersonic16** [comment]
Your ModsDB.ini Looks good now, I'll have to fix the naming issue in HMM later.

From what I see, The Black Knight voices should work.

**Comment by hyperhunt621** [comment]
Maybe I'm doing something wrong then? Cause even after putting the mod (not just BK Sonic--I've tried Unleashed Sonic as well) at the very top of the list, I still get vanilla-Sonic. Do I need a fresh install, perhaps? 

Not sure if it'll help you, but here's what my Gens folder looks like at the moment: 
![capture](https://user-images.githubusercontent.com/33323167/47593601-dc7dc180-d945-11e8-9dc5-c269c2d80bc6.PNG)

**Comment by hyperhunt621** [comment]
I accidentally deleted HMM prior to that picture. Whoops. :P 

(I undid it)

**Comment by thesupersonic16** [comment]
btw In your setup Its Top To bottom.

**Comment by hyperhunt621** [comment]
Top to Bottom, yeah--doesn't that mean (seeing as the character mods are my highest priority) I should have them at the top in HMM?

**Comment by thesupersonic16** [comment]
No, Means Bottom has higher priority.

**Comment by thesupersonic16** [comment]
Sorry, I mean Bottom is last.

**Comment by hyperhunt621** [comment]
![mods](https://user-images.githubusercontent.com/33323167/47595173-db03c780-d94c-11e8-9b66-785bfc554730.PNG)

OK, so (with it still set to Top to Bottom) I have it set up like this...but I still get no results. 

(I'm sorry to be such a pain...)

**Comment by thesupersonic16** [comment]
Can you enable the CPKREDIR Console and show me the whole output?

**Comment by hyperhunt621** [comment]
I wasn't sure how to grab a screenshot of this considering how much there is, so forgive this wall of text: 

Successfully installed custom CriFsIo methods!
Successfully installed custom Sonic Generations savegame methods!
savegame redirection enabled!
Setting breakpad minidump AppID = 71340
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198212165971 [API loaded no]
OPEN:  "disk\bb3.cpk" o=FILE_MODE_OPEN a=FILE_ACCESS_READ
Analyzing CPK file "disk\bb3.cpk"
164 internal files, 4 external files
Handling file "disk\bb3.cpk"!
OPEN:  handle=$4C0, result=0
READ:  o=$00000000 c=$000800 buf=$042CB400 bfs=$000800 file=disk\bb3.cpk
Header read detected ...
CLOSE: "disk\bb3.cpk" result=0
OPEN:  "disk\bb3.cpk" o=FILE_MODE_OPEN a=FILE_ACCESS_READ
Still handling file "disk\bb3.cpk"!
OPEN:  handle=$470, result=0
READ:  o=$00000000 c=$000800 buf=$042D3540 bfs=$000800 file=disk\bb3.cpk
Header read detected ...
READ:  o=$04965E00 c=$001C40 buf=$042D3524 bfs=$001C40 file=disk\bb3.cpk
TOC read detected ...
READ:  o=$015443C0 c=$03B154 buf=$18930050 bfs=$03B800 file=disk\bb3.cpk
read of "shader_r_add.arl" detected, o=$0, -> "D:\SteamLibrary\steamapps\common\Sonic Generations\mods\UnleashedFxPipelineShaders\disk\bb3\shader_r_add.arl"
READ:  o=$00C4E900 c=$0032C2 buf=$05890620 bfs=$003800 file=disk\bb3.cpk
read of "shader_r.arl" detected, o=$0, -> "D:\SteamLibrary\steamapps\common\Sonic Generations\mods\UnleashedFxPipelineShaders\disk\bb3\shader_r.arl"
READ:  o=$00009900 c=$0001B8 buf=$1896B870 bfs=$000800 file=disk\bb3.cpk
read of "#Application.arl" detected, no external file, using CPK
READ:  o=$000B2D40 c=$0000F8 buf=$1896C2C0 bfs=$000800 file=disk\bb3.cpk
read of "Application.arl" detected, no external file, using CPK
READ:  o=$00000800 c=$0090DC buf=$18930050 bfs=$02B000 file=disk\bb3.cpk
read of "#Application.ar.00" detected, no external file, using CPK
READ:  o=$00019180 c=$099BC0 buf=$18D72030 bfs=$09A000 file=disk\bb3.cpk
read of "Application.ar.00" detected, no external file, using CPK
READ:  o=$00C170C0 c=$037840 buf=$1895B070 bfs=$038000 file=disk\bb3.cpk
read of "shader_r.ar.00" detected, o=$0, -> "D:\SteamLibrary\steamapps\common\Sonic Generations\mods\UnleashedFxPipelineShaders\disk\bb3\shader_r.ar.00"
READ:  o=$000B3980 c=$000031 buf=$05890600 bfs=$000800 file=disk\bb3.cpk
read of "AutoSave.arl" detected, no external file, using CPK
READ:  o=$004A01C0 c=$000021 buf=$05890E20 bfs=$000800 file=disk\bb3.cpk
read of "Languages\English\AutoSave.arl" detected, no external file, using CPK
READ:  o=$000B2E40 c=$000B20 buf=$058904B0 bfs=$003800 file=disk\bb3.cpk
read of "AutoSave.ar.00" detected, no external file, using CPK
READ:  o=$0049FCC0 c=$0004FC buf=$18930050 bfs=$001800 file=disk\bb3.cpk
read of "Languages\English\AutoSave.ar.00" detected, no external file, using CPK
READ:  o=$007FB100 c=$00001D buf=$058904B0 bfs=$000800 file=disk\bb3.cpk
read of "SegaLogo.arl" detected, no external file, using CPK
READ:  o=$006558C0 c=$1A5840 buf=$1A989030 bfs=$1A6000 file=disk\bb3.cpk
read of "SegaLogo.ar.00" detected, no external file, using CPK
READ:  o=$00C51C00 c=$400000 buf=$1AB44030 bfs=$7DE800 file=disk\bb3.cpk
read of "shader_r_add.ar.00" detected, o=$0, -> "D:\SteamLibrary\steamapps\common\Sonic Generations\mods\UnleashedFxPipelineShaders\disk\bb3\shader_r_add.ar.00"
READ:  o=$01051C00 c=$3DE168 buf=$1AF44030 bfs=$3DE800 file=disk\bb3.cpk
read of "shader_r_add.ar.00" detected, o=$400000, -> "D:\SteamLibrary\steamapps\common\Sonic Generations\mods\UnleashedFxPipelineShaders\disk\bb3\shader_r_add.ar.00"
READ:  o=$0000DA40 c=$00004A buf=$05890CB0 bfs=$000800 file=disk\bb3.cpk
read of "#Sonic.arl" detected, no external file, using CPK
OPEN:  "disk\bb.cpk" o=FILE_MODE_OPEN a=FILE_ACCESS_READ
Analyzing CPK file "disk\bb.cpk"
453 internal files, 58 external files
Handling file "disk\bb.cpk"!
OPEN:  handle=$B94, result=0
READ:  o=$00000000 c=$000800 buf=$1967C220 bfs=$000800 file=disk\bb.cpk
Header read detected ...
CLOSE: "disk\bb.cpk" result=0
OPEN:  "disk\bb.cpk" o=FILE_MODE_OPEN a=FILE_ACCESS_READ
Still handling file "disk\bb.cpk"!
OPEN:  handle=$B50, result=0
READ:  o=$00000000 c=$000800 buf=$197BA540 bfs=$000800 file=disk\bb.cpk
Header read detected ...
READ:  o=$924188C0 c=$004C80 buf=$197BA524 bfs=$004C80 file=disk\bb.cpk
TOC read detected ...
OPEN:  "disk\bb2.cpk" o=FILE_MODE_OPEN a=FILE_ACCESS_READ
Analyzing CPK file "disk\bb2.cpk"
1634 internal files, 72 external files
Handling file "disk\bb2.cpk"!
OPEN:  handle=$BD4, result=0
READ:  o=$00000000 c=$000800 buf=$1967C220 bfs=$000800 file=disk\bb2.cpk
Header read detected ...
CLOSE: "disk\bb2.cpk" result=0
OPEN:  "disk\bb2.cpk" o=FILE_MODE_OPEN a=FILE_ACCESS_READ
Still handling file "disk\bb2.cpk"!
OPEN:  handle=$BD0, result=0
READ:  o=$00000000 c=$000800 buf=$197BF8A0 bfs=$000800 file=disk\bb2.cpk
Header read detected ...
READ:  o=$A65DDC40 c=$0106E0 buf=$197BF894 bfs=$0106E0 file=disk\bb2.cpk
TOC read detected ...
READ:  o=$025B71C0 c=$001EF4 buf=$18930050 bfs=$008800 file=disk\bb3.cpk
read of "Sonic.arl" detected, no external file, using CPK
READ:  o=$1F480280 c=$0000B6 buf=$05891630 bfs=$000800 file=disk\bb2.cpk
read of "Loading.arl" detected, no external file, using CPK
READ:  o=$1EB696C0 c=$000020 buf=$05891E50 bfs=$000800 file=disk\bb2.cpk
read of "Languages\English\Loading.arl" detected, no external file, using CPK
READ:  o=$00009AC0 c=$003F70 buf=$18930050 bfs=$012000 file=disk\bb3.cpk
read of "#Sonic.ar.00" detected, no external file, using CPK
READ:  o=$017072C0 c=$400000 buf=$21E85030 bfs=$9FD800 file=disk\bb3.cpk
read of "Sonic.ar.00" detected, no external file, using CPK
READ:  o=$01B072C0 c=$400000 buf=$22285030 bfs=$5FD800 file=disk\bb3.cpk
read of "Sonic.ar.00" detected, no external file, using CPK
READ:  o=$01F072C0 c=$1FD600 buf=$22685030 bfs=$1FD800 file=disk\bb3.cpk
read of "Sonic.ar.00" detected, no external file, using CPK
READ:  o=$021048C0 c=$400000 buf=$22897030 bfs=$700800 file=disk\bb3.cpk
read of "Sonic.ar.01" detected, no external file, using CPK
READ:  o=$025048C0 c=$0B28D4 buf=$22C97030 bfs=$300800 file=disk\bb3.cpk
read of "Sonic.ar.01" detected, no external file, using CPK
READ:  o=$A144EC40 c=$00007F buf=$05890CB0 bfs=$000800 file=disk\bb2.cpk
read of "ResidentLoading.arl" detected, no external file, using CPK
READ:  o=$1EBD46C0 c=$000022 buf=$058915F0 bfs=$000800 file=disk\bb2.cpk
read of "Languages\English\ResidentLoading.arl" detected, no external file, using CPK
READ:  o=$1F45B440 c=$024E20 buf=$1A709030 bfs=$0DC000 file=disk\bb2.cpk
read of "Loading.ar.00" detected, no external file, using CPK
READ:  o=$1EB4D300 c=$01C384 buf=$22FA1030 bfs=$132800 file=disk\bb2.cpk
read of "Languages\English\Loading.ar.00" detected, no external file, using CPK
READ:  o=$A1416F00 c=$037D18 buf=$1A70C030 bfs=$112000 file=disk\bb2.cpk
read of "ResidentLoading.ar.00" detected, no external file, using CPK
READ:  o=$1EBD4080 c=$00060C buf=$05890CB0 bfs=$003000 file=disk\bb2.cpk
read of "Languages\English\ResidentLoading.ar.00" detected, no external file, using CPK
READ:  o=$04846BC0 c=$000020 buf=$05890CB0 bfs=$000800 file=disk\bb3.cpk
read of "voices\English\SonicVoice.arl" detected, no external file, using CPK
READ:  o=$04811940 c=$035270 buf=$18930050 bfs=$035800 file=disk\bb3.cpk
read of "voices\English\SonicVoice.ar.00" detected, no external file, using CPK
READ:  o=$00655800 c=$0000A9 buf=$05890CB0 bfs=$000800 file=disk\bb3.cpk
read of "NoticeBoard.arl" detected, no external file, using CPK
READ:  o=$004C47C0 c=$000068 buf=$058914D0 bfs=$000800 file=disk\bb3.cpk
read of "Languages\English\NoticeBoard.arl" detected, no external file, using CPK
READ:  o=$0063BF80 c=$019874 buf=$1A70B030 bfs=$0FF000 file=disk\bb3.cpk
read of "NoticeBoard.ar.00" detected, no external file, using CPK
READ:  o=$004A0200 c=$024594 buf=$1ABED030 bfs=$114000 file=disk\bb3.cpk
read of "Languages\English\NoticeBoard.ar.00" detected, no external file, using CPK
OPEN:  "Sound\SNG21_ETC.csb" o=FILE_MODE_OPEN a=FILE_ACCESS_READ
Not handling file "Sound\SNG21_ETC.csb", wrong file extension
OPEN:  handle=$B54, result=0
OPEN:  "Sound\SNG21_ETC.cpk" o=FILE_MODE_OPEN a=FILE_ACCESS_READ
Analyzing CPK file "Sound\SNG21_ETC.cpk"
no external files
Not handling file "Sound\SNG21_ETC.cpk"
OPEN:  handle=$B58, result=0
READ:  o=$00016680 c=$000059 buf=$05890CB0 bfs=$000800 file=disk\bb3.cpk
read of "#SonicClassic.arl" detected, no external file, using CPK
READ:  o=$036A85C0 c=$001314 buf=$18930050 bfs=$005000 file=disk\bb3.cpk
read of "SonicClassic.arl" detected, no external file, using CPK
READ:  o=$00012740 c=$003F20 buf=$18935070 bfs=$011000 file=disk\bb3.cpk
read of "#SonicClassic.ar.00" detected, no external file, using CPK
READ:  o=$02B74D80 c=$400000 buf=$2146A030 bfs=$A02000 file=disk\bb3.cpk
read of "SonicClassic.ar.00" detected, no external file, using CPK
READ:  o=$02F74D80 c=$400000 buf=$2186A030 bfs=$602000 file=disk\bb3.cpk
read of "SonicClassic.ar.00" detected, no external file, using CPK
READ:  o=$03374D80 c=$201F90 buf=$21C6A030 bfs=$202000 file=disk\bb3.cpk
read of "SonicClassic.ar.00" detected, no external file, using CPK
READ:  o=$03576D40 c=$131874 buf=$1A985030 bfs=$1EC000 file=disk\bb3.cpk
read of "SonicClassic.ar.01" detected, no external file, using CPK
READ:  o=$0063BF80 c=$019874 buf=$1A98C030 bfs=$0FF000 file=disk\bb3.cpk
read of "NoticeBoard.ar.00" detected, no external file, using CPK
READ:  o=$004A0200 c=$024594 buf=$1AA9B030 bfs=$114000 file=disk\bb3.cpk
read of "Languages\English\NoticeBoard.ar.00" detected, no external file, using CPK
OPEN:  "Sound\SNG21_ETC.csb" o=FILE_MODE_OPEN a=FILE_ACCESS_READ
Not handling file "Sound\SNG21_ETC.csb", wrong file extension
OPEN:  handle=$B5C, result=0
OPEN:  "Sound\SNG21_ETC.cpk" o=FILE_MODE_OPEN a=FILE_ACCESS_READ
Analyzing CPK file "Sound\SNG21_ETC.cpk"
no external files
Not handling file "Sound\SNG21_ETC.cpk"
OPEN:  handle=$B98, result=0
READ:  o=$01A99480 c=$0000BF buf=$05890CB0 bfs=$000800 file=disk\bb.cpk
read of "#SonicActionCommon.arl" detected, no external file, using CPK
READ:  o=$00004800 c=$0000EF buf=$058914D0 bfs=$000800 file=disk\bb.cpk
read of "#ActionCommon.arl" detected, no external file, using CPK
READ:  o=$02927A00 c=$0001C7 buf=$05890CB0 bfs=$000800 file=disk\bb.cpk
read of "#SystemCommon.arl" detected, o=$0, -> "D:\SteamLibrary\steamapps\common\Sonic Generations\mods\UNLSHDFLV2\disk\bb\#SystemCommon.arl"
READ:  o=$1EB40B80 c=$00001D buf=$058914D0 bfs=$000800 file=disk\bb2.cpk
read of "Languages\English\GameHint.arl" detected, no external file, using CPK
READ:  o=$8E6061C0 c=$000D58 buf=$18930050 bfs=$003000 file=disk\bb.cpk
read of "SonicActionCommon.arl" detected, no external file, using CPK
READ:  o=$8E6DA740 c=$0001B0 buf=$05890CB0 bfs=$000800 file=disk\bb.cpk
read of "SonicActionCommonHud.arl" detected, no external file, using CPK
READ:  o=$14B60B00 c=$00007D buf=$058914D0 bfs=$000800 file=disk\bb.cpk
read of "Languages\English\SonicActionCommonHud.arl" detected, no external file, using CPK
READ:  o=$02F72980 c=$000AE4 buf=$18930050 bfs=$002800 file=disk\bb.cpk
read of "ActionCommon.arl" detected, no external file, using CPK
READ:  o=$14B39380 c=$00002E buf=$05890CB0 bfs=$000800 file=disk\bb.cpk
read of "Languages\English\ActionCommon.arl" detected, no external file, using CPK
READ:  o=$0D21BDC0 c=$00002F buf=$058914D0 bfs=$000800 file=disk\bb2.cpk
read of "DecorationText.arl" detected, no external file, using CPK
READ:  o=$924185C0 c=$0002E8 buf=$05890CB0 bfs=$000800 file=disk\bb.cpk
read of "SystemCommon.arl" detected, no external file, using CPK
READ:  o=$14B77880 c=$00008E buf=$058914D0 bfs=$000800 file=disk\bb.cpk
read of "Languages\English\SystemCommon.arl" detected, no external file, using CPK
READ:  o=$0A87E640 c=$000058 buf=$05890CB0 bfs=$000800 file=disk\bb2.cpk
read of "ConverseCommon.arl" detected, no external file, using CPK
READ:  o=$01A948C0 c=$004BB8 buf=$18930050 bfs=$00F000 file=disk\bb.cpk
read of "#SonicActionCommon.ar.00" detected, no external file, using CPK
READ:  o=$00000800 c=$003FC4 buf=$1893F070 bfs=$00A800 file=disk\bb.cpk
read of "#ActionCommon.ar.00" detected, no external file, using CPK
READ:  o=$0289E700 c=$0892EA buf=$1A8D8030 bfs=$089800 file=disk\bb.cpk
read of "#SystemCommon.ar.00" detected, o=$0, -> "D:\SteamLibrary\steamapps\common\Sonic Generations\mods\UNLSHDFLV2\disk\bb\#SystemCommon.ar.00"
READ:  o=$1EB3B740 c=$005424 buf=$18930050 bfs=$01A000 file=disk\bb2.cpk
read of "Languages\English\GameHint.ar.00" detected, no external file, using CPK
READ:  o=$8E1F82C0 c=$400000 buf=$21467030 bfs=$962800 file=disk\bb.cpk
read of "SonicActionCommon.ar.00" detected, no external file, using CPK
READ:  o=$8E5F82C0 c=$00DEC8 buf=$21867030 bfs=$562800 file=disk\bb.cpk
read of "SonicActionCommon.ar.00" detected, no external file, using CPK
READ:  o=$8E606F40 c=$0D37F8 buf=$1A985030 bfs=$369000 file=disk\bb.cpk
read of "SonicActionCommonHud.ar.00" detected, no external file, using CPK
READ:  o=$14B44880 c=$01C248 buf=$1ACF4030 bfs=$0AF000 file=disk\bb.cpk
read of "Languages\English\SonicActionCommonHud.ar.00" detected, no external file, using CPK
READ:  o=$02927C00 c=$400000 buf=$248B9030 bfs=$64B000 file=disk\bb.cpk
read of "ActionCommon.ar.00" detected, no external file, using CPK
READ:  o=$02D27C00 c=$24AD78 buf=$24CB9030 bfs=$24B000 file=disk\bb.cpk
read of "ActionCommon.ar.00" detected, no external file, using CPK
READ:  o=$14B36280 c=$0030D8 buf=$18930050 bfs=$00F000 file=disk\bb.cpk
read of "Languages\English\ActionCommon.ar.00" detected, no external file, using CPK
READ:  o=$0D1ED6C0 c=$02E6CC buf=$1ADB5030 bfs=$0F2000 file=disk\bb2.cpk
read of "DecorationText.ar.00" detected, no external file, using CPK
READ:  o=$923E1D00 c=$036890 buf=$1AEB5030 bfs=$128800 file=disk\bb.cpk
read of "SystemCommon.ar.00" detected, no external file, using CPK
READ:  o=$14B60B80 c=$016CC8 buf=$1A8D9030 bfs=$08B800 file=disk\bb.cpk
read of "Languages\English\SystemCommon.ar.00" detected, no external file, using CPK
READ:  o=$0A856100 c=$028538 buf=$1B329030 bfs=$0D4000 file=disk\bb2.cpk
read of "ConverseCommon.ar.00" detected, no external file, using CPK
READ:  o=$02952880 c=$000020 buf=$05891B50 bfs=$000800 file=disk\bb2.cpk
read of "#Title.arl" detected, o=$0, -> "D:\SteamLibrary\steamapps\common\Sonic Generations\mods\UNLSHDFLV2\disk\bb2\#Title.arl"
READ:  o=$A48C2340 c=$0004A4 buf=$05892370 bfs=$001000 file=disk\bb2.cpk
read of "Title.arl" detected, no external file, using CPK
READ:  o=$1EC643C0 c=$0000B0 buf=$05891B50 bfs=$000800 file=disk\bb2.cpk
read of "Languages\English\Title.arl" detected, no external file, using CPK
READ:  o=$0294EC80 c=$003BF9 buf=$18930050 bfs=$004000 file=disk\bb2.cpk
read of "#Title.ar.00" detected, o=$0, -> "D:\SteamLibrary\steamapps\common\Sonic Generations\mods\UNLSHDFLV2\disk\bb2\#Title.ar.00"
READ:  o=$A43FC200 c=$3FB13C buf=$27E80030 bfs=$907000 file=disk\bb2.cpk
read of "Title.ar.00" detected, no external file, using CPK
READ:  o=$A47F7340 c=$0CB000 buf=$21560030 bfs=$731800 file=disk\bb2.cpk
read of "Title.ar.01" detected, no external file, using CPK
READ:  o=$1EC2F600 c=$034D94 buf=$1A980030 bfs=$128800 file=disk\bb2.cpk
read of "Languages\English\Title.ar.00" detected, no external file, using CPK
READ:  o=$A48F5280 c=$0000C7 buf=$05891B50 bfs=$000800 file=disk\bb2.cpk
read of "TitleToPAM.arl" detected, no external file, using CPK
OPEN:  "Sound\SNG00_SYS.csb" o=FILE_MODE_OPEN a=FILE_ACCESS_READ
Not handling file "Sound\SNG00_SYS.csb", wrong file extension
OPEN:  handle=$B98, result=0
OPEN:  "Sound\SNG00_SYS.cpk" o=FILE_MODE_OPEN a=FILE_ACCESS_READ
Analyzing CPK file "Sound\SNG00_SYS.cpk"
no external files
Not handling file "Sound\SNG00_SYS.cpk"
OPEN:  handle=$BAC, result=0
READ:  o=$A48C2800 c=$032A80 buf=$2156B030 bfs=$709800 file=disk\bb2.cpk
read of "TitleToPAM.ar.00" detected, no external file, using CPK

**Comment by thesupersonic16** [comment]
Seems to only be loading UNLSHDFLV2 and UnleashedFxPipelineShaders.

Have to tried going to the world map?

**Comment by hyperhunt621** [comment]
World Map? You mean the hub world? If so, then yeah. 

Right now all I'm trying to load is Black Knight Sonic in the original game, no unique stages or anything.

**Comment by thesupersonic16** [comment]
I'm lost now lol

**Comment by hyperhunt621** [comment]
Oof...

I hope we didn't misunderstand each other from the offset; I'm using HMM for Generations. No matter what character mods I load for the game, they never load; all I get is normal, Generations Sonic. Stages work, and the Unleashed Shaders work, but character mods never do. 

Whether I was using Sonic GMI or HMM, the issue is the same across both.

**Comment by thesupersonic16** [comment]
I think its best to start a new Mods folder, and just copy over the mods you want to play into the new mods, As I think its a mod you have thats causing the issue.
And use https://ci.appveyor.com/api/buildjobs/m74vaurmqi11oe0x/artifacts/HedgeModManager%2Fbin%2FHedgeModManager%206.1-020_r187%20%5BRelease%5D.zip As it has the fixed mod activator.

**Comment by hyperhunt621** [comment]
I'll give it a shot and let you know how things go. 

Thanks so much for your help! :D

**Comment by hyperhunt621** [comment]
OK, we're golden! 

But, actually, what you suggested above actually didn't work, exactly. 
Originally, I did the new mods folder and the new HMM install, but that didn't work. So I decided to see if SonicGMI would work at the very least with the new mod folder, and it turned out that by replacing the CPKREDIR files I had from HMM with the ones from GMI's install actually made things work. 

I even tried things out in HMM without changing anything having to do with the CPKREDIR files, and voila, Black Knight Sonic appeared like nothing was ever wrong! 

So I'm not sure what the mistake was on my end, but regardless, I can't thank you enough for trying to help me out!

**Comment by thesupersonic16** [comment]
I have downloaded the mod and took a look and found that the mod.ini file is written incorrectly for CPKREDIR, This issue is not related to HMM, HMM uses the newest version of CPKREDIR which has some nice fixes in it, But requires mods to use the proper INI syntax. UltimateDarkman forgot to put the Quotation mark at the end of the Include Path which is what thrown CPKREDIR off. I'll be closing this Issue now.
