### ISSUE TITLE
Same issue

### ISSUE THREAD

**Issue by OctoTheBitch** [thesupersonic16/HedgeModManager#343]
Heya, while I am extremely thankful for your efforts, it seems that the same errors as mentioned before continue to happen, certain mods crashing on startup, namely D3D9EX, and a few others.

**Comment by thesupersonic16** [comment]
I would suggest naming this issue and keeping each issue on topic. The issue I closed before was for the double click.

I have taken a look at the snapshot you sent in #321 and it is showing it is not installed in a Steam library and the hash of the game does not match what it should be. Either this is a pirated copy or you have modified the executable. Best I can suggest is to install a clean copy of Sonic Generations from Steam and try installing the mods again.
