### ISSUE TITLE
[Forces] The game won't start when I have mods installed anymore 

### ISSUE THREAD

**Issue by PhilipS02** [thesupersonic16/HedgeModManager#35]
Alright so I tried to play Forces with some mods again but the game just won't start for me...
 I can still play it perfectly fine without any mods installed but whenever I have mods installed the game just won't start even after reinstalling the whole game and restarting my whole computer.
what's odd is that I could still play forces with mods without any issues a day before....
maybe I deleted an important file somewhere but I could really need some help now

**Comment by thesupersonic16** [comment]
Did you recently install the new physics mod?

**Comment by PhilipS02** [comment]
> 
> 
> Did you recently install the new physics mod?

Actually I did!

**Comment by thesupersonic16** [comment]
Around 3 days ago, I found a bug in HMM and FML, which is causing them to fail, I have not yet fixed it, But I do have plans to fix, I had alot of people reporting this issue, For the time being, Please delete your ModsDB.ini file and delete the `CFR's REVISED Modern Sonic Physics Tweaks` mod.

**Comment by Jambopaul** [comment]
I just started having the same issue. On January 29th 2019, Sonic Forces updated automatically for me on Steam (I don't know if it was an actual update or perhaps a glitch on Steam since I couldn't seem to find any records of an update online or on Steam's Database) and now I can't play the game with any mods installed, the game just refuses to boot up. I have been playing the game with mods for the past few weeks (including physics mods) and it has worked fine until now. Does the Mod Loader need to be updated?

**Comment by thesupersonic16** [comment]
Can you please send your ModsDB.ini andCPKREDIR.ini file and the version of HMM and ForcesModLoader you are using?
Also There hasn't been a Forces Update in over a year.

**Comment by Jambopaul** [comment]
It won't let me send the files through GitHub. Should I send them through Twitter DM's or something else? Also it should be noted that now the game doesn't even start booting up and giving me the "Mods Loading in Reverse" message anymore, the game executable just closes immediately.

**Comment by Jambopaul** [comment]
The Hedge Mod Manager is version 6.1-020. I tried reinstalling HMM and when that didn't work, I tried re-installing the game all together.

**Comment by Jambopaul** [comment]
I've tried rebooting. It didn't work. Also your Twitter DM's are deactivated at the moment.

**Comment by thesupersonic16** [comment]
Released 6.1-021 which should have solved the main issue. Reopen if the issue persist on the newest release, Closing.
