### ISSUE TITLE
I just updated the mod manager and whenever i pressed continue game on Sonic generations it crashed. [Sonic generations] 

### ISSUE THREAD

**Issue by Gmodfan750** [thesupersonic16/HedgeModManager#352]
[HMM_Snapshot_00122021164731.txt](https://github.com/thesupersonic16/HedgeModManager/files/7705498/HMM_Snapshot_00122021164731.txt)

**Comment by thesupersonic16** [comment]
Can you please go to `%localappdata%\CrashDumps` and zip up the newest crash dump that starts with `SonicGenerations` and send it here? That file will contain information about the crash.

I also noticed from the snapshot file you included you have a bunch of mods active, I recommend disabling some mods and try narrow down the cause of the crash if it is related to mod conflicts.

**Comment by Loganm2007** [comment]
[Uploading SonicGenerations.exe.12740.txt…]()
i had to change the file type to .txt to send it.

**Comment by Gmodfan750** [comment]
> here.

https://drive.google.com/file/d/1w-9Wrn8PMQNPbzK-2vPvb_1Ybjij7u3j/view?usp=sharing

**Comment by Gmodfan750** [comment]
Thanks, it was one of my mods
