### ISSUE TITLE
[Unnamed Game] 

### ISSUE THREAD

**Issue by SillyJen** [thesupersonic16/HedgeModManager#355]
This has happened to me constantly over the span of a few months. I tried a couple months ago, didnt do anything. I tried again now, and still, i have the same issue.

[HMM_Snapshot_00122021195448.txt](https://github.com/thesupersonic16/HedgeModManager/files/7731278/HMM_Snapshot_00122021195448.txt)

HMM Info:
```
    Version: 7.6-1
    Args: 
    StartDir: C:\Users\gmf36\Desktop\
    Process Level: User
    Game: Unnamed Game
    Update Status: Up To Date
```

Exception:
```
    Type: ArgumentException
    Message: Illegal characters in path.
    Source: mscorlib
    Function: Void CheckInvalidPathChars(System.String, Boolean)
    StackTrace: 
       at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
       at System.IO.Path.Combine(String path1, String path2)
       at HedgeModManager.Steam.SearchForGames() in C:\Users\SuperSonic16\source\repos\HedgeModManager\HedgeModManager\Steam.cs:line 43
       at HedgeModManager.GameInstall.SearchForGames(String preference) in C:\Users\SuperSonic16\source\repos\HedgeModManager\HedgeModManager\Game.cs:line 176
       at HedgeModManager.HedgeApp.Main(String[] args) in C:\Users\SuperSonic16\source\repos\HedgeModManager\HedgeModManager\HedgeApp.xaml.cs:line 171
    InnerException: 
```

**Comment by thesupersonic16** [comment]
The snapshot file you sent shows that you have had HMM running before in a Steam library, but the exception information seems to show it failing. Did you move any Steam related files around when you first got this issue?

**Comment by SillyJen** [comment]
No, i removed it from the library after it failed to run. A while after that, i had to uninstall steam on my pc to fix some corrupted files.

**Comment by thesupersonic16** [comment]
Do you have Steam currently installed?

**Comment by SillyJen** [comment]
Yes I do. HedgeModManager is not on steam at the moment.

**Comment by thesupersonic16** [comment]
Does the file `libraryfolders.vdf` exist in `C:\Program Files (x86)\Steam\steamapps`?

**Comment by SillyJen** [comment]
Yes, it does.

**Comment by thesupersonic16** [comment]
Maybe there is an issue with your computer's registry. If your comfortable, can you open the Registry Editor and navigate to `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Valve\Steam` and check if `InstallPath` matches with this?

![image](https://user-images.githubusercontent.com/25761885/146485334-58d33c20-05f3-4cd9-9d2c-4363929de85c.png)

**Comment by SillyJen** [comment]
Do you mind if I check this out later on tomorrow? It’s getting pretty late
for me and I need to get up early for my classes in the morning. I hope you
don’t mind if I check it tomorrow-

**Comment by SillyJen** [comment]
Alrighty, I checked and it’s under the same install the path.

**Comment by thesupersonic16** [comment]
Can you please send an image of it showing the path?

**Comment by SillyJen** [comment]
I actually went further into the editor and found out that in one of my
steam registeries, it was incorrect. I fixed it, and the manager began
working again :)

Thank you so much for your help on this. I really appreciate it!

**Comment by thesupersonic16** [comment]
Mind telling me what it was before? I may need to have HMM handle the issue incase someone else has it.
