### ISSUE TITLE
[Sonic Colors Ultimate Update] 

### ISSUE THREAD

**Issue by topkeksphagetti** [thesupersonic16/HedgeModManager#357]
Newest update seems to have broken support for the Rainbow Mod loader
![image](https://user-images.githubusercontent.com/15426253/146649681-4e8cb701-dc38-4ee0-bcbe-ae20b5226294.png)
This renders mods such as gameplay tweaks unusable

**Comment by YousifAlkhalaf** [comment]
I also have the same issue. It seems like an issue with the mod loader & not HMM because Sonic Generations works just fine with mods

**Comment by Sajidur78** [comment]
The error is related to Rainbow Mod Loader. An update for it will be released when the author(@blueskythlikesclouds) can find time to add support for the current version.
