### ISSUE TITLE
[SonicGenerations] Workaround for The detected configuration does not match your current hardware

### ISSUE THREAD

**Issue by eadmaster** [thesupersonic16/HedgeModManager#362]
## Describe the issue/bug

When starting the game it shows this error "The detected configuration does not match your current hardware".

(the game was restored from a manual backup and not installed normally)

## Expected Behaviour

the game should start

## Additional Context

tried with the [workarounds suggested here](https://steamcommunity.com/app/71340/discussions/0/846938351034781131/).

Running  HedgeModManager v7.6-1.

**Comment by Sajidur78** [comment]
This isn't really a HMM issue but, [Skyth's Direct3D9Ex](https://gamebanana.com/mods/50770) mod has a workaround for config mismatch. You can also try messing around with the configuration tool or [PTKickass' Configuration Tool Rewrite](https://github.com/ptkickass/GenerationsConfigTool_Rewrite) until it works.
