### ISSUE TITLE
[Sonic Forces]

### ISSUE THREAD

**Issue by Shadow-87** [thesupersonic16/HedgeModManager#367]
Hello.
I wanted to install some mods on Sonic Forces (Fitgirl Repack) but it doesn't install any mods.
I can see and select mods in mods menu, but they won't work in game.
Is it because of Fitgirl or anything else?
Thanks

**Comment by thesupersonic16** [comment]
I am sorry, but we do not support pirated copies of Sonic Forces. I am not sure why cracked copies are not working, likely their cracks are not calling `SteamAPI_RestartAppIfNecessary` from the Steam API.
