### ISSUE TITLE
Add 90fps cap to Sonic Generations community codes?

### ISSUE THREAD

**Issue by Kilrua** [thesupersonic16/HedgeModManager#374]
## Describe the issue

I was wondering if there is way to set Sonic Generations to run at 90fps. 

## Additional Context

Just looking for a middle ground between 72 and 120 fps. 
I would hex edit the exe to make it run at 90fps but I'm not sure what the hex value for 90 would be.

**Comment by thesupersonic16** [comment]
A better solution over editing the exe is to copy one of the codes and change the old framerate to 90.

**Comment by Kilrua** [comment]
> A better solution over editing the exe is to copy one of the codes and change the old framerate to 90.

Honestly I'm unsure of how all this works. How do I copy the code?

**Comment by thesupersonic16** [comment]
Create a file in your mods folder called `ExtraCodes.hmm` and copy the code `Locked 72 FPS (experimental)` into the new file and change all `72` to `90`. That should work, never tried it.
