### ISSUE TITLE
"Update Community Codes" appears to not be able to be translated

### ISSUE THREAD

**Issue by NextinMono** [thesupersonic16/HedgeModManager#383]
I don't think I did something wrong myself, but it appears that in the latest version, in the Codes tab, "Update Community Codes" can't be translated, despite having an entry in the localization file
![image](https://user-images.githubusercontent.com/38560522/160234842-f9278af0-1507-4521-a8a5-f8351472a95c.png)

**Comment by thesupersonic16** [comment]
The button can be translated. It just doesn't update when you change languages live.

**Comment by NextinMono** [comment]
So essentially it only updates when you restart the program?

**Comment by thesupersonic16** [comment]
Yes. I will have to look into that at another date.

**Comment by thesupersonic16** [comment]
Issue should be fixed in 2b810e48be246afae8f5b6e407551be6e96992b8.

**Comment by NextinMono** [comment]
Yup, it is
