### ISSUE TITLE
Problems with UltimateDarkman's STH06 Sonic Mod

### ISSUE THREAD

**Issue by toeifan1998** [thesupersonic16/HedgeModManager#39]
Dear SuperSonic16,

I type this letter requesting help please. I've been trying very hard to figure out what's wrong with UltimateDarkman's STH06 Sonic Mod in this link here: https://www.youtube.com/watch?v=L3rXDtzEUy4

I think there's something going on with the files because for some reason I can only run the mod if I use the SG Version (Generations Model with the 06 animations). I've been trying to run the regular one so I can play the game with the 06 Sonic model and it's animations, but whenever I do I get a black screen after the HAVOK Logo before the Title Screen comes up and I'm forced to restart my PC.

Can you please help me?

**Comment by thesupersonic16** [comment]
Not an issue with HedgeModManager, You will need to take this up with the mod author. Closing.
