### ISSUE TITLE
[Bug] [Sonic Generations] "Fix Boost Gauge Particles" Code crashes the game when Boosting/Spin Dashing in Casino Night Zone

### ISSUE THREAD

**Issue by Mystyle-48** [thesupersonic16/HedgeModManager#393]
## Describe the issue/bug
When the "Fix Boost Gauge Particles" code is enabled, using the Boost/Spin Dash move during the Casino Night Zone pinball stage will crash the game every time.

**Comment by Mystyle-48** [comment]
Commenting to prevent the issue from going stale; it still occurs.

**Comment by DeaTh-G** [comment]
Codes for HedgeModManager now have a new home at: https://github.com/hedge-dev/HMMCodes. If the issue/suggestion is still relevant please open an issue on that repository as code related issues are no longer being tracked on the main HedgeModManager repository.

Thank you, and sorry for the inconvenience.
