### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by InboundsBead590** [thesupersonic16/HedgeModManager#403]
## Describe the issue/bug
I was going to add the Double Jump mod for Sonic Generations to HedgeModManager, but it gave me an error which said "Hedge Mod Manager has ran into an error

## Expected Behaviour
I was expecting Hedge Mod Manager to add the mod

**Comment by Sajidur78** [comment]
What was the error?

**Comment by InboundsBead590** [comment]
[HMM_Snapshot_00042022130556.txt](https://github.com/thesupersonic16/HedgeModManager/files/8581787/HMM_Snapshot_00042022130556.txt)
This was the error
