### ISSUE TITLE
[Bug] SLW won't boot if I have any mods enabled

### ISSUE THREAD

**Issue by Redyn** [thesupersonic16/HedgeModManager#406]
I'm using the latest version of HMM. If I have even one mod enabled the game won't boot.

I tried QuickBoot, DLC Restoration and Gamma Correction.

If I disable all 3 I can run the game.

Don't know if this is related, but the Codes also seem to have issues for me. Don't Lose Rings doesn't work. The codes for forcing languages make the game crash on boot. Didn't try the others.

**Comment by DeaTh-G** [comment]
DLC Restoration uses code injection which most Lost World mods don't (at the point of writing this comment).
If your EXE file doesn't match the latest Steam release EXE it will very likely crash or at best not function correctly.

If the issue still persists then try verifying game files through Steam.

**Comment by Redyn** [comment]
What about the other mods? Because each of them prevent the game from loading even if enabled individually.

**Comment by DeaTh-G** [comment]
Gamma Correction, QuickBoot and HMM Codes also modify game code thus they also won't work unless the game's EXE matches the latest steam release's EXE.
