### ISSUE TITLE
UltimateDarkman's STH06 Sonic v.2.0

### ISSUE THREAD

**Issue by toeifan1998** [thesupersonic16/HedgeModManager#41]
supersonic16,

I'm back with you again to ask for your help. UltimateDarkman refuses to answer the problems related to STH06 Sonic v.2.0

I'm hoping you could please help by downloading the mod yourself and see if you can figure out why 06 Style Sonic doesn't work yet the 06 Style Sonic using Generations Sonic Model works.

I've tried for weeks now to figure out what the heck is wrong with it and I'm at my wit's end.

So please check it out or try getting in contact with UltimateDarkman or something because I'm just frustrated to hell that I can't figure out what's wrong with it.

Link - https://www.youtube.com/watch?v=L3rXDtzEUy4

I'm no good and reading code so that's why I'm asking again for your help. Please don't turn me down again and just give me an answer as to why it keeps giving me a black screen right after the HAVOK logo before the title screen ;~;

**Comment by thesupersonic16** [comment]
Duplicate #39 Closing

Also I have tried the mod and it is broken on my end, And like what I said in the other Issue, Please take it to the mod author, I don't write mods.
