### ISSUE TITLE
[SonicGenerations] Game won't load

### ISSUE THREAD

**Issue by SilversJunkpile** [thesupersonic16/HedgeModManager#410]
The game will just say the cloud is at 100 percent and then stop running it. I only have 2 mods on, and they  are just model swaps of legacy sonic and sonic 2 sonic in 3d. I'm very confused and this is my first time using this manager. Help?

**Comment by SilversJunkpile** [comment]
It says on the mod loader it started and then just crashes

**Comment by thesupersonic16** [comment]
Does any error message show up and did you make sure you have an up to date version of HedgeModManager?

**Comment by SilversJunkpile** [comment]
nope

**Comment by SilversJunkpile** [comment]
it says no updates found
odd

**Comment by SilversJunkpile** [comment]
very odd
