### ISSUE TITLE
[Gens] Code Loader Error

### ISSUE THREAD

**Issue by AllThingsGaming6** [thesupersonic16/HedgeModManager#43]
![Image of Error](https://i.imgur.com/1lc4fXB.png)
[https://i.imgur.com/1lc4fXB.png](url)

I have no idea what's wrong. I'm pretty sure I'm using the latest version (with the Casino Nights DLC), but I get this error. I'm also not sure where exactly I'm supposed to "check for an updated version", as when I open HedgeModManager, I don't see an option for it.

**Comment by thesupersonic16** [comment]
This feature has been broken for many people for whatever reason. I currently don't know the cause as it works for some people, but not for others even with the same version. for the time being just uninstall the codeloader, Maybe sometime in the future I might try redo the patcher to be more tolerable and to not break the config tool.

**Comment by thesupersonic16** [comment]
The code loader for Sonic Generations has been replaced. This issue is now irrelevant, reopen if the issue still occurs.
