### ISSUE TITLE
I can't see Sonic Origins in the mod loader

### ISSUE THREAD

**Issue by qtpurx** [thesupersonic16/HedgeModManager#434]
So I downloaded the loader and when I open it up, it shows that no games are detected. I tried to play the game and open up the loader and that didn't work. I tried to put the loader in the sonic origins folder and that also didn't work. I have also tried to switch the update channel to developmental and it also did not work. Something to note is that I have installed Sonic Origins from the Epic Games Store. 
![Screenshot 2022-06-24 203937](https://user-images.githubusercontent.com/92770135/175756837-540cfa02-9028-4fa0-baf5-db3a85b8e226.png)

**Comment by thesupersonic16** [comment]
Thanks for reporting the issue. Can you please send `LauncherInstalled.dat` from `C:\ProgramData\Epic\UnrealEngineLauncher` (Default location) and tell me what DLCs you own with the game?

**Comment by qtpurx** [comment]
I can't send the file because it's telling me that "We don't support that file type".

**Comment by thesupersonic16** [comment]
Can you put it in a zip file and send it here?

**Comment by qtpurx** [comment]
[LauncherInstalled.zip](https://github.com/thesupersonic16/HedgeModManager/files/8983836/LauncherInstalled.zip)
Ok now it works! The DLC's I own are "Sonic Origins: Classic Music Pack" and "Sonic Origins: Premium Fun Pack".

**Comment by qtpurx** [comment]
I also have the "Sonic Origins: Start Dash Pack" as well.

**Comment by thesupersonic16** [comment]
Does `SonicOrigins.exe` exist in `E:\\Program Files\\Epic Games\\SonicOrigins\\build\\main\\projects\\exec`?

**Comment by qtpurx** [comment]
Yes it does.
![Screenshot 2022-06-24 212056](https://user-images.githubusercontent.com/92770135/175757801-02c10601-f884-4f29-8867-3295415ace25.png)

**Comment by thesupersonic16** [comment]
Are you familiar with using `regedit`? We may need to see if the registry is correct.

After opening Registry Editor on the top enter `Computer\HKEY_CURRENT_USER\Software\Epic Games\EOS` and you should see a  `ModSdkMetadataDir`, can you show me what the value of this is?

**Comment by qtpurx** [comment]
C:/ProgramData/Epic/EpicGamesLauncher/Data/Manifests
![Screenshot 2022-06-24 212716](https://user-images.githubusercontent.com/92770135/175757951-9dd36270-48f2-4121-91c1-6c0e4090e4da.png)

**Comment by thesupersonic16** [comment]
I think I have an idea what went wrong. Can you try this? Make sure to place it away from your game folder like your desktop.
[HedgeModManager.zip](https://github.com/thesupersonic16/HedgeModManager/files/8984072/HedgeModManager.zip)

**Comment by qtpurx** [comment]
It looks like it's working!
![Screenshot 2022-06-25 000643](https://user-images.githubusercontent.com/92770135/175762715-77eee9c3-1b0a-498e-82b3-b72241ed928c.png)

**Comment by thesupersonic16** [comment]
Fixed in 45098b5ad5fa5b16c8df750bc24292c3cb8ccf46. You may continue using that build. All future builds will also include the fix.

**Comment by qtpurx** [comment]
Ok, thank you so much!
