### ISSUE TITLE
ERROR, Hedgemodmanager could not access the game directory

### ISSUE THREAD

**Issue by OrbyyOrbinaut** [thesupersonic16/HedgeModManager#442]
Consistently getting an error about how hmm can't access the game directory and it telling me to make sure the users group has write access to allow on the directory despite that already being the case

**Comment by thesupersonic16** [comment]
Did you install the game untouched using Steam or Epic Games?

**Comment by OrbyyOrbinaut** [comment]
uhhh i've used hmm on my copy of gens before i switched computers awhile ago, should i reinstalling the game and see if that fixes it?

**Comment by thesupersonic16** [comment]
Sounds like your permissions got screwed up when moving between PCs and not an issue with HedgeModManager. The safest method is to backup the game, delete the Sonic Generations folder and redownload it from Steam and reinstall all your mods online.
