### ISSUE TITLE
[Sonic Origins/Linux] Game not launching after HedgeMod Manager is installed (Wine)

### ISSUE THREAD

**Issue by confiscatedharddrive** [thesupersonic16/HedgeModManager#445]
## Describe the issue/bug
I've tried installing it through the recommended methods in the wiki but neither Bottles nor Proton worked; couldn't launch. I can get it to run using just regular Wine, however. Thing is, after I install and hit Save on the mod manager, I can no longer launch the game. If I try through Steam, it will just refuse to launch outright (tested both under Proton Experimental and 7.0-3). When I launch through the HedgeMod Manager or by double clicking the SonicOrigins.exe I get the error:
`Unable to initialize SteamAPI. Please make sure Steam is running and you are logged in to an account entitled to the game.`
I've tried the different .dll files [from this issue here](https://github.com/thesupersonic16/HedgeModManager/issues/435) but didn't seem to help.

## Expected Behaviour
Expected behaviour would be being able to launch the game.

## Additional Context
I have no codes selected and my options are as follows:
`Mods directory: Z:\home\user\.steam\steam\steamapps\common\SonicOrigins\build\main\projects\exec\mods`

Checked boxes:
`Enable mod loader; Enable save file retention; Check for mod loader updates; Check for code loader updates; Check for mod updates; Keep Hedge Mod Manager open after starting a game`

For reference here are my specs that could be relevant:
Wine version: wine-7.10 (Staging)
OS: Fedora 36
Linux Kernel: x86_64 Linux 5.18.6-200.fc36.x86_64

I've also got the following winetricks packages installed:
d3dcompiler_47
d3dx9
dotnet40
dotnet48
dotnetcore3
dxvk
vcrun2019

Also, I don't suppose there is a way to manually install mods without a GUI or .exe manager? If there is, I couldn't find a reference to something like that anywhere. I'm also going to attach the HedgeModManager log in case that helps with anything.

[HedgeModManager_d3d9.log](https://github.com/thesupersonic16/HedgeModManager/files/9007186/HedgeModManager_d3d9.log)

**Comment by thesupersonic16** [comment]
Asking in #219 might be helpful. I am not sure why it is causing the error. As for installing without a manager, you can by editing ModsDB.ini, it follows the same format as CPKREDIR.

**Comment by megasart** [comment]
If you on steam deck, I recommend opening the game through the game mode and not desktop. Not sure if this helps but when I ran generations in desktop mode it would not work, afterwards I went to game mode it went perfectly fine (even though generations lags a bunch on deck for no good reason).

**Comment by confiscatedharddrive** [comment]
I'm not running it on Steam Deck, it's why I mentioned I'm on Fedora 36. I'm running it off my laptop that runs Linux.

**Comment by megasart** [comment]
> I'm not running it on Steam Deck, it's why I mentioned I'm on Fedora 36. I'm running it off my laptop that runs Linux.

Ah sorry then
