### ISSUE TITLE
Sonic Origins won't launch on Linux with HedgeModManager with d3d11.dll file

### ISSUE THREAD

**Issue by DarkSparkish** [thesupersonic16/HedgeModManager#446]
## Describe the issue/bug
I decided to try and get HedgeModManager working with Sonic Origins on Steam, as I have gotten it to work easily with no issues in Sonic Generations using just Wine for HMM. People seem to follow long guides to even get HMM to work, but I've had no issues. I just run HMM, install mods and launch the game. "It just works" as said by Todd Howard.

But in Sonic Origins, I can't for some reason boot into the game without deleting the d3d11.dll file generated by HMM for Hite Mod Launcher, which is what I need in order to actually load my mods. I've also tried using Bottles (which can't even open up HMM for some odd reason) as well as trying to install some components that're required by HMM in such a Linux setup through the game's Wine Prefix using Protontricks (with no success). HMM itself works with no issues (except for Save and Play, presumably I need to launch it through Proton to make that function work, but the manager works without any issues). When I boot up Sonic Origins with that dll-file, it either runs but I don't get anything popping up on the screen, or the game just exits immediately after I press the "Play" button.

In case you are about to bring up the Steam Deck, I'm not using the Steam Deck. I'm running EndeavourOS on my own personal computer.

## Expected Behaviour
I expected HMM to work the same way as it does in Generations, which is to allow me to configure mods, and boot into the game with no issues. No hocus-pocus.

**Comment by thesupersonic16** [comment]
Can you enable the debug console in the settings and tell me if it shows up? If it does show up, can you take a screenshot?

**Comment by DarkSparkish** [comment]
I have it toggled in settings. How does it show up though? Is it inside the manager itself?

**Comment by thesupersonic16** [comment]
It should show up when you press Save and Play

**Comment by DarkSparkish** [comment]
Ah. Well, then I'm afraid that I can't, because (as mentioned) that part of the manager doesn't work.

**Comment by thesupersonic16** [comment]
After enabling it, press Save then launch it using Proton.

**Comment by DarkSparkish** [comment]
I struggle to get HMM running through Proton (unless there's a stupidly easy way I don't know of). Tried following whatever guides are out there. Maybe it's my lack of understanding, but I can't get it working, and Denuvo seems to have locked me out of the game. So lovely. I apologize if you didn't get an answer on precisely why the game doesn't work on Linux with that d3d11.dll file installed. Hope that someone else can figure this out, and find an answer in the Debug console.

**Comment by thesupersonic16** [comment]
Can you tell me the version of the d3d11.dll file? Recently I did push an update to fix startups.

**Comment by DarkSparkish** [comment]
It seems to have been 1.0.2.0, but since I've been locked out of Denuvo (seriously, they can go cry in a corner), I can't test out 1.0.3.0, but I do get the same Denuvo message telling me I can't authenticate on new devices. Not to say that I get into the game, but I hope that's a sign of some kind.

**Comment by thesupersonic16** [comment]
That explains why you had start up issues, I had it fixed in 1.0.2.1 (The fix in 1.0.2.0 was bad).

Not sure how you caused Denuvo to reauthenticate so often, but you will have to wait for the cool-down.

**Comment by DarkSparkish** [comment]
Yeah. I have no idea either why it happened, but I'll wait, and then try again when I have the time.

**Comment by DarkSparkish** [comment]
So I decided to try again, and I get an error stating the following: 
![image](https://user-images.githubusercontent.com/78657573/176708666-c83933a1-dcdc-4180-a677-476c41a1ed7f.png)

Here's what the log states when opening the game:
![image](https://user-images.githubusercontent.com/78657573/176708844-1e53459d-a92b-42a9-8d91-2195f721fad3.png)

**Comment by thesupersonic16** [comment]
That error is unrelated to HedgeModManager and HiteModLoader. You will need to ask the author of OriginsPixelFilter.

**Comment by DarkSparkish** [comment]
If it has nothing to do with HMM, then fair enough. But even with the mod (or any mods) disabled, I alternatively get a little debug console popping up briefly, and the game shuts down. So something must be up.

(I had to time it just right to get the screenshot below, as it appeared for like half a second)
![Screenshot_20220630_165821](https://user-images.githubusercontent.com/78657573/176710366-c307ed8e-bf4a-476a-aa62-2e99ec4e686a.png)

**Comment by thesupersonic16** [comment]
Do you have wine-mono installed? We currently do not fully know the cause of the issue.

**Comment by DarkSparkish** [comment]
Yeah. It's within the game's Wine prefix, and I've also just now installed it for my default Wine. So I suppose I may as well wait for an eventual fix in that case. I appreciate you took the time to troubleshoot the issue, and I hope this gives you an insight of some kind to further improve HMM for Linux users and HMM as a whole even!

**Comment by thesupersonic16** [comment]
We know what module is failing, but we currently do not know how to solve it. We are looking into it. 

You can for the time being run a build with CommonLoader disabled, but this will prevent Codes from loading.
[HiteModLoader.zip](https://github.com/thesupersonic16/HedgeModManager/files/9017618/HiteModLoader.zip) (CommonLoader Disabled)

**Comment by DarkSparkish** [comment]
Gave this a whirl, and it actually worked! The debug screen said it initialized, and the blur fix does indeed work! Now the games in the collection look sharper than before! So I guess that's the solution for Linux users in this case for the time being.

So again, thank you very much!

**Comment by thesupersonic16** [comment]
Can you provide me your proton log file from when you had the crash? I was looking at someone else's log file and it contained some useful information.

**Comment by DarkSparkish** [comment]
Not sure if you know, but where's the log-file to Proton usually located? Inside the Proton-folder itself?

**Comment by thesupersonic16** [comment]
Another user mentioned setting the `PROTON_LOG` environmental variable to 1 and checking the home folder.

**Comment by DarkSparkish** [comment]
Alright, here's the log I get when loading with a d3d11.dll file that doesn't work with the game on Linux. Hope this will help you on understanding the issue better:

[steam-1794960.log](https://github.com/thesupersonic16/HedgeModManager/files/9021651/steam-1794960.log)

**Comment by thesupersonic16** [comment]
Ok, same exact error as someone else had. Is proton able to use dotnet?

**Comment by DarkSparkish** [comment]
Hm. Not sure. I'm not able to install it in the game's Proton prefix, as I get an error message, and from the guides regarding HMM on Linux, there's one who's able to download dotnet480 with Proton 5.0, while someone else got it working on Proton GE 5 point something. So I don't have a clear answer on that.

**Comment by agrastiOs** [comment]
> Ok, same exact error as someone else had. Is proton able to use dotnet?

Proton is able to use dotnet, it has dotnet480 included on the prefixes after all.

Hope this will get fixed some day! I would love to use Sonic Origins Codes (I need these lives on Anniversary Mode)

**Comment by yllekz** [comment]
Same issue here. Running HedgeHodManager not only broke the game, it prevented it from launching ever since. How do we fix this?
