### ISSUE TITLE
[Sonic forces/SteamDeck/Linux] Sonic Forces wont launch after install

### ISSUE THREAD

**Issue by megasart** [thesupersonic16/HedgeModManager#447]
## Describe the issue/bug
After running hedgemodmanager through bottles, with the method described for generations, the game will not launch. There is no error message, the game just doesn't launch.

## Expected Behaviour
The game should run after HMM is installed but it won't run

## Additional Context
HMM runs fine, generations loaded without problem. I am using Cafe 7.7 with hardware acceleration disabled. Please note it is not HMM that isn't opening, it is the game itself after installing HMM. I've tried in steam OS and desktop mode.

**Comment by JDsGod7** [comment]
I'm having the exact same issue. I'm using the bottles method aswell, have you found any fixes yet?

**Comment by thesupersonic16** [comment]
Do you have dotnet472 installed in the game's prefix?

**Comment by JDsGod7** [comment]
> 

I'm a linux noob so I have no idea where I can check that. I know that everything works in hedgemodmanager because it works flawlessly with Generations. Forces just won't launch for me

**Comment by thesupersonic16** [comment]
I cannot give exact instructions, but I'm pretty sure all games but Gens and LW require dotnet472 which can be installed using winetricks with the prefix set to Forces. 

For help installing it, I recommend asking in #219

**Comment by remivamp** [comment]
I'm having the same issue. The debug console closes too fast but the last thing I was able to see before it did so was that it was attempting to load codes when none are enabled

Also I did have dotnet472 installed in the forces (and origins, and puyo tetris 2) prefix

Also the window closes too fast, so I had to use a gimmicky "window close" animation so I could actually keep it on screen long enough to screenshot it and the only one I had was the break into squares one: https://i.imgur.com/Y1as2qt.png sorry for hard to read
