### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by PandaWoozY** [thesupersonic16/HedgeModManager#448]
## Describe the issue/bug
 Application isn't opening 

## Additional Context
 I went to download hedgemodmanager so that I can use this mod for Sonic Generations but when I run it nothing happens. It happens the same even if I put it in the mod folder. I don't know if it's my computer but I need help.

**Comment by thesupersonic16** [comment]
Check you check if you have any files starting with `HedgeModManager` in `%localappdata%\CrashDumps`? If so, zip up the newest one and send it so I can take a look at what is going on.

**Comment by PandaWoozY** [comment]
![image](https://user-images.githubusercontent.com/108445641/176592726-78e7ae7a-2212-4a1f-a9ca-65186cfcbdfd.png)
It is not there
