### ISSUE TITLE
[Sonic Generations] [Bug] Game Doesn't Boot

### ISSUE THREAD

**Issue by Rachel8260** [thesupersonic16/HedgeModManager#449]
After Installing the mod loader, the game no longer boots. Runs perfectly fine when loader is uninstalled. No Error code or anything, just doesn't boot the game.

**Comment by megasart** [comment]
Are you on windows or Linux?

**Comment by Rachel8260** [comment]
Windows
I've also tried playing Lost World and the mod loader won't let that boot either.
