### ISSUE TITLE
sonic origins isn't saving progress

### ISSUE THREAD

**Issue by Rockpikmin101** [thesupersonic16/HedgeModManager#450]
every time I launch the game it doesn't save my progress and closing the game deletes my progress

**Comment by JougaMaya** [comment]
Does it happen with the save redirection option disabled?

**Comment by thesupersonic16** [comment]
Does it happen with save redirection disabled?

**Comment by Rockpikmin101** [comment]
Thanks that fixed it

**Comment by thesupersonic16** [comment]
Can you delete the savedata folder that's in the exec folder and enable save redirection and debug console and show me what it says after reaching the title screen.
