### ISSUE TITLE
Hedge Mod Manager will not load mods for Sonic Origins

### ISSUE THREAD

**Issue by Tails1988** [thesupersonic16/HedgeModManager#453]
I have installed a few mods for Sonic Origins that replaces music and I have them both checked. I hit save and play but the mods didnt work. I still get the default music were the music should be changed by the mods.

**Comment by thesupersonic16** [comment]
Can you enable the debug console in the HMM settings then try a different mod and then send a screenshot of the console after you entered any area where a mod has made modifications to.
