### ISSUE TITLE
[Sonic Colors: Ultimate] install with legendary (epic games launcher alternative) undetected

### ISSUE THREAD

**Issue by Labreezy** [thesupersonic16/HedgeModManager#454]
I have a legitimate install of sonic colors ultimate located on my computer (in a non-epic games folder), but there's no option to specify where it is and everything bar a few buttons is disabled in the mod manager.  I assume because the game is not being launched through epic games launcher which puts it in a standard place, is there a quick fix or would it have to be a feature?

**Comment by thesupersonic16** [comment]
I don't use the Epic Game launcher, but you should be moving the game install using the launcher itself. If said feature exists.

If not you can move the exe into the game folder, but I do not recommend it. There is also a registry option, but it is not fully tested.
