### ISSUE TITLE
[Bug] HedgeModManager cannot load modsDB.ini from Steam Deck SD card 

### ISSUE THREAD

**Issue by downtheoctave** [thesupersonic16/HedgeModManager#458]
## Describe the issue/bug
 I had HMM and Sonic Origins both working on Steam OS but when it came time to run the game with the mods, the debug console says "failed to load [INSERT DIRECTORY HERE modsdb.ini]" and the game would start with the modded hitemodloader.dll compatibility for Deck but no mods would load. I had to fix this by moving Origins to my internal storage and redirecting the mod directory manually in cpkredir.ini. 

## Expected Behaviour
 I expected it to work like it does on the internal storage.

**Comment by RagdollClash** [comment]
Have you tried manually choosing the mod directory within HedgeModManager? You can do so by clicking the button with the three dots.

> Seems manually choosing the mod directory in HedgeModManager allowed for mods using cpk inis (ex. Unleashed Project) to work. It also allowed for mods to actually work on my Steam Deck.
> 
> ![image](https://user-images.githubusercontent.com/15317421/180630004-6e50272b-2647-474d-855a-b09a45bdbfb7.png)
> 
> ![image](https://user-images.githubusercontent.com/15317421/180629993-0ba8338d-ca28-4fc1-be33-1bac164697da.png)
