### ISSUE TITLE
help i srsly don't know what to do anymore

### ISSUE THREAD

**Issue by ammar12121212** [thesupersonic16/HedgeModManager#459]
[HMM_Snapshot_00082022000336.txt](https://github.com/thesupersonic16/HedgeModManager/files/9275882/HMM_Snapshot_00082022000336.txt)
![image](https://user-images.githubusercontent.com/110747672/183268611-e8c47b98-40a7-4a7e-b320-bc59d86a3a48.png)

**Comment by thesupersonic16** [comment]
Sorry for the very late response. It appears your cpkredir config file has become corrupt. If you do still encounter this issue please let me know and delete cpkredir.ini

**Comment by ammar12121212** [comment]
thank you alot
