### ISSUE TITLE
[Gen] Mods not Loading

### ISSUE THREAD

**Issue by canary-1023** [thesupersonic16/HedgeModManager#46]
No matter how hard I try, for some reason, the vanilla game would load. They would be "checked" but when I load up the game the only mod that works no matter what I do is DiscordGenerations. Is there a way I can fix this?

**Comment by thesupersonic16** [comment]
Have you installed and enabled CPKREDIR? Can you show me a screenshot of your Settings?

**Comment by canary-1023** [comment]
> Have you installed and enabled CPKREDIR?

How do I know if I did that?

Here's my settings by the way.
![Capture1](https://user-images.githubusercontent.com/46818515/66248441-18dca480-e6f5-11e9-9dba-d50b1423bc2a.PNG)

**Comment by thesupersonic16** [comment]
Shows its installed, Can I see the cpkredir.ini file and the ModsDb.ini file from the mods folder?

**Comment by canary-1023** [comment]
If this is what you mean, hear you go.
![capture2](https://user-images.githubusercontent.com/46818515/66248616-fe0b2f80-e6f6-11e9-9d57-d046692d2f8d.PNG)

**Comment by thesupersonic16** [comment]
I was asking if you could send the files.

**Comment by canary-1023** [comment]
Oh, in that case...

cpkredir: https://drive.google.com/open?id=18zt7jeVVzMqz1OGyzSidpdsmD8XtpXmq

modsDB: https://drive.google.com/open?id=1iJkgIA2R-ALln4XVQ7qyR17UBEmonYOF

**Comment by thesupersonic16** [comment]
That's weird, the cpkredir.ini file you sent doesn't match with the settings you showed in the screenshot you sent before. Can you please send me the file from the Sonic Generations directory?

**Comment by canary-1023** [comment]
That's strange, it was from the mods folder.

**Comment by thesupersonic16** [comment]
cpkredir.ini doesn't belong in the mods folder in the first place.

**Comment by canary-1023** [comment]
I meant the HedgeMod Manager folder, sorry.

**Comment by canary-1023** [comment]
Also it appears that DiscordGenerations isn't working for some reason.

**Comment by thesupersonic16** [comment]
Closing due to issue being related to an old version of HedgeModManager.
