### ISSUE TITLE
[Sonic Generations] "Widescreen Support" code has title card elements in the expanded area

### ISSUE THREAD

**Issue by RibShark** [thesupersonic16/HedgeModManager#460]
## Describe the issue/bug
In the expanded areas that are uncovered with the "Widescreen Support" code, there are elemernts such as the zig-zags from the title cards that do not disappear. This appears after selecting "New Game" from the menu. Both ultrawide and 16:10 resolutions are affected.

## Expected Behaviour
These title card elements should disappear when they reach the edge of the screen.

## Additional Context
The Flawless Widescreen fix works but is a pain to set up since it uses an external app, especially on the Steam Deck. Would be nice to just be able to have this handled through the mod manager.

**Comment by RibShark** [comment]
Issue still exists.

**Comment by DeaTh-G** [comment]
Codes for HedgeModManager now have a new home at: https://github.com/hedge-dev/HMMCodes. If the issue/suggestion is still relevant please open an issue on that repository as code related issues are no longer being tracked on the main HedgeModManager repository.

Thank you, and sorry for the inconvenience.
