### ISSUE TITLE
[sonic generations] the game crashes when i enter the game while having a specific mod on

### ISSUE THREAD

**Issue by tohchal** [thesupersonic16/HedgeModManager#476]
i downloaded a certain mod (3d spindash for classic sonic) and when in main menu when i hit "continue" the game goes into loading screen and just crashes

**Comment by thesupersonic16** [comment]
Don't know if this applies to non-stage mods, do you have a GTX 1660 or any RTX cards?

**Comment by tohchal** [comment]
yeah i actually have a gtx 1660
