### ISSUE TITLE
[Bug] [SonicFrontiers] Modloader doesn't work with non C: drive

### ISSUE THREAD

**Issue by mathewjubin** [thesupersonic16/HedgeModManager#485]
## Describe the issue/bug
My computer has its boot drive set to the F drive, rather than the C drive (my computer has no C drive), which I believe is causing an issue with trying to load Sonic Frontiers with mods. The error message I receive is shown below.
![image](https://user-images.githubusercontent.com/100049159/200912617-9fb0602f-1092-4f00-8c17-a8be93903b79.png)
Seeing as it specifically mentions the C drive I am assuming that is why I can't load the game with mods, but if there is some other explanation as to why it isn't working for me please let me know.

**Comment by thesupersonic16** [comment]
Does this solve the error? Place the .dll next to SonicFrontiers.exe

[d3d11.zip](https://github.com/thesupersonic16/HedgeModManager/files/9979086/d3d11.zip)

**Comment by mathewjubin** [comment]
Yep that fixed it. Thank you!
