### ISSUE TITLE
how to add mutiple games?

### ISSUE THREAD

**Issue by Kilrua** [thesupersonic16/HedgeModManager#486]
I have Gens, Forces, Lost World, and Frontiers installed but hedgemod only sees generations no matter what I do. I don't see an option to add other games and putting the exe in the game directory does nothing. On the latest version.

**Comment by RagdollClash** [comment]
Is HedgeModManager up to date? Given the fact that you have Frontiers installed, you should be using the development version of the manager. This can be changed in the settings tab.
![2022-11-09_18-06-06_HedgeModManager](https://user-images.githubusercontent.com/15317421/200982722-a48cf103-9d7e-4fe6-b568-38342bc8f3db.png)

**Comment by Kilrua** [comment]
That worked, thank you!
