### ISSUE TITLE
Hedge Mod Manager does not detect any games or allow me to do anything with it.

### ISSUE THREAD

**Issue by sscythess** [thesupersonic16/HedgeModManager#487]
![image](https://user-images.githubusercontent.com/60312761/200995850-b7ce058f-9bf4-432b-8ce8-0aaa6932d6a2.png)
When I open HMM basically everything is greyed out and it fails to detect any of my games, all I can really do is check for updates, change and change the theme or language, I cannot use any mods or even load any games.

**Comment by thesupersonic16** [comment]
Do you have all your games on Steam or Epic and are properly installed?

**Comment by sscythess** [comment]
I've restarted my computer and verified the integrity of the game files for both Sonic Generations and Sonic Frontiers through steam, HMM now detects Sonic Generations but not Frontiers, which is the game I'm currently trying to play using HMM

**Comment by thesupersonic16** [comment]
At this moment Sonic Frontiers is only supported on the development channel until 7.9 gets released. If you want to use it now you need to change your update channel setting.

**Comment by sscythess** [comment]
awesome, thanks for the help!

**Comment by HonorLeon** [comment]
I have a pirate sonic generations and everything works there, I do it in sonic forces and nothing happens and the error Hedge Mod Manager cannot determine the game from the selected executable file

**Comment by Shadas4free** [comment]
Sonic colors ultiamte is not recognized. I see that there are so MANY peoples on internet that got this kind of problem.

Why you didn´t implement manual add exe? 
Why you didn´t tested it before uploading?
Why are you doing program that is not working anymore?

**Comment by RagdollClash** [comment]
We do not support pirated versions of Sonic Generations (2011), Sonic Forces, or Sonic Colours: Ultimate. Please install the game normally using Steam or Epic.
