### ISSUE TITLE
[Bug] [SonicFrontiers] Digital Art Book & Mini Soundtrack doesn't boot with cheats enabled

### ISSUE THREAD

**Issue by MegAmi24** [thesupersonic16/HedgeModManager#488]
## Describe the issue/bug
The Digital Art Book & Mini Soundtrack doesn't boot when the mod loader is installed. The steam_appid.txt file in the game directory does update when it attempts to boot, however the window never appears and there's no sign of the program in the task manager. Uninstalling the mod loader and then booting the program works properly, and Sonic Frontiers itself boots fine with the mod loader installed.

## Expected Behaviour
The Digital Art Book & Mini Soundtrack boots.

## Additional Context
Tested on Windows.

**Comment by thesupersonic16** [comment]
Can you enable the debug console and show me what it says before the game crashes/errors?

**Comment by MegAmi24** [comment]
Found that it's not having the mod loader installed that's crashing it, but rather having cheats enabled. Tested multiple individually and they all crashed it.

**Comment by MegAmi24** [comment]
I'll just go ahead and close it now
