### ISSUE TITLE
[Bug Sonic Frontiers] HedgeModManager does not see Sonic Frontiers on a different drive.

### ISSUE THREAD

**Issue by JAAYapps** [thesupersonic16/HedgeModManager#489]
## Describe the issue/bug
The HedgeModManager does not show the option of Sonic Frontiers. 

## Expected Behavior
I was expecting HedgeModManager to show an option for Sonic Frontiers. 

## Additional Context
I have Sonic Frontiers on steam, my main drive is small, so I don't install any of my games on it. I have a larger SSD I use for my steam library where all my Sonic games are, HedgeModManager Sees generations, forces, Lost World, origins, but not Frontiers. Drive letter is D:. My main OS drive is C:.

**Comment by thesupersonic16** [comment]
At this monent, only the development channel has support for Sonic Frontiers until 7.9 is released.
