### ISSUE TITLE
[Fatal Error][Steam Deck] Switching to Development Channel has caused HMM to always run into an "No Game Detected" Fatal Error When Booting

### ISSUE THREAD

**Issue by ChikoLad182** [thesupersonic16/HedgeModManager#490]
## Describe the issue/bug

I wanted to start using Sonic Frontiers with HedgeModManager on my Steam Deck. I had previously set it up for use with Sonic Generations, Sonic Lost World, Sonic Forces, and Sonic Origins. I went through the Protontricks dotnet48 installation for Sonic Frontiers as usual, this worked fine.

I then booted up HedgeModManager and switched it to development channel as this is required to get Sonic Frontiers to show up in the games list. After doing so, HMM restarted but was immediately met with a fatal error that has mention of "No Game Detected!" in the output log. This will happen whenever I try to boot it up now, and is preventing me from using HMM with any of the other games I had set it up for.

HMM is being run through Bottles.
## Expected Behaviour

HMM should run in Development Mode.
## Additional Context

HMM Info:
    Version: 7.8-2-15210dd
    Args: 
    StartDir: Z:\run\user\1000\doc\7610c514\
    Process Level: Administrator
    Game: No Game Detected!

Exception:
    Type: ArgumentNullException
    Message: Value cannot be null.
Parameter name: path1
    Source: mscorlib
    Function: System.String Combine(System.String, System.String)
    StackTrace: 
       at System.IO.Path.Combine(String path1, String path2)
       at HedgeModManager.Linux.GenerateDesktop() in D:\a\HedgeModManager\HedgeModManager\HedgeModManager\Linux.cs:line 47
       at HedgeModManager.HedgeApp.Main(String[] args) in D:\a\HedgeModManager\HedgeModManager\HedgeModManager\HedgeApp.xaml.cs:line 189
    InnerException:

**Comment by thesupersonic16** [comment]
Can you show me a screenshot of the Bottles GUI?

**Comment by ChikoLad182** [comment]
![2022-11-12_19-25](https://user-images.githubusercontent.com/53979498/201491249-7b64160e-e93b-442c-a23b-c6ddd202811d.png)

Hopefully this helps. Still a little new to this so let me know if you needed a different screen.

**Comment by thesupersonic16** [comment]
I may make an update later today to handle that error better, does removing all those programs and readding the HMM exe fix it?

**Comment by timedroid** [comment]
I'm running into this same error after clicking "Update" when prompted for a new release.

**Comment by timedroid** [comment]
Hedgehog Manager is the only thing in the bottle; installed using the Linux instructions linked from the wiki.

**Comment by ChikoLad182** [comment]
> I may make an update later today to handle that error better, does removing all those programs and readding the HMM exe fix it?

I removed the programs from Bottles and tried re-adding a fresh .exe and this at least reverted to the release version so I could use it again with the four games I already installed it for.

Then I tried going to the development channel again and it was the same issue, again I needed to grab a fresh .exe to fix it again.

So I at least have been able to revert it back to being usable for the Sonic games I already had it set up for. But it seems switching to development channel on Steam Deck is not doable right now which blocks me from using HMM for Sonic Frontiers at the moment.

Probably not the biggest deal as I imagine Sonic Frontiers support will be added to the Release channel at some point anyway which would get around the issue I'm having (since it seems switching to development channel is the main thing tripping it up from what I understand), and I understand HMM was not designed with Linux in mind so things are expected to break there. Just thought I'd document the issue for anyone else hoping to mod Sonic Frontiers on Steam Deck right now. Would be nice if development channel is something that could work on Steam Deck though. Maybe I'm just doing something wrong?

**Comment by thesupersonic16** [comment]
The issue is not because of switching, it's because of a bug in the newest dev version. I have not yet fixed it, but I will let you know when I have pushed a possible fix.

I suspect the issue is that Bottles is not setting the folder field. If you want, can you look for your bottle yml file? It should be located in a folder called HedgeModManager somewhere in `~/.var/app/com.usebottles.bottles`

**Comment by thesupersonic16** [comment]
I just pushed an update on the development channel to ignore errors with creating shortcuts. Can you please check if your issue is resolved?

**Comment by ChikoLad182** [comment]
Hey, sorry for the late response. I tested your new update and it resolves my issue. Development build downloaded and run without a problem. Then I just made sure HMM had my correct Sonic Frontiers directory by manually directing it to it and tested a mod in-game and it worked.

![image](https://user-images.githubusercontent.com/53979498/201642653-45ce3290-45f2-4031-9cb9-b978d1e4dba5.png)
