### ISSUE TITLE
[Bug] HE2 modloader crashes instantly when modloader installed on some machines running linux

### ISSUE THREAD

**Issue by lolman9998** [thesupersonic16/HedgeModManager#491]
## Describe the issue/bug
Whenever I start Frontiers on linux with the modloader installed, the game crashes without a window ever opening for the game.

## Expected Behaviour
Game starts with any enabled mods running

## Additional Context
Arch Linux 6.0.7=arch1-1
RTX 2060 Super
Ryzen 2700
GE-Proton7-41
HedgeModManager works perfectly fine for generations so I can confirm it is set up correctly.

**Comment by thesupersonic16** [comment]
Sonic Fronters very likely needs `dotnet48` installed in the game's prefix for the ML to load. Try install it using something like protonticks or winetricks.

**Comment by sonic2kk** [comment]
I was able to update the modloader just now with Hedge Mod Manager from the latest git.

I did not test if mods work but Frontiers works for me vanilla, and the modloader seems to be installed correctly for Frontiers (the DLL looks like it was updated at the correct time and such).

You may want to try disabling and re-enabling the modloader from the MO2 settings tab.

**Comment by lolman9998** [comment]
Just tried installing dotnet48 and disabling all my mods again, same result. Starting to wonder if this is just my config but frontiers launches fine without the modloader installed.

**Comment by sonic2kk** [comment]
Are you sure you definitely installed `dotnet48` into the Sonic Frontiers prefix? Please make sure it's installed in the prefix the game is using.

I have only played through the first ~30 minutes of Frontiers and don't want to use any mods yet. You could try running Frontiers with a different version of Proton, I am running with Proton Experimental

It is also possible that the modloader is just not compatible with Sonic Frontiers on Linux.

**Comment by lolman9998** [comment]
Just gave experimental a try, same result. Also confirmed dotnet48 is in the specific prefix. Im gonna try proton 7 real quick just in case experimental was also not working.

**Comment by sonic2kk** [comment]
Hmm, maybe the modloader isn't even loading for me. I just tried enabling the "Force Switch Controller UI" code and it doesn't seem to have done anything.

Do you have any very "low risk" mods I could try out? That is, mods that have very minimal gameplay impact and that don't have a lot of dependencies? That way I can see if mods work (maybe one to disable the game intro splashes? :sweat_smile:)

**Comment by lolman9998** [comment]
You could try the mod I am trying, improved physics (gotta love cyberspace) or just a model swap. Both seem minimally impactful.

**Comment by sonic2kk** [comment]
Actually nevermind, I enabled the "Infinite Boost Gauge" code and it works fine for me (tested GE-Proton7-35, GE-Proton7-41 and Proton Experimental).

This is quite strange, you could try making sure you are using the latest HMM get (`618cced` at the time of writing).

Thanks for replying with the mods, I might try the improve physics mod out later and see if it works.

Are you playing the Steam version of Sonic Frontiers? That is the version I am using and testing with. I also installed HedgeModManager using SteamTinkerLaunch. I'm also on Arch with KDE Plasma Wayland but with a slightly newer kernel and an AMD GPU.

**Comment by sonic2kk** [comment]
Just tested installing the 06 Sonic mod and it seems to work. 

![image](https://user-images.githubusercontent.com/7917345/201489549-1c2478f2-3a0d-4f58-bf8c-af431ad327a0.png)

Sorry that I can't offer more help at this moment. Maybe you could try deleting the game's prefix and reinstalling dotnet48 into it?

**Comment by lolman9998** [comment]
I am using steam, yes.
I used that q4wine tutorial thats been floating around to get hedge to work.
Also I am on plasma too, though I could give gnome a try
I know my nvidia card is causing some problems with the game, who knows if amd will stop the crashing later on though. Had to pull out my windows machine to beat the game.

**Comment by thesupersonic16** [comment]
You could try STL. But I think you might have installed dotnet48 incorrectly unless something else broke like configs.

**Comment by sonic2kk** [comment]
Hmm, HMM should work if you just installed dotnet48. Maybe there's something else causing problems here. Since the game uses d3d11.dll to inject the mods and codes (correct me if I'm wrong here HMM team) maybe the Nvidia drivers don't play nice with it? I doubt it though.

> who knows if amd will stop the crashing later on though

Sorry, this is more my own curiosity, but on my PC and Steam Deck I haven't had any crashes with the game and was actually hoping to give it a try today with GE-Proton7-41. Does the game crash on AMD GPUs?

**Comment by lolman9998** [comment]
We will see about amd then. Nvidia crashes consistently at the same parts making the game unplayable, but thats not related to this.
Maybe we could revisit this with updated nvidia drivers.
lemme go see what stl is and give it a go before waiting for nvidia to fix their drivers.

**Comment by thesupersonic16** [comment]
Does deleting Codes.dll from the mods folder than launching using Steam work? That will rule out if it's an issue with dotnet48. I just want to be clear with that first.

**Comment by lolman9998** [comment]
> Does deleting Codes.dll from the mods folder than launching using Steam work? That will rule out if it's an issue with dotnet48. I just want to be clear with that first.

no such luck. still nothing from it.
also, would you mind telling me what stl is? cant find anything about it

**Comment by thesupersonic16** [comment]
> no such luck. still nothing from it.
also, would you mind telling me what stl is? cant find anything about it

Ok, then it may not be a dotnet48 issue. STL is [Steam Tinker Launch](https://github.com/sonic2kk/steamtinkerlaunch) which recently got support for installing HMM and everything it needs. But I think its only on the git version.

Not sure if it will help, but can you try enabling the debug console to see if it shows any error messages?

**Comment by lolman9998** [comment]
got nothing from debug console. might give stl a try later on then. we might also need to wait for another nvidia user to weigh in so we can see if its a driver issue.

**Comment by sonic2kk** [comment]
Just wanted to say that for now yes, HMM support is still only in git. There are plans to roll out a new release sometime soon (the changelog is getting pretty long too :sweat_smile:).

More information about HMM usage with SteamTinkerLaunch can be found here: https://github.com/thesupersonic16/HedgeModManager/issues/219#issuecomment-1312238594

I would recommend trying with a clean Wineprefix for Sonic Frontiers (deleting `/path/to/libraryfolder/steamapps/compatdata/1237320`). SteamTinkerLaunch's Game Files menu will let you select and open the Prefix with your default file manager too :wink:

Enough advertising from me heh. Hopefully STL fixes your issue and if not, reporting this to Nvidia sounds like a good idea. I am not totally sure if injecting into d3d11 could cause driver problems but I suppose it is possible. Not totally sure though.

I also think a beta for the Nvidia drivers came out very recently (maybe 2 days ago?) - If you are not using that, maybe you could give it a try.

**Comment by thesupersonic16** [comment]
I am a Nvidia user, but I don't own the game, and I only have the game shared to me on my Windows OS. I could try ask my friend for access again so I can try it.

**Comment by the-outcaster** [comment]
[steamtinkerlaunch.log](https://github.com/thesupersonic16/HedgeModManager/files/9999018/steamtinkerlaunch.log)
Got a log file for STL attached, using a RTX 3060 on Pop!_OS. HMM won't even load. Don't know if this log will help at all.

**Comment by sonic2kk** [comment]
Thanks for the log!

Your Winetricks version may be too out of date and the installation of dotnet48 may have failed for such a recent version of Proton (GE-Proton7-41 is what its using). Just going off this line in your log:

```
Sun Nov 13 05:00:16 PM EST 2022 INFO - chooseWinetricks - Using systemwide winetricks with version '20210206'
```

And also the length of time between it trying to install dotnet48 for the Sonic Frontiers' prefix (I guess this log is from a second run of HMM). The log looks like it only spent 2 minutes trying to install dotnet48 for Sonic Frontiers' prefix.

It is also possible that you could be missing `cabextract`, which is needed in general for Winetricks to install `dotnet48`.  

You should be able to run `sudo winetricks --self-update` to force an update of Winetricks (the current latest is `20220411-next`). There is an open issue about distros not using the most up-to-date version of Winetricks on their repo, though it is using a newer version than the log is reporting here: https://github.com/Winetricks/winetricks/issues/1964

Hopefully that helps :-) 

P.S. you will also need to delete `~/.config/steamtinkerlaunch/hedgemodmanager/compatdata` - This is the prefix HMM runs in, and since the prefix is setup but the dotnet installation failed, it won't try to install it again and so HMM won't start. But deleting it will "force" STL to re-create the prefix, and so it will retry installing dotnet48.

**Comment by the-outcaster** [comment]
Success after updating winetricks and deleting the compatdata -- thanks!!

**Comment by sonic2kk** [comment]
Oh hell yeah, glad to hear it! Since you have an Nvidia GPU please do report back with how mods work -- For Sonic Frontiers and otherwise. It would be unfortunate if this is a driver bug.

Phew, I stayed awake holding my breath a little on that one :-)

**Comment by the-outcaster** [comment]
![20221113223715_1](https://user-images.githubusercontent.com/101075966/201572392-7f2dbf43-5cbc-430d-abcc-c7b1126e6292.jpg)
Working just fine with Frontiers

**Comment by lolman9998** [comment]
Been a while, huh?
I recently swapped my gpu for a 6700 xt and only just thought to try it again. Somehow, the bug persists, so im pretty sure its not gpu related. Im gonna try to grap a picture of my debug window before it closes to get something else to go on.

**Comment by lolman9998** [comment]
![Screenshot_20230116_195428](https://user-images.githubusercontent.com/42286057/212792812-bf3b3925-799f-4ce9-833c-8c14cd0731f9.jpg)
Bit blurry, but its something. Cant normally screencap as it closes so fast.

**Comment by lolman9998** [comment]
Just switched distro to Nobara, still getting same error.

**Comment by lolman9998** [comment]
Just got forces on sale, problem occurs with it too. It is absolutely a HE2 modloader issue.

**Comment by thesupersonic16** [comment]
Blame whatever side you want, the issue is with mono, just replace it with dotnet48.

**Comment by lolman9998** [comment]
![image](https://user-images.githubusercontent.com/42286057/226198078-0428c0e5-011c-4e74-b1c4-778a91deaacf.png)
Looks like steamtinkerlaunch already installed dotnet48 (i switched to running via steamtinkerlaunch after switching distros)

**Comment by lolman9998** [comment]
Upon further testing forces now just never opens a window or crashes, steam just says it is running. To change this result i forced a winetricks self upgrade, purged the prefix and regenerated it, and then attempted to install dotnet48 again. these steps do not produce different results on frontiers, only forces.

**Comment by lolman9998** [comment]
So I found a way to install dotnet48 on a seperate system with more success, and copy the files onto my main system manually. No change. Dotnet is 100% successfully installed, and I get no output, and the game still crashes. I have tried every debug step, this being a dotnet issue seems entirely impossible. If you still believe this is a dotnet issue please chime in with something for me to act on so we can just get this solved.

**Comment by lolman9998** [comment]
Reformatted again, made sure to let steamtinkerlaunch handle all configuration and confirmed it installed dotnet48 in all applicable prefixes. Still same result.
