### ISSUE TITLE
[Bug] Sonic Frontiers mods don't load when using a profile other than Default

### ISSUE THREAD

**Issue by blue-person** [thesupersonic16/HedgeModManager#493]
## Describe the bug
In HedgeModManager development version 7.8-2-aae6239, when trying to activate mods for Sonic Frontiers under a profile other than Default, they don't load, leaving the game completely vanilla. However, when these same mods are enabled in the Default profile, all mods run and behave normally. It is worth mentioning that this only happens with mods, since the cheats are activated normally in both cases.

## Expected Behaviour
The mods should run correctly either in the Default profile or in any other.

**Comment by thesupersonic16** [comment]
Sorry for not noticing this issue. This has been fixed in https://github.com/hedge-dev/HE2ModLoader/commit/26fe49352479b240f5819af54300157f0e1e7ab6, but has not yet been released for HedgeModManager.

I will close this issue on the next HE2ModLoader release.
