### ISSUE TITLE
[Bug] [Sonic Frontiers] Mod Manager causes crashes on startup (7.8-2-219379f)

### ISSUE THREAD

**Issue by Boneshouse** [thesupersonic16/HedgeModManager#494]
Was working fine up until recently. current version is (7.8-2aae6239)
Mod loader will crash SF on startup, before a screen even boots up. Uninstalling the mod manager causes the game to launch fine, i'm assuming it's something with the .dll being added on install. Even with no mods, codes or save file redirection disabled, it still crashes.
I'm on windows 10.

edit: still broken in 7.8-2-219379f
edit 2: tried uninstalling and reinstalling the game, still broken 11/17

**Comment by thesupersonic16** [comment]
Did the modloader work before updating, or has the modloader never worked?

**Comment by Boneshouse** [comment]
> Did the modloader work before updating, or has the modloader never worked?

Was working perfectly fine until the recent update.

**Comment by thesupersonic16** [comment]
In `%localappdata%\CrashDumps` do you have a file starting with `SonicFrontiers`?

**Comment by Boneshouse** [comment]
I do! this is the dump produced from the crash
[SonicFrontiers.exe.12004.zip](https://github.com/thesupersonic16/HedgeModManager/files/10001536/SonicFrontiers.exe.12004.zip)

**Comment by thesupersonic16** [comment]
Can you place this DLL next to SonicFrontiers.exe and see if a message box appears? If it does, can you show me a screenshot of it?

[d3d11.zip](https://github.com/thesupersonic16/HedgeModManager/files/10001590/d3d11.zip)

**Comment by Boneshouse** [comment]
![image](https://user-images.githubusercontent.com/118165393/201626210-1b05a86c-5415-4de4-b6c3-7908e87a2bf4.png)

**Comment by pankeke-chocolate** [comment]
Hi, not to bother, but I also do have the same issue while using the lastest version of HedgeModManager. In my case, I use DXVK-Async 2.0 on Windows to make the game run better. I am not sure if it's a compability problem on DXVK, due to the HedgeModManager changing the DLL. 

Here is the dump produced by the crash just in case is needed it. 
[SonicFrontiers.exe.15396.dmp.zip](https://github.com/thesupersonic16/HedgeModManager/files/10028485/SonicFrontiers.exe.15396.dmp.zip)

**Comment by TBirdSoars** [comment]
I've been running into the same issue. DXVK uses its own d3d11.dll and dxgi.dll. So, when attempting to launch through Hedge Mod Manager, it displays the message "Mod Loader Not Yet Installed!" when DXVK is installed. Clicking "Yes" causes the mod manager to overwrite d3d11.dll again, so the game fails to launch properly. Instead, it just produces a "SonicFrontiers_dxgi.log" file, when there should also be a "SonicFrontiers_d3d11.log" file. For now, it seems like the mod manager and DXVK are incompatible.

**Comment by RagdollClash** [comment]
You need to turn DXVK into a HMM mod.
https://github.com/thesupersonic16/HedgeModManager/wiki/Loading-DirectX-Dlls

**Comment by TBirdSoars** [comment]
OK, I tried that and it seems like it's loading d3d11.dll - there is a log file being produced in the mod's folder, but the file is empty and the DXVK HUD doesn't appear on screen. Also, I'm not sure how to load d3d11.dll and dxgi.dll together in one mod. I tried adding them as separate mods, but that still didn't work and produced empty log files.

**Comment by RagdollClash** [comment]
This might sound weird, but try leaving DXVK's dxgi.dll next to the game executable.

**Comment by TBirdSoars** [comment]
Just tried it. Something similar to my initial attempt happens - the game doesn't start, and a dxgi log file is produced:
[SonicFrontiers_dxgi.log](https://github.com/thesupersonic16/HedgeModManager/files/10505973/SonicFrontiers_dxgi.log)
The d3d11 log is also still blank.
