### ISSUE TITLE
Mod Manager isn't detecting Frontiers at all

### ISSUE THREAD

**Issue by InfernoDigital** [thesupersonic16/HedgeModManager#497]
I followed the instructions to download the exe and place it somewhere on my hard drive, can't find Frontiers.

Put it in the folder with Frontiers, can't find Frontiers.

Even tried dragging Frontiers onto the mod manager, can't find it.

Not sure what I'm doing wrong here.

**Comment by Knuxfan24** [comment]
You need to be on the development branch for Frontiers right now.

**Comment by InfernoDigital** [comment]
aha! thanks for the tip!

**Comment by InfernoDigital** [comment]
How uh... how do you get the dev branch? I don't have any betas available.

**Comment by thesupersonic16** [comment]
Under Settings in HMM
![image](https://user-images.githubusercontent.com/25761885/201984488-15970d0d-be9d-41b4-b380-31318b07f39a.png)

**Comment by InfernoDigital** [comment]
Aha! thanks guys!
