### ISSUE TITLE
A bug when trying to launch the game via modmanager

### ISSUE THREAD

**Issue by Muzzarino** [thesupersonic16/HedgeModManager#5]
When I try to launch the game with the loader, I get an error message saying this:

"An error occured! See "HedgehogModManager.log" for more info and report the file if possible.

**Comment by thesupersonic16** [comment]
Please include "HedgeModManager.log" like what the message said. :)

**Comment by Muzzarino** [comment]
This is the problem from the log:

[2017/11/13 21:27:41]: Exception thrown while saving ModsDB and starting.

**Comment by thesupersonic16** [comment]
Can you send the whole file?

**Comment by thesupersonic16** [comment]
Closing I'm getting no reply, Reopen if the issue continues in the newest version.
