### ISSUE TITLE
[Bug] [Sonic Frontiers] Controller disabled when running game via HedgeModManager

### ISSUE THREAD

**Issue by nikotonn** [thesupersonic16/HedgeModManager#500]
I'm rocking an 8bitdo Pro 2, set to Xinput mode. Running the game normally it all works out fine, but when I launch it through the mod manager, my controller is simply disabled. No input is taken, I am reduced to playing with keyboard/mouse which like...it's doable? But maybe no thanks?
As far as I can tell, this seems to have to do with Steam, as I don't see Steam's usual "loaded your controller profile" message appear when launching the game through the mod manager. Does...the game not have its OWN native support for controllers or am I missing something

**Comment by RagdollClash** [comment]
You need to launch the game through the game launcher (for Frontiers it's Steam). This can be ticked on in the Settings tab.

**Comment by nikotonn** [comment]
Aha! That does fix it, thanks!
