### ISSUE TITLE
Crashes when loading different islands in Sonic Frontiers. [Windows]

### ISSUE THREAD

**Issue by ShockDragonDelta** [thesupersonic16/HedgeModManager#507]
It worked fine up until now. Every time I try to switch to an island, it now crashes. Even with the mod manager deleted, it still crashes. I had to uninstall. I hope this works, but in the meantime, please fix this.

**Comment by ShockDragonDelta** [comment]
Edit: Even uninstalling Sonic Frontiers didn't work. I think my game is actually messed up now thanks to this.

**Comment by thesupersonic16** [comment]
Are you still getting this issue?
