### ISSUE TITLE
HedgeModManager Tries to open with steamtinkerlaunch, but nothing happens

### ISSUE THREAD

**Issue by CubixTwist** [thesupersonic16/HedgeModManager#508]
So, i installed HHM with STL and things were going smoothly until it wouldn't open. I figured i didn't set it
up correctly, so did the setup again and nothing. It just says it's configuring HMM and launching HMM, but the process stops.

![Screenshot_2022-11-21_18-31-19](https://user-images.githubusercontent.com/114561247/203132750-9ecade4c-04ed-4b06-82a8-b4dd34a69e40.png)

**Comment by sonic2kk** [comment]
You need to provide more information:
- Distro
- SteamTinkerLaunch version
- steamtinkerlaunch.log file

The Terminal output is only for user benefit to see what is going on, it isn't useful for fixing bugs.

I'm already looking into another HMM issue, I will look into this once I make more headway with that and once I get the needed information from you.

**Comment by CubixTwist** [comment]
Oh, i understand. But just in case, my distro is GalliumOS, STL version is v11.12.20221121-3 and here is the log file.
[31337.log](https://github.com/thesupersonic16/HedgeModManager/files/10060739/31337.log)

**Comment by sonic2kk** [comment]
That is a log file from running `steamtinkerlaunch settings` - Try running `steamtinkerlaunch hmm start` and then attaching the log file found at `/dev/shm/steamtinkerlaunch/steamtinkerlaunch.log`

**Comment by CubixTwist** [comment]
[steamtinkerlaunch.log](https://github.com/thesupersonic16/HedgeModManager/files/10060951/steamtinkerlaunch.log)

**Comment by sonic2kk** [comment]
Ah, the Winetricks version you are using appears to be too old: `chooseWinetricks - Using systemwide winetricks with version '20180217'` - SteamTinkerLaunch requires `20220411` at *least* or preferrably `20220411-next`.

If this is installed via package manager, you can update this with `sudo winetricks --self-update` which will force Winetricks to update itself. If it's installed locally, `sudo` may not be required (advising users to run sudo commands at will is not always a good idea, so I try to give the rationale when I do :slightly_smiling_face:)

Once updated, you'll need to delete and re-create the Wineprefix that HMM runs in, this is stored at `~/.config/steamtinkerlaunch/hedgemodmanager` - You can delete the `hedgemodmanager` folder and then re-run `steamtinkerlaunch hmm start nightly`.

This will setup the prefix for HMM again, and should correctly install dotnet48 for HMM to start up in.

If it does not start up after this, please attach the steamtinkerlaunch log again (that log will let me see what happened during install) as well as any `installDotNet.log` files - all of these are in `/dev/shm/steamtinkerlaunch`. The `installDotNet` logs show what happens during the Winetricks setup of dotnet, so I can see if it errored out anywhere. The steamtinkerlaunch log lets me track the variables and the majority of the flow during a SteamTinkerLaunch run.

<hr>

All being well though, a Winetricks update and a re-creation of the HMM prefix should fix this :-) You *may* also need to delete and re-create the prefix for any supported games you want to mod, as it may have tried and failed to install dotnet and there may be an invalid / partial dotnet install there that could be messing things up. I'm not sure how prevalent of an issue this is, but I tend to just delete prefixes in such cases.

**Comment by CubixTwist** [comment]
I can't install Winetricks 20220411, it just says unknown option --self-update

**Comment by sonic2kk** [comment]
That is a strange problem. Maybe self-update wasn't in your version of Winetricks, though I thought I used it as far back as 2016.

I'm not sure of the steps to manually install Winetricks or with the ins and outs of GalliumOS. Is there a way you could install a more up-to-date Winetricks? Your version appears to be from 2018, so it is a bit behind.

Sorry I can't help more here, if I find out more I'll give a reply. It might be worth talking to the packager on the GalliumOS side about updating Winetricks here.

**Comment by sonic2kk** [comment]
There is an answer on Stackoverflow about updating Winetricks manually on Ubuntu. Maybe this has some hints? https://askubuntu.com/questions/755059/how-do-i-get-the-latest-version-of-winetricks-on-ubuntu

It also mentions Cabextract, which may not come with GalliumOS. You may need to install that as well.

The exact steps here may not work on your distribution but maybe the steps have some hints :-)

**Comment by CubixTwist** [comment]
Thank you! It actually worked, you're a lifesaver.

**Comment by sonic2kk** [comment]
No problem :-) Feel free to close this issue!

Just a heads up: I'll be taking a bit of a break from today to disconnect and enjoy some games. I'm sorry if you run into HMM issues during this time, but feel free to post on the pinned HMM issue for support.

The main things you might run into are:
- Sonic Frontiers isn't detected - Requires HMM nightly (can be set in the STL settings or in the global config file you can set the version from `stable` to `nightly`)
- STL's UI doesn't work - May require a more up-to-date Yad package
- 64bit games aren't working - May need to manually install a DLL (instructions on the HMM wiki's Linux section)

That's everything I can think of. If you have other issues the Linux issue is closed but active with support. There are some good users over there that can hopefully help you out in my absence.

Thanks!

**Comment by CubixTwist** [comment]
HMM is still not opening, but i will try to resolve this issue tomorrow.

**Comment by sonic2kk** [comment]
One thing I just thought of: Your system may not have `jq` installed, which may be needed for fetching the required Proton version, as it allows for parsing JSON responses in Bash, the language SteamTinkerLaunch is written in.

I *think* most distributions do actually come with this, but some do not. I also thought most distributions came with `cabextract` until recently when really most do not 😅

There were also some updates recently to SteamTinkerLaunch to improve Proton detection for HMM, try updating to the latest version (updating your package or a manual install might work -- However you got the latest version before 🙂)

After you've verified you're on the latest version and you have `jq` installed, try deleting the prefix in `~/.config/steamtinkerlaunch/hedgemodmanager` and then retrying an install.

And if that doesn't work post the log from the installation attempt and the dotnet files, just the same ones I listed earlier :-)

If you'd like you're also free to look at these files yourself and see if anything stands out to you. Of course there's no need to do this but I'm just saying feel free to have a browse yourself at the logs.

There haven't been any reported users with GalliumOS before, so there may be some extra steps needed for this distribution.

Thanks!

**Comment by CubixTwist** [comment]
Ok thanks, you said you wanted to take a break from github, so i will leave you alone now.
