### ISSUE TITLE
[SonicGenerations] none of the codes in the hedgehog manager work or just outright crash the game

### ISSUE THREAD

**Issue by tohchal** [thesupersonic16/HedgeModManager#513]
it's mostly stuff that changes the gameplay side (i haven't tried any other ones) of things stuff like:
all walls are wall-jumpable (doesn't work)
buy anything at the skill shop with any points (crashes when i visit the skill shop)
all rings can be light dashed (i think it crashes when the real light dash rings appear but normally doesn't work)
3d spindash doesn't crash (doesn't work as the game still crashes when you attempt to spin dash in 3d)
infinite lifes (crashes the game when dying)
faster homing attack (crashes outright at the boot up)
disable lives (crashes when loading into the hub)
and couple others

**Comment by thesupersonic16** [comment]
All Sonic Generations codes require the latest version of the game from Steam to work correctly, otherwise it will crash. Can you confirm that you have the latest version installed?
