### ISSUE TITLE
[Sonic Frontiers]  "Disable In-Game Letterboxing (v1.01)" crashes the game after today's update.

### ISSUE THREAD

**Issue by atomicwrites** [thesupersonic16/HedgeModManager#522]
## Describe the issue/bug
Frontiers updated today and would not start, the steam play button would just change to stop for a few seconds then back to play. Enabling the debug console would show it crashes at `[HE2ML] [INFO]  Loading Codes...`. I was able to track it down to the "Disable In-Game Letterboxing (v1.01)" code being enabled.

## Expected Behaviour
Disable In-Game Letterboxing does not prevent the game from starting.

**Comment by thesupersonic16** [comment]
Codes labeled as `(outdated)` formally as `(v1.01)` are only for v1.01 of the game. v1.10 of Frontiers came out today and such. those code will not work. Please check for code updates periodically as we are working on getting the codes updated in our free time.

I will now be closing this issue. If you see any issues with codes without any of those markers in the title, please open a new issue for those.
