### ISSUE TITLE
[Bug] No game detected

### ISSUE THREAD

**Issue by JurreST** [thesupersonic16/HedgeModManager#525]
## Describe the issue/bug

Hi, i'm trying to mod sonic frontiers, but the hedgemodmanager cant find it?
When i open it it just says "no games detected" and i cant fill in a install location or anything.

I'm guessing its because ive installed the game on an external hard drive and that's what throwing it off, but if i was just able to enter the game install location that'd probably be able to fix it

## Expected Behaviour

To recognise the game :3

**Comment by JurreST** [comment]
Updated problem: the development build does recognise the game, but avira really doesnt like the development build.
Ive added an exception but it keeps quarantining something in my temp folder that has to do with the development build apparently

**Comment by thesupersonic16** [comment]
At this monent Frontiers support is still development only. As for the temp folder, HMM downloads its updates there then applies it. 

Since you have solved your issue, I will be closing the issue. Feel free to reopen if needed.

**Comment by KiloLW** [comment]
hey im having the same problem but its with sonic generations
