### ISSUE TITLE
[SonicFrontiers] DXVK 2.0 not working as a mod

### ISSUE THREAD

**Issue by droi34** [thesupersonic16/HedgeModManager#526]
I'm running Steam Deck with Windows 10. For some reason DXVK just crashed the game when loaded as dll, even though everything is added properly (d3d11.dll added as dll). At first I thought the problem was that i left identical dxvk dll in main game folder. But it didn't change everything, now it's only able to open game window and close it after i deleted identical files from the main path.

**Comment by ActualMandM** [comment]
Use the 32-bit d3d9 dll instead.
