### ISSUE TITLE
[Sonic Frontiers] Crash upon engine cutscene triggering

### ISSUE THREAD

**Issue by VanillaCold** [thesupersonic16/HedgeModManager#529]
## Describe the issue/bug
Every time a tutorial/in-engine scene occurs, the game just outright crashes if the modloader is installed. Uninstalling the modloader fixes the bug entirely.

## Expected Behaviour
The game would continue running as normal, like when the modloader is not installed.

## Additional Context
I'm using Windows 10 version 21H2.
My computer has an Intel i7-8565U CPU and an AMD Radeon r7 M440.
(Not the best specs, hence why I really need mods to play the game.)

Here's the memory dumb it produces, too:
https://1drv.ms/u/s!AvuubHYsSlZUo0LDXJtqsvuFg2-M?e=T6yxRL

**Comment by thesupersonic16** [comment]
Do you have any mods or codes enabled?

**Comment by VanillaCold** [comment]
No.
At first I tried it with a low-spec mod that removed some scenery, but the issue still persisted after uninstalling the mod.

**Comment by thesupersonic16** [comment]
Can you show me a video of the crash?

**Comment by VanillaCold** [comment]
Here's a video.

https://user-images.githubusercontent.com/35960636/205492029-1838b1cc-fdcb-4367-a0f2-bd345eb5c072.mp4

**Comment by thesupersonic16** [comment]
Works fine for me, are you able to save your game without any issue?

**Comment by VanillaCold** [comment]
Just tested that and no, I can't save my game with the modloader installed.

**Comment by thesupersonic16** [comment]
That issue seems to be happening to a small amount of people using the mod loader. Did you install the game directly from Steam or move the files at all?

Can you also press Ctrl + F1 in HMM and send the txt file it mentions? This file contains some of your configuration files.

**Comment by VanillaCold** [comment]
I installed directly from Steam to an SDXC card.
As for Ctrl+f1, it seemingly is just doing nothing when I press them in the HMM.

**Comment by thesupersonic16** [comment]
My bad, Shift + F1

**Comment by VanillaCold** [comment]
[HMM_Snapshot_00122022134421.txt](https://github.com/thesupersonic16/HedgeModManager/files/10148618/HMM_Snapshot_00122022134421.txt)

**Comment by thesupersonic16** [comment]
Can you make a folder in your SonicFrontiers folder called `savedata` then try to save?

**Comment by VanillaCold** [comment]
Still crashes, unfortunately.

**Comment by thesupersonic16** [comment]
Does disabling save redirection in the settings tab fix the issue? I am thinking save redirection is broken.

**Comment by VanillaCold** [comment]
It did, thanks.

**Comment by thesupersonic16** [comment]
You alright with running a debug build of the modloader so I can look further? ~~Totally didn't lose my PDB~~

**Comment by thesupersonic16** [comment]
So I have done some more looking, are you able to screenshot the console window when it crashes? You should see a line like `Writing save file ` right before it crashes. You could attach the game to VS's Debugger if you have VS installed to hold the console.

**Comment by VanillaCold** [comment]
Tried doing that, but the VS debugger seemed to fail to stop it from closing, not sure why.

**Comment by thesupersonic16** [comment]
Using the memory dump, I think I know what function is crashing, can you try this DLL and send me a screenshot of a messagebox or a memory dump if crashed?

[d3d11.zip](https://github.com/thesupersonic16/HedgeModManager/files/10149098/d3d11.zip)

**Comment by VanillaCold** [comment]
![image](https://user-images.githubusercontent.com/35960636/205510514-2394b599-7fd4-4d6b-bf0b-5b9835e8b503.png)

This time it didn't actually crash, though, and even saved after closing a few more identical message boxes

**Comment by thesupersonic16** [comment]
It's concerning how it's blank. Did it show any information?

**Comment by VanillaCold** [comment]
![image](https://user-images.githubusercontent.com/35960636/205511000-60146351-b90d-4559-9646-e11dd24b9927.png)
This is the only stuff that appeared in the debug console.

Strangely enough, I think there weren't actually as many of the dialogue boxes this time.
Maybe the time between saving and me closing the last error has something to do with it, since I installed Sonic Frontiers on a pretty slow drive

**Comment by thesupersonic16** [comment]
Was the dialog window always blank for you? It should look something like this

![image](https://user-images.githubusercontent.com/25761885/205511393-d153bfab-f91e-4cbc-a1ee-f5916c9eeaf5.png)

**Comment by VanillaCold** [comment]
Yes, it was.

**Comment by thesupersonic16** [comment]
I will post a new build later with it printing to the console. What version and build number of Windows you using?

**Comment by thesupersonic16** [comment]
Can you try this DLL and show me the console output?

[d3d11.zip](https://github.com/thesupersonic16/HedgeModManager/files/10150380/d3d11.zip)

**Comment by VanillaCold** [comment]
![image](https://user-images.githubusercontent.com/35960636/206205288-4df5bc81-46c7-4874-9263-1932b81cb79c.png)

**Comment by VanillaCold** [comment]
> I will post a new build later with it printing to the console. What version and build number of Windows you using?

Windows 10, version 21H2, OS build 19044.2251

**Comment by thesupersonic16** [comment]
I have changed how directories are created, can you check if this solves the issue? Please also double check that the folders were automatically created (Do not create them manually)
![image](https://user-images.githubusercontent.com/25761885/206402939-e21dfb63-2556-484d-936b-8d34a2950a00.png)


[d3d11.zip](https://github.com/thesupersonic16/HedgeModManager/files/10183752/d3d11.zip)
