### ISSUE TITLE
Mod Loader Won't Download

### ISSUE THREAD

**Issue by spawnofthestorm** [thesupersonic16/HedgeModManager#542]
I have the latest version downloaded and the application is running fine. It says the Mod Loader has to be downloaded and it won't download. I have tried the nightly and regular release.

**Comment by thesupersonic16** [comment]
Duplicate of #539, which has already been resolved.

**Comment by thesupersonic16** [comment]
Oh actually this might not be a duplicate. Can you explain your issue in more detail, with images if possible?

**Comment by spawnofthestorm** [comment]
> 

When I try to save my mods it says the mod loader isn't downloaded and I need to download it to save the mods. I agree and then for the download pop up the bar stays fully white forever. It never makes any progress.

**Comment by thesupersonic16** [comment]
Does this happen for any other games? like Gens and LW?

**Comment by spawnofthestorm** [comment]
> Does this happen for any other games? like Gens and LW?

I haven't tried it for those games. This is really my first time downloading the mod manager

**Comment by thesupersonic16** [comment]
What game you trying to install mods for?

**Comment by spawnofthestorm** [comment]
> What game you trying to install mods for?

Sonic Frontiers
