### ISSUE TITLE
[Bug] Cant find sonic generations installed from dvd

### ISSUE THREAD

**Issue by T0biasCZe** [thesupersonic16/HedgeModManager#553]
## Describe the issue/bug

When you have Sonic Generations installed from PC-ROM/DVD-ROM, the mod manager cant find the game.
## Expected Behaviour

The mod manager finds the game

**Comment by thesupersonic16** [comment]
All versions of Sonic Generations including the one supplied on the DVDs use Steam. Did you make sure the game is showing up as installed on Steam? Non-Steam releases are not supported.

**Comment by T0biasCZe** [comment]
after install it doesnt appear on steam. and when i manually added it to steam as external game it still didnt show up in h.m.m.
But it appeared in the mod loader when i manually copied the game folder to SteamLibrary\steamapps\common
