### ISSUE TITLE
[SonicFrontiers] "Save and Play" button forces keyboard controls

### ISSUE THREAD

**Issue by mahougomi** [thesupersonic16/HedgeModManager#569]
## Describe the issue/bug
When launching Frontiers from the mod manager, hitting "Save and Play" prevents controllers being detected. Keyboard and mouse input is unaffected. I can still hit save in the mod manager and launch through Steam but this is a bit frustrating for workflow

## Expected Behaviour
"Save and Play" launches the game no differently than from Steam.

## Additional Context
I have never tested whether this happens when the mod loader is not installed to the executable.

I have heard this is a known issue but I'm reporting it on GitHub mostly so it gets closed once someone fixes it

**Comment by mahougomi** [comment]
Apparently someone reported the issue previously and it got closed? Not sure why this happened, it's still a bug...

**Comment by thesupersonic16** [comment]
Enabling use game launcher should make Hedge Mod Manager launch the game the same way as Steam.

**Comment by mahougomi** [comment]
This option fixed the issue for me. Thanks!
