### ISSUE TITLE
[Sonic Generations] Error code 0cx0000142 when loading GCL

### ISSUE THREAD

**Issue by canary-1023** [thesupersonic16/HedgeModManager#57]
When I try playing sonic generations with mods the mod loader enabled, it gives me the error code 0cx0000142. How do I fix this?

**Comment by thesupersonic16** [comment]
Looks like a module not found error code. Do you see `cpkredir.dll` in the `Sonic Generations` directory? And do you have the VC++ Redistributables installed?

For the redistributables, you can get them here and install them in this order: (x64 is not needed, but if you have a 64 bit PC, then install both)
1. [Visual C++ 2019 Redistributable x86](https://aka.ms/vs/16/release/vc_redist.x86.exe)
2. [Visual C++ 2019 Redistributable x64](https://aka.ms/vs/16/release/vc_redist.x64.exe)

**Comment by canary-1023** [comment]
Yes and yes. I don't know what the problem is.

**Comment by thesupersonic16** [comment]
What mods do you have active?

**Comment by canary-1023** [comment]
DiscordGenerations, High Quality Sonic, High-Res HUD, Realistic Gens Sonic, and Longer Blue Trail

**Comment by Sajidur78** [comment]
There is a bug with DiscordGenerations which makes it not work with GCL I recommend disabling the mod or updating it from the GameBanana page

**Comment by canary-1023** [comment]
Can you send me a link?

**Comment by thesupersonic16** [comment]
DiscordGenerations 1.x will NOT work on newer versions of GCL, you will need 2.x

Grab `discordgenerations-24.zip` from [here](https://gamebanana.com/gamefiles/6969)

**Comment by canary-1023** [comment]
Ah, I see. Is that what was causing the issue?

**Comment by canary-1023** [comment]
The issue isn't occurring anymore, the game just launches and shows a black screen and then crashes to desktop. How do I fix this?

**Comment by thesupersonic16** [comment]
Does the game work fine with just DiscordGenerations and Longer Blue Trail?

**Comment by canary-1023** [comment]
Nope.

**Comment by thesupersonic16** [comment]
Does it still work when all mods are disabled?

**Comment by canary-1023** [comment]
No. It doesn't work at all.

**Comment by thesupersonic16** [comment]
There are some things I need you to do to help us find the issue:
1. Try delete the Codes.dat file in your mods folder
2. Send your cpkredir.ini and ModsDb.ini file in a zip file
3. Send a screenshot of your `Sonic Generations` folder

**Comment by canary-1023** [comment]
[zip](https://github.com/thesupersonic16/HedgeModManager/files/4126005/a.zip)
[sonic generations folder](https://user-images.githubusercontent.com/46818515/73325264-d72fb680-421b-11ea-96de-7a043908ff60.PNG)

**Comment by thesupersonic16** [comment]
Not sure if you enabled any mods after you checked if it works with it all off. Can you try remove the ModsDb.ini and then run HMM and right after press Save and play?

That was we can see if the game works on a clean slate.

**Comment by canary-1023** [comment]
That worked,

**Comment by thesupersonic16** [comment]
Sorry for late reply, didn't see the email. Can you try one by one enable the mod and codes you want? and let me know which one starts causing issues.
