### ISSUE TITLE
[Bug] "Fix Empty Messages" code causes Frontiers to crash on boot

### ISSUE THREAD

**Issue by TimerBunneh** [thesupersonic16/HedgeModManager#570]
## Describe the issue/bug
I've tried starting up Sonic Frontiers with the "Fix Empty Messages" code on, but the game does not start up at all. I've gone through the other codes I have enabled, and they all work fine, and it seems that code in particular is the culprit.

## Expected Behaviour
The game was to start and run as normal. Instead, it doesn't open at all.

## Additional Context
Here are the codes I have enabled, all of which work as intended:

- Disable Boost Audio Filter
- Disable Ring Loss
- Infinite Boost Gauge
- Infinite Quick Cyloop Gauge
- Centre Game Window on Launch
- Fix Resolution Resetting On Launch
- Fix Upreel Grip Position
- Disable Challenge Marker Scanner
- Disable Dropped Rings
- Disable Guardian Introductions
- Disable Power Boost Cutscene
- Disable Starfall Cutscene
- Disable Tutorial Messages
- Disable Umbrella Camera Lock-On
- Disable Chromatic Aberration
- Disable Cyberspace CRT Effects
- Disable Framerate Limiter
- Disable Framerate Limiter in Cutscenes
- Disable In-Game Letterboxing
- Force Cyber Space Items on Islands
- Hide Challenge Markers
- Always Hide Mouse Cursor
- Always Run In the Background
- Force Playstation 4 Controller UI
- Hide Boost Gauge
- Disable Forced Weather For Bosses

**Comment by hyperbx** [comment]
I've tested all of the above codes together with Fix Empty Messages and the game boots up successfully - the only crash occurs after completing Cyber Space 1-1 due to Force Cyber Space Objects on Islands, but that's a known issue and a fix is in the works.

Do you have any mods enabled as well?

**Comment by TimerBunneh** [comment]
Hm, must be a mod conflict, then. My bad.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by hyperbx** [comment]
> the only crash occurs after completing Cyber Space 1-1 due to Force Cyber Space Objects on Islands

This issue has been fixed as of commit https://github.com/thesupersonic16/HedgeModManager/commit/ad331ce3f3ab3ba9ddeda65fb5f72e02e606579a, please test again with your current configuration.
