### ISSUE TITLE
[SonicFrontiers] Game crashes on save.

### ISSUE THREAD

**Issue by FlambingoSucks** [thesupersonic16/HedgeModManager#571]
When attempting to save (or, whenever the game auto-saves), Sonic Frontiers (Steam) crashes. This happens regardless of what, if any mods or codes are enabled. Reinstalling the game did not fix this. The only fix is deleting d3d11.dll, rendering the tool inactive.

**Comment by thesupersonic16** [comment]
Thanks for reporting this issue. We are aware of this issue but have not gotten any contact from those who had the issue for testing any potential fixes. Can you please try the attached DLL and confirm if it solves your issue?

[d3d11.zip](https://github.com/thesupersonic16/HedgeModManager/files/10515948/d3d11.zip)
