### ISSUE TITLE
[Bug] Latest development release detected as virus by Avast antivirus

### ISSUE THREAD

**Issue by throwaway1908** [thesupersonic16/HedgeModManager#581]
## Describe the issue/bug
When I try to update the development release version of HedgeModManager, Avast antivirus detects some of it's files as being malicious. 

## Expected Behaviour
Updating HedgeModManager to the latest release version.

**Comment by RagdollClash** [comment]
Mark HedgeModManager as an exception in your anti-virus, sounds like it's hitting a false positive.

**Comment by throwaway1908** [comment]
> Mark HedgeModManager as an exception in your anti-virus, sounds like it's hitting a false positive.

I already knew to do that, but I still thought I'd make you aware of this issue in case your team wants to make some kind of fix for this in a future update :)

**Comment by thesupersonic16** [comment]
We only really ensure we don't get any false positives with Windows Defender, I recommend submitting the exe as a sample so it can get analysed and marked as safe.
