### ISSUE TITLE
[Bug] Sonic colors ultimate, mod loader can't find game even tho i have it

### ISSUE THREAD

**Issue by Droidzeetka14** [thesupersonic16/HedgeModManager#582]
Got the game off steam but the mod loader can't seem to find it or think i have it installed

i have no idea why this is happing and if anyone could help me that would be great

**Comment by RagdollClash** [comment]
Try using the latest development build.

**Comment by Droidzeetka14** [comment]
that worked for some reason it only shows up on the dev release

**Comment by thesupersonic16** [comment]
The game was never out on Steam back when we made the last stable release.

**Comment by Droidzeetka14** [comment]
makes sense it was just released on steam yester day but from what ive played using the loader it works great

**Comment by SaltyKombat** [comment]
> Try using the latest development build.

Where do I find the Dev build?

**Comment by thesupersonic16** [comment]
Select Development where it says `Update Channel` in the Settings tab.
![image](https://user-images.githubusercontent.com/25761885/236264345-0c720fcc-8c93-456b-a837-5cc6b989c56f.png)
