### ISSUE TITLE
HMM not working on Linux in general [Bug] 

### ISSUE THREAD

**Issue by DarkSparkish** [thesupersonic16/HedgeModManager#586]
## Describe the issue/bug
HMM simply won't boot.

## Expected Behaviour
HMM opens up.

## Additional Context
I've been running HMM through SteamTinkerLaunch on my desktop running EndeavourOS since about December, mainly for Sonic Frontiers, which has worked with no issues. Until the start of this year when HMM just refuses to boot. No matter if it's through STL or just launching HMM through Wine in general, it refuses to boot. Not only with Sonic Frontiers, but also with Sonic Generations, which has worked effortlessly to me in the past.

I can boot up Sonic Frontiers with the mods and cheats I've enabled prior to the issue, but I can't launch HMM itself at all. But I can't launch Sonic Generations at all.

**Comment by Shoptalky** [comment]
What's the output when you run HMM through the command line?

**Comment by thesupersonic16** [comment]
Please use the issue #219 for getting/providing help with setting up HMM and its games on Linux.

Closing.
