### ISSUE TITLE
sonic colors not launching when the modloader is present

### ISSUE THREAD

**Issue by pokemansenpai** [thesupersonic16/HedgeModManager#587]
well sonic colors ult isnt launching with the modloader and idk if its denovo or the mod manager

**Comment by thesupersonic16** [comment]
Please provide a description.

**Comment by thesupersonic16** [comment]
Please provide more details like your OS, HMM version, game distribution (Steam/Epic) and any pictures of what you see. Also make sure all mods and codes are disabled when testing the modloader.
