### ISSUE TITLE
Can't get HHM to run on Steam Deck

### ISSUE THREAD

**Issue by spike63995** [thesupersonic16/HedgeModManager#592]
Hi, I have followed instructions to the tee for getting HHM to run on the Steam Deck. Done it a few times, deleted the HMM from the .config folder and retried. Tried to manually use protontricks to install dotnet 40 and 48. And every time I go to load HHM, it just says loading and does nothing. Anything you can suggest I try?

Thanks.

**Comment by thesupersonic16** [comment]
Please use the issue #219 for getting/providing help with setting up HMM and its games on Linux.

Closing.
