### ISSUE TITLE
[Bug] Sonic Colors Ultimate (Steam) does not launch. 

### ISSUE THREAD

**Issue by pastelaura** [thesupersonic16/HedgeModManager#594]
## Describe the issue/bug
Sonic Colors Ultimate (Steam) does not launch through HedgeModManager.

## Expected Behaviour
I was just trying to start Sonic Colors Ultimate (Steam) through HedgeModManager.

## Additional Context
I have tried reinstalling the game and also verify the integrity of the game files. Neither solved the issue.

**Comment by thesupersonic16** [comment]
Can you provide what version of HedgeModManager you are using?

**Comment by pastelaura** [comment]
> Can you provide what version of HedgeModManager you are using?

The latest development version (7.9-0).

**Comment by thesupersonic16** [comment]
Have you tried enabling use game launcher?

**Comment by pastelaura** [comment]
> Have you tried enabling use game launcher?

Yes, and it still doesn't launch.

**Comment by pastelaura** [comment]
> Have you tried enabling use game launcher?

I was wondering if I could also make a code request for Sonic Lost World? UI- Disable HUD.
