### ISSUE TITLE
[Bug] hmm does not launch on steam deck. Wine error

### ISSUE THREAD

**Issue by crimsondeku** [thesupersonic16/HedgeModManager#596]
I followed the steps line by line twice, even watching the video.
When attempting to launch through the terminal, I get the error:
“wine server: using server-side synchronization
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely

HMM does not launch after this error shows. Have tried setting multiple newer proton versions in STL, after using 5.10 for installation.

**Comment by thesupersonic16** [comment]
Please use the issue #219 for getting/providing help with setting up HMM and its games on Linux.

Closing.
