### ISSUE TITLE
[Frontiers]Codes DO NOT work on newest update. 

### ISSUE THREAD

**Issue by AskaLangly** [thesupersonic16/HedgeModManager#599]
![Screenshot 2023-03-22 212854](https://user-images.githubusercontent.com/6183728/227077157-17d114a2-50c5-477d-ba25-c7e8c0e17226.png)
![Screenshot 2023-03-22 212943](https://user-images.githubusercontent.com/6183728/227077160-6636a2e5-372d-4cc5-805e-2c9e1b598621.png)
Tried the following codes after an update right after the Frontiers update dropped.
I have to turn off ALL codes in order for the game to run.
Before the game update, these codes worked.

**Comment by Z-Target** [comment]
I've tried the same thing with a variety of codes and mods. The game will not work with HedgeModManager with the new 1.20 update to Sonic Frontiers

**Comment by hyperbx** [comment]
Update your codes and untick any that are labelled with the `(v1.10)` suffix, these will be fixed individually as soon as possible.

**Comment by RagdollClash** [comment]
Closing because the update *just* came out and we've noted what codes currently don't work.
