### ISSUE TITLE
Can't find Forces

### ISSUE THREAD

**Issue by lavendertheghost** [thesupersonic16/HedgeModManager#6]
Title says all. HedgeModManager seems to be able to work with Forces (As so claimed) however cannot locate it, no matter how close or how far away it is from the exe.

**Comment by thesupersonic16** [comment]
We didn't have Forces support on Releases at the time, Now It should work but only with codes, No File Replacements yet.

https://github.com/thesupersonic16/HedgeModManager/releases/latest

**Comment by thesupersonic16** [comment]
No Reply in a week, Reopen If you still have the issue on the newest version of HedgeModManager, We had Lots of commits pushed.
