### ISSUE TITLE
[Unnamed Game] 

### ISSUE THREAD

**Issue by DanSurasshu** [thesupersonic16/HedgeModManager#60]
At least, there are the error information

HMM Info:
    Version: 7.0-4
    Args: 
    StartDir: D:\Archivos DanKamon\DanKamon Juegos\Sonic Generations\
    Process Level: User
    Game: Unnamed Game

Exception:
    Type: NullReferenceException
    Message: Object reference not set to an instance of an object.
    Source: HedgeModManager
    Function: System.Collections.Generic.Dictionary`2[System.String,System.Object] GetContainer(System.Collections.Generic.Dictionary`2[System.String,System.Object], System.String)
    StackTrace: 
       at HedgeModManager.SteamVDF.GetContainer(Dictionary`2 containers, String name)
       at HedgeModManager.Steam.SearchForGames(String preference)
       at HedgeModManager.App.Main(String[] args)
    InnerException:

**Comment by Sajidur78** [comment]
Could you try running this version of HMM and see if anything is different
[HedgeModManager.zip](https://github.com/thesupersonic16/HedgeModManager/files/4132212/HedgeModManager.zip)

**Comment by DanSurasshu** [comment]
FIXED!!! Thank You,
![Captura de pantalla (2)](https://user-images.githubusercontent.com/38163815/73576833-640b8780-4449-11ea-97c8-5b8a728bfd49.png)

**Comment by ChronoSMP** [comment]
can some one help me i am having the same problem but the new version isn't working

**Comment by RagdollClash** [comment]
Your issue has `Illegal characters in path.` while this issue has `Object reference not set to an instance of an object.`

**Comment by ChronoSMP** [comment]
sorry i am a bit stupid could you please explain what that means thank you
