### ISSUE TITLE
[Bug] Sonic Frontiers not starting unless mod loader is uninstalled after update (Steam Deck)

### ISSUE THREAD

**Issue by onyxlebron** [thesupersonic16/HedgeModManager#600]
## Describe the issue/bug

Frontiers won't start at all on the steam deck if the mod loader is installed after the recent update even if no codes or mods are active.

## Additional Context

The game works as normal if you uninstall the mod loader in the settings tab. I tried using different versions of proton, reinstalling the game but nothing worked. Not sure if the update broke the mod loaders compatibility with linux or something.

**Comment by thesupersonic16** [comment]
Please use the issue #219 for getting/providing help with setting up HMM and its games on Linux.

Closing.
