### ISSUE TITLE
[Frontiers] All mods loaded crash the game after SEGA splash screen

### ISSUE THREAD

**Issue by Z-Target** [thesupersonic16/HedgeModManager#601]
## Describe the issue/bug
Any mod I had tried for Sonic Frontiers would immediately crash the game upon loading the SEGA splash screen. There would be a Command Prompt box before startup containing this text:

[HE2ML] [INFO] Starting HE2ModLoader v1.1.2...
[HE2ML] [DEBUG] Game ID is 1237320
[HE2ML] [DEBUG] SIGSCAN: crifsIoWin_Exists: 140D1A018 (140D1A018)
[HE2ML] [DEBUG] SIGSCAN: crifsIoWin_CreateFile: 140D1A6C4 (140D1A6C4)
[HE2ML] [DEBUG] SIGSCAN: criErr_Notify: 140CFF61C (140CFF61C)

## Expected Behaviour
Before the 1.20 Update to Sonic Frontiers, HedgeModManager would not show a Command Prompt window at all, instead immediately starting the game with the mods applied without issue.

## Additional Context
This happens with every mod I have tried to load. I tried looking through the forums, and saw that a thread of an issue relating to this one had been closed rather quickly. I do hope this issue is resolved soon.

**Comment by RagdollClash** [comment]
These mods will need to update to be compatible with v1.20. Only thing that can be done is waiting for the mod creators to update them.
