### ISSUE TITLE
[Bug] "Disable Dropped Rings" Code Crashes Sonic Frontiers on Launch After 1.20 Update

### ISSUE THREAD

**Issue by BrochachoTheBro** [thesupersonic16/HedgeModManager#603]
## Describe the issue/bug
Launching Sonic Frontiers with the "Disable Dropped Rings" code makes the game fail to launch.

## Expected Behaviour
The game would launch and Sonic would not drop any rings upon taking damage.

## Additional Context
N/A

**Comment by hyperbx** [comment]
Fixed in commit https://github.com/thesupersonic16/HedgeModManager/commit/8a2b0a35cb21075db769a1b9542bcfd151584e24, please update your codes.

**Comment by BrochachoTheBro** [comment]
Tysm
