### ISSUE TITLE
[Bug] Sonic Lost World does not start with any cheats enabled on Steam Deck

### ISSUE THREAD

**Issue by jeffkrull** [thesupersonic16/HedgeModManager#611]
## Describe the issue/bug
I've been trying to get HMM working with the Steam version of Sonic Lost World on my Steam Deck, but am running into issues with at least one mod, and all of the cheats.

I've installed HMM using SteamTinkerLaunch, and so far I've got it working just fine with other games that support it, like Generations, Colors Ultimate, Forces, Frontiers, and Origins. Lost World fails to launch if I have any cheats enabled. I click Save and Play, but nothing happens. If I try to launch through Steam, the Play button just turns to the Cancel button, and then back to the Play button. The same thing happens if I try to start the game with no cheats enabled, and no other mod but DLC Restoration 2.1.1 enabled. 

## Expected Behaviour
The game should load with the cheats (and/or the DLC Restoration mod) enabled.

## Additional Context
My Steam Deck is running the latest OS as of the time of posting, and I'm using the default Proton version for Lost World. I am using the Development channel for HMM. I've started with a fresh install of Lost World from Steam, and I've validated files from within Steam. I have four other mods installed that work just fine: Gamma Correction, Fixed Super Sonic, Lost World Improvement Mod, and Wii U Font. I've tested with all mods and cheats disabled (works), with the four above mentioned mods enabled and no cheats enabled (works), with just DLC Restoration enabled (does not work), and with no mods enabled and any one cheat enabled, like Don't Lose Rings (doesn't work).

**Comment by thesupersonic16** [comment]
At this point of time the development chanel is broken for Linux. I recommend for the time being to move to release.

**Comment by jeffkrull** [comment]
I was going to try and revert to the release build to test and see if it fixed the issue, but when I booted up HMM it prompted me to install version 9f9b044. That version actually fixed the issue with codes in Sonic Lost Worlds, and even fixed the DLC Restoration mod. Not entirely sure why, but that commit seems to have resolved what was wrong.

**Comment by thesupersonic16** [comment]
That commit causing the issue was already known for a little while back and was planned to have it reverted and tested. Since its now been reverted I will now close this issue.
