### ISSUE TITLE
Hedgemod Manager crashing when using "Showin's Momentum Tweaks" mod, or any mod in general on Sonic Frontiers. 

### ISSUE THREAD

**Issue by yoeshii** [thesupersonic16/HedgeModManager#617]
so i downloaded sonic frontiers, with the excited ambition to mod it to be the sonic game i really wanted it to be, yet whenever i use the mod loader for Frontiers, i am met with the Sega logo, then immediate crash, with the window disappearing and everything. what can i do to solve this issue? for reference, i'm on the ASUS Zephyrus G14, with the AMD Radeon 6800s, using the pre-installed ASUS drivers.

**Comment by RagdollClash** [comment]
Showin's Momentum Tweaks hasn't been updated to support Update 1 yet, hence why the game crashes after the SEGA logo. This is not a HMM issue, you'll have to wait for the mod to make an update.

**Comment by yoeshii** [comment]
> Showin's Momentum Tweaks hasn't been updated to support Update 1 yet, hence why the game crashes after the SEGA logo. This is not a HMM issue, you'll have to wait for the mod to make an update.

thank you so much! do you have any other momentum-based mods to suggest to me? i bought this game on steam to play it with momentum involved, since i really disliked the lack of it on my first playthrough on switch. again, thank you for the reply! i thought my computer was just boned lmao
