### ISSUE TITLE
Can't checkmark any boxes 

### ISSUE THREAD

**Issue by TheKaijuGojira** [thesupersonic16/HedgeModManager#62]
In both the codes and settings areas, the only buttons that I can click are the 6 rectangle buttons at the bottom of the screen. The checkmark boxes are blank even after clickig on them. Is this an issue or am I missiing something to turn them on?

**Comment by thesupersonic16** [comment]
The issue was possibly fixed in 2b93d069f2264abb90e929ff1df9eafcfef102ab. Can you please check if the newest version of HedgeModManager has the same issue?

**Comment by TheKaijuGojira** [comment]
The update fixed it. TYSM!

**Comment by thesupersonic16** [comment]
No problem. Sorry for the long wait we forgot to reply.

Closing.
