### ISSUE TITLE
Any way to manually set a game directory?

### ISSUE THREAD

**Issue by BrochachoTheBro** [thesupersonic16/HedgeModManager#628]
HMM hasn't ever detected my Forces install unlike my Generations, Lost World, and Frontiers ones. If there isn't a method that exists, could this be added somehow? Like an "Add Game" option in the game selection dropdown.

**Comment by thesupersonic16** [comment]
You can manually add extra locations to scan using the `ExtraGameDirectories` registry key, but you should be looking into why HMM isn't able to detect the game. Is it in the same Steam library as the other games?

**Comment by BrochachoTheBro** [comment]
I'll try that. I got Forces somewhere that isn't Steam, but I tried moving the directory to my Steam's common folder but had no luck.

**Comment by BrochachoTheBro** [comment]
Late reply but it worked. I'd still recommend you guys look to find an in-app way to add a game manually without having to go into the registry.

**Comment by BrochachoTheBro** [comment]
Late reply but it worked. I'd still recommend you guys look to find an in-app way to add a game manually without having to go into the registry.

**Comment by sdfmnb2314** [comment]
I added the path to `ExtraGameDirectories` but it still hasn't detected my game.

**Comment by thesupersonic16** [comment]
In dev `ExtraGameDirectories` is being phased out. `CustomGames` will be replacing it and its format will be like `Z:\Games\SomeGame\Game.exe|SonicForces|Steam`.


As I said before you should be looking into why HMM isn't able to detect the game. Please locate the game folder and send the main `libraryfolders.vdf` from Steam so I can look into why its not being detected.

**Comment by Sonictchuitio** [comment]
i got frontiers from a discord server, which I then put into steam, but only my file of unleashed recomp is only visible, I can't put any mods into frontiers. how do I fix it?

**Comment by amiko0225** [comment]
> In dev `ExtraGameDirectories` is being phased out. `CustomGames` will be replacing it and its format will be like `Z:\Games\SomeGame\Game.exe|SonicForces|Steam`.
> 
> As I said before you should be looking into why HMM isn't able to detect the game. Please locate the game folder and send the main `libraryfolders.vdf` from Steam so I can look into why its not being detected.

im in the custom games file what do i do next?

**Comment by thesupersonic16** [comment]
It's not a file, also I had already explained how it works. And again you should be looking into why it's not automatically being detected not manually specifying the game.

**Comment by amiko0225** [comment]
> It's not a file, also I had already explained how it works. And again you should be looking into why it's not automatically being detected not manually specifying the game.

got it out of somewhere that is not steam

**Comment by RizzhanSolos** [comment]
> You can manually add extra locations to scan using the `ExtraGameDirectories` registry key, but you should be looking into why HMM isn't able to detect the game. Is it in the same Steam library as the other games?

it doesn't work tho, after opening hedgemod loader all my buttons went grey and I cant use them

**Comment by Ihi-spec** [comment]
Not trying to necro this, but I'm having the same problem. I got the game from the ultimate collection on [Humble](https://www.humblebundle.com/store/sonic-the-hedgehog-ultimate-bundle) and I cant find the `ExtraGameDirectories ` or `CustomGames ` registry key.

**Comment by thesupersonic16** [comment]
> Not trying to necro this, but I'm having the same problem. I got the game from the ultimate collection on [Humble](https://www.humblebundle.com/store/sonic-the-hedgehog-ultimate-bundle) and I cant find the `ExtraGameDirectories ` or `CustomGames ` registry key.

What distribution platform did you download the game from? You should beable to install the game and after reopening HMM it should show up without any registry changes.

**Comment by norumalumilkku** [comment]
> Not trying to necro this, but I'm having the same problem. I got the game from the ultimate collection on [Humble](https://www.humblebundle.com/store/sonic-the-hedgehog-ultimate-bundle) and I cant find the `ExtraGameDirectories ` or `CustomGames ` registry key.

The `CustomGames` registry key is located in
`My Computer\HKEY_CURRENT_USER\SOFTWARE\HEDGEMM`
As @thesupersonic16 stated earlier, the format for the string value registry key is 
`Z:\Games\SomeGame\Game.exe|GameName|Platform`

Where Platform can be None, Steam, Epic, Heroic
The platform option dictates how the game launches. Usually None seems to be fine as that launches the executable directly.
The others launch the games via the platforms respective protocol launch methods.

The possible values for `GameName` are `SonicGenerations, SonicForces, SonicLostWorld, PuyoPuyoTetris2, SonicColorsUltimate, SonicOrigins, SonicFrontiers, ShadowGenerations, UnleashedRecompiled
`
Not sure why this is hidden within an _undocumented_ registry option. Some sort of "Add Custom Game" option would be very useful in the UI.

**Comment by Ihi-spec** [comment]
I solved my problem by going back to an old version of HMM where there was the option to “Add Game” in the drop-down. And after using that, I updated HMM. Thank you for the help tho!

**Comment by Ihi-spec** [comment]
If anyone wants to know the version, it’s 7.13-1.

**Comment by Ozidesk** [comment]
I find it really unpleasant that apparently the "Add Game" option was removed, since I'm on beta 8.0.0 and can't seem to find it. It is not about having the Mod Manager search for everything in a closed ecosystem, because you have people like me. I'm not on Windows, so I can't modify the Registry Key that easily, and I don't buy my games nor Steam, Epic or Heroic. I'll troubleshoot and find what works, but dang, why have such a closed program in the open source community?

**Comment by Kurggg** [comment]
Years later, I'm having the same issue with Sonic Colors Ultimate. I have it on Epic Games, but it's not even being detected. Tried reg edit, didn't work. Tried downgrading, was told the file couldn't be verified.

**Comment by Kurggg** [comment]
> Years later, I'm having the same issue with Sonic Colors Ultimate. I have it on Epic Games, but it's not even being detected. Tried reg edit, didn't work. Tried downgrading, was told the file couldn't be verified.

sorry, correction, it's unable to determine the game from the selected executable.

**Comment by thesupersonic16** [comment]
> Years later, I'm having the same issue with Sonic Colors Ultimate. I have it on Epic Games, but it's not even being detected.

Can you try locate your `LauncherInstalled.dat` file, zip the file and send it here? The file will be in a folder called `UnrealEngineLauncher`, you should beable to find information online on how to find it.
