### ISSUE TITLE
[Bug] Sonic Generations Code "Homing Attack on Boost" Gives Classic Sonic Ability to Dash

### ISSUE THREAD

**Issue by KristalAndStarlight** [thesupersonic16/HedgeModManager#629]
## Describe the issue/bug
When enabling this code (Homing Attack on Boost under gameplay category) classic sonic somehow gains the ability to dash when pressing jump again after jumping, this is especially annoying with special shields because the dash overrides their second jump abilities.

## Expected Behaviour
Homing attack is bound to X/Square button without any other side effects

## Additional Context
Didn't know where to put this since there is no repo for the codes, or at least I haven't found one.

**Comment by KristalAndStarlight** [comment]
thing

**Comment by Sajidur78** [comment]
Move this issue to https://github.com/hedge-dev/hmmcodes

**Comment by KristalAndStarlight** [comment]
Understood 👍
