### ISSUE TITLE
[Bug] Sonic Forces mods not working

### ISSUE THREAD

**Issue by miles86-64** [thesupersonic16/HedgeModManager#631]
## Describe the issue/bug

When loading some Sonic Forces mods (specifically Sonic Forces Free Cam and DiscordForces) they just don't work, a few months ago they still worked but in an update they stopped working

**Comment by RagdollClash** [comment]
Fixed with HE2ModLoader v1.1.4.

**Comment by miles86-64** [comment]
The mods are working again, great job!
![20230603130422_1](https://github.com/thesupersonic16/HedgeModManager/assets/118630356/734adfab-cf23-418e-b2b9-9a63d66602b3)
![20230603130435_1](https://github.com/thesupersonic16/HedgeModManager/assets/118630356/d74bb3fe-b338-483b-9467-4dfc157c6d4f)
![20230603130512_1](https://github.com/thesupersonic16/HedgeModManager/assets/118630356/d990eeda-e3b3-4ed4-9c53-a83a51c97161)
![vlcsnap-forces](https://github.com/thesupersonic16/HedgeModManager/assets/118630356/94403a56-e247-42f5-94f6-74423061d538)
