### ISSUE TITLE
Boss Select causes Hedge Mod Manager to throw exception.

### ISSUE THREAD

**Issue by ToonLink511** [thesupersonic16/HedgeModManager#633]
Is there a way for me to manually fix this?

also just wanna say that I followed the instructions it gave me, I can't make sense of this gobbly gook.

[HMM_Snapshot_00062023160022.txt](https://github.com/thesupersonic16/HedgeModManager/files/11658477/HMM_Snapshot_00062023160022.txt)

**Comment by thesupersonic16** [comment]
Thanks for sending in the report we have removed the broken releases. Also the issue has already been reported in #632, feel free to subscribe to that issue for any updates.

Hedge Mod Manager should now attempt to downgrade to ec642a1.
