### ISSUE TITLE
Crash upon saving or launching game

### ISSUE THREAD

**Issue by Sambammers** [thesupersonic16/HedgeModManager#634]
## Describe the issue/bug

Crash upon saving in HMM and attempting to launch the game
## Expected Behaviour

Game to launch or HMM to save changes.
## Additional Context

[HMM_Snapshot_00062023210107.txt](https://github.com/thesupersonic16/HedgeModManager/files/11659198/HMM_Snapshot_00062023210107.txt)

**Comment by Sambammers** [comment]
Seems that Frontiers is the only title affected from what I can tell.

**Comment by thesupersonic16** [comment]
Thanks for sending in the report, we have now removed the broken releases. Also the issue has already been reported in #632, feel free to subscribe to that issue for any updates.

Hedge Mod Manager should now attempt to downgrade to ec642a1.
