### ISSUE TITLE
[Bug] HedgeModManager crashes trying to save mods in Sonic Frontiers.

### ISSUE THREAD

**Issue by BlakeAtStake** [thesupersonic16/HedgeModManager#635]
## Describe the issue/bug

HedgeModManager crashes when activating the "Save" or "Save & Play" options in Sonic Frontiers. Furthermore, likely related, Sonic Frontiers will not open (even after verifying Steam files).

## Expected Behaviour

I was expecting HMM to save the mods and open Sonic Frontiers- neither happened.

## Additional Context

[HMM_Snapshot_00062023220441.txt](https://github.com/thesupersonic16/HedgeModManager/files/11659240/HMM_Snapshot_00062023220441.txt)

**Comment by thesupersonic16** [comment]
Thanks for sending in the report, we have now removed the broken releases. Also the issue has already been reported in #632, feel free to subscribe to that issue for any updates.

Hedge Mod Manager should now attempt to downgrade to ec642a1.
