### ISSUE TITLE
[Bug] Only Sonic Generations works with Bottles

### ISSUE THREAD

**Issue by All-StarsPixel** [thesupersonic16/HedgeModManager#642]
## Describe the issue/bug

Any game other than Sonic Generations crashes with the loader installed

## Expected Behaviour

Games boot with the loader and some mods/codes installed

## Additional Context

I'm on a Steam Deck and STL didn't work for me. I've tested SG, SF, SO and SCU

**Comment by RagdollClash** [comment]
STL doesn't appear to work anymore, it's best to stick with the Bottles method for setting up HMM. Also, please keep Linux issues to #219.
