### ISSUE TITLE
[Bug] Sonic Frontiers Code "Disable Guardian Music (experimental)" also disables Jukebox

### ISSUE THREAD

**Issue by Fnflol278922** [thesupersonic16/HedgeModManager#643]
## Describe the issue/bug

I noticed that whenever I enabled Disable Guardian Music, it also disables the jukebox, and Elder and Hermit Koco's music when you interact with them. Any idea what causes this?

**Comment by RagdollClash** [comment]
Please use the HMMCodes repo for code issues.

https://github.com/hedge-dev/HMMCodes
