### ISSUE TITLE
[Request] Search + categorise features

### ISSUE THREAD

**Issue by throwaway1908** [thesupersonic16/HedgeModManager#645]
## Describe the issue/bug
Not a bug, just feature requests. I wasn't sure where else to send this. 

## Additional Context

Two features I think HedgeModManager would benefit from is a search function (mainly for the cheat codes section, but it could be useful for already installed mods as well). And an option that allows users to categorise their mods would be very handy. Having a large collection of mods installed can be a bit of a pain to navigate through.

**Comment by Sajidur78** [comment]
HMM Already has this feature. Just use `Ctrl + F` on mods/codes tab.

**Comment by Sajidur78** [comment]
Categories is an interesting one but, should open a different issue for that.

**Comment by throwaway1908** [comment]
> 

Thanks for telling me about the Ctrl + F function. Wasn't aware that HMM already had that implemented. 
As for the categories, I will open a new issue for that one., and thanks for the quick reply.
