### ISSUE TITLE
[Suggestion: Frontiers; Cheats] Extreme Difficulty and Spindash Unlock

### ISSUE THREAD

**Issue by AskaLangly** [thesupersonic16/HedgeModManager#651]
Has anyone come around to find a cheat that allows difficulty switching? Maybe it might be possible to find the Extreme difficulty through that.

Maybe get the spindash unlocked in the same manner as well?

**Comment by RagdollClash** [comment]
There is already a code to unlock Spin Dash. e9c1e08233afbaba5f247e02c85cf4a5bde7b900

**Comment by AskaLangly** [comment]
Okay, I did a code update ~ 17 h ago, and there wasn't. Thank you on that.

What of the difficulty?

**Comment by irrelevantpelican** [comment]
I'm really sorry I'm totally new to Github and don't understand how to do things. I have Hedge Mod manager. I sort of only know how to click on the mods on Game Banana .com and it opens Hedge Mod Manager automatically. How do I use the code listed above to unlock Spindash? Sorry for the noob question.

**Comment by hyperbx** [comment]
Always Unlocked Extreme Difficulty was added as of commit https://github.com/thesupersonic16/HedgeModManager/commit/18fa31100464938827bce7aa45fe744d97ff8e27.
