### ISSUE TITLE
[Bug] Frontiers runs but doesn't open its window with HMM installed

### ISSUE THREAD

**Issue by wagabago** [thesupersonic16/HedgeModManager#653]
## Describe the issue/bug

When I open up Sonic Frontiers with the mod loader installed, the app runs but doesn't open its window, staying only visible in Task Manager
![image](https://github.com/thesupersonic16/HedgeModManager/assets/120038183/d45eef2e-5319-4726-9797-90d2bf08b3a3)

## Expected Behaviour

The game should be opening up its window with all of its mods and codes properly
## Additional Context

The game opens completely fine without the mod loader installed. It uses up a weirdly high amount of memory according to my task manager, too. I tried using the debug console to get more information, but this is all that it shows:
![image](https://github.com/thesupersonic16/HedgeModManager/assets/120038183/d1ec9ddb-9087-4356-bc3a-bd14d6a0f2ea)

**Comment by thesupersonic16** [comment]
Sorry for the long delay.

Appears to be a memory leak. Do you have any files located in `%localappdata%\NeverFinishAnything\CommonLoader\.storage`? if so, can you send the one that says `SonicFrontiers.exe` in it?

**Comment by Jyuruko** [comment]
I've got the same problem. I've entered this %localappdata%\NeverFinishAnything\CommonLoader\.storage and found 2 files. One is called 43e1374a and the other is eb369c16. Is there something that I'm missing? The game is still in the task manager and no windows on sight.

**Comment by thesupersonic16** [comment]
Does any of them say `Name=SonicFrontiers.exe` inside of it?

**Comment by Jyuruko** [comment]
both of them say it

**Comment by thesupersonic16** [comment]
> both of them say it

Can you please send both files in a zip, then delete the files and rerun the game.

**Comment by Jyuruko** [comment]
It worked! Thnx mate!

**Comment by thesupersonic16** [comment]
An update was pushed to attempt to fix the issue. I will be closing this issue, if the issue comes back, please reply back in this issue.
