### ISSUE TITLE
How do I apply this to Sonic Origins plus or can I even do that?

### ISSUE THREAD

**Issue by Ragiroth** [thesupersonic16/HedgeModManager#659]
I want to mod Sonic Origins Plus on my Steam Deck, but I only find guides talking about Frontiers.  When I use this guide I get to the part where I'm copying the code to run Sonic Frontiers in protontricks on the konsole/terminal.  I replace the ID with Sonic Origins's ID, but it just says "command not found" or something.  What am I supposed to do here? Thank you!

**Comment by thesupersonic16** [comment]
We try to keep issues relating to setting up HMM on Linux in #219, please read near the end of the issue and if you still have a question ask it in there.

I would recommend using the Bottles method over others like STL as some has reported it not working.

If you are having issues finding what you need, here are some links that may help get you started.

https://github.com/thesupersonic16/HedgeModManager/issues/219#issuecomment-1618988473 (Manager stage)
https://github.com/thesupersonic16/HedgeModManager/issues/219#issuecomment-1606112899 (Modloader stage)
