### ISSUE TITLE
HedgemodManager crashes

### ISSUE THREAD

**Issue by genesis0428** [thesupersonic16/HedgeModManager#66]
Help. I tried to start HedgeModmanager, but when I started it, an error code has occurred like below.

HMM Info:
    Version: 7.0-4
    Args: 
    StartDir: C:\Program Files (x86)\SEGA\Sonic Generations\
    Process Level: User
    Game: Unnamed Game

Exception:
    Type: NullReferenceException
    Message: Object reference not set to an instance of an object.
    Source: HedgeModManager
    Function: System.Collections.Generic.Dictionary`2[System.String,System.Object] GetContainer(System.Collections.Generic.Dictionary`2[System.String,System.Object], System.String)
    StackTrace: 
       at HedgeModManager.SteamVDF.GetContainer(Dictionary`2 containers, String name)
       at HedgeModManager.Steam.SearchForGames(String preference)
       at HedgeModManager.App.Main(String[] args)
    InnerException: 

I don't know how to fix it. Please help

**Comment by Sajidur78** [comment]
This issue is fixed in [HMM 7.0-5](https://github.com/thesupersonic16/HedgeModManager/releases/tag/7.0-5)
Re-open the issue if the problem persists.
