### ISSUE TITLE
[Bug] Always Allow Boost Damage Objects crashes Frontiers only with one or other mods.

### ISSUE THREAD

**Issue by HeroCoder76** [thesupersonic16/HedgeModManager#660]
## Describe the issue/bug

Only one mod turned on with the Code Always Allow Boost Damage Objects crashes Sonic Frontiers after a Sonic Quote. 
## Additional Context

I first encountered the crash after Sonic mentioned Omega once.

**Comment by HeroCoder76** [comment]
I have to stop playing until someone fixes/modifies the code.

**Comment by HeroCoder76** [comment]
Update: Even with no mods the above code still crashes the game, the same codemaker has also added the extreme difficulty always unlocked. 

Please contact them to fix/modify the code.

**Comment by hyperbx** [comment]
Please provide a crash dump.

If you're using the Disable Telemetry code, go to `%LOCALAPPDATA%\CrashDumps\` and send the latest `SonicFrontiers.*.dmp` file when the game crashes.

If you're not using the Disable Telemetry code, go to `%APPDATA%\SEGA\SonicFrontiers\steam\crashpad_db\reports\` and perform the same steps.

**Comment by HeroCoder76** [comment]
I cant send the Dump.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by hyperbx** [comment]
If you're unable to send a crash dump, then I'll be unable to debug your issue.

If GitHub is limiting the file size, use a third-party service like Google Drive instead.

Also please provide your `ModsDB.ini` file from your mods directory, I don't know what "other mods" you have on otherwise.

**Comment by HeroCoder76** [comment]
That’s what I’ve been thinking.
Ok, I’ll do it

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by HeroCoder76** [comment]
What's your google drive account?

**Comment by hyperbx** [comment]
Upload the crash dump to *your* Google Drive account and create a sharable link that anyone can access.

![image](https://github.com/thesupersonic16/HedgeModManager/assets/34012267/83d8dcaa-df51-49c7-844e-1288fc3f2962)

**Comment by HeroCoder76** [comment]
https://drive.google.com/file/d/1eirGCGPl8AhSDR6Q2lLO44eA0_m7fQsM/view?usp=drive_link
https://drive.google.com/file/d/1e4h4JP-LrDEkHMkXy8PUn2MbZv6LZNOG/view?usp=drive_link
Here are the links!

**Comment by hyperbx** [comment]
You didn't set the permissions to public, as I requested.

Make sure `Anyone with the link` is the selected option for file sharing.

![image](https://github.com/thesupersonic16/HedgeModManager/assets/34012267/c230ea7e-c611-4ddd-be7d-72ea6a123816)

**Comment by HeroCoder76** [comment]
https://drive.google.com/file/d/1e4h4JP-LrDEkHMkXy8PUn2MbZv6LZNOG/view?usp=drive_link
https://drive.google.com/file/d/1eirGCGPl8AhSDR6Q2lLO44eA0_m7fQsM/view?usp=drive_link
Try these now.

**Comment by hyperbx** [comment]
I haven't been able to reproduce this crash with the mods and codes you have enabled, and the source of the crash from the minidump is uncertain.

The only thing I can think of that could potentially be a problem is the `Forces Sonic with animations` mod, as it hasn't been updated for about five months apparently, and there are new assets in Sonic Frontiers v1.30 that aren't present within that mod, which could cause some problems.

Despite that, the game seems stable with your configuration. I'd suggest verifying your game data through Steam in the event that something went wrong with your game files.

**Comment by HeroCoder76** [comment]
Nope, Still Crashing even with or without mods installed.
look into these new files.
https://drive.google.com/file/d/1YMzGVEcWL4u9Vl8TAW94z3z3L8rbDfAr/view?usp=sharing
https://drive.google.com/file/d/1ZuzPQOniHlXs-SsD960nb49ndqObkMKC/view?usp=sharing

**Comment by HeroCoder76** [comment]
Here's one more crash dump.
https://drive.google.com/file/d/117pYbQdJI0rl9Fg92vscyQwuzG2YjILD/view?usp=sharing

**Comment by HeroCoder76** [comment]
I still see no fix on this code,

I'm really getting sick of this... >:(

**Comment by HeroCoder76** [comment]
> I haven't been able to reproduce this crash with the mods and codes you have enabled, and the source of the crash from the minidump is uncertain.

It was only the Boost Damage Objects code. After a Monologue, the game shuts down.

> The only thing I can think of that could potentially be a problem is the `Forces Sonic with animations` mod, as it hasn't been updated for about five months apparently, and there are new assets in Sonic Frontiers v1.30 that aren't present within that mod, which could cause some problems.

Tried it without that mod and others and it still crashes.

> Despite that, the game seems stable with your configuration. I'd suggest verifying your game data through Steam in the event that something went wrong with your game files.

Tried that, didn't work.

**Comment by HeroCoder76** [comment]
It has been 6 days and no one fixed this!?
here is my updated crash dump.
https://drive.google.com/file/d/11TqkWSHtB5ZsFSuInAmpLBNbp9Ky7NtZ/view?usp=sharing

**Comment by HeroCoder76** [comment]
Here is a new Crash Dump and a Mod Ini list to go with it.

https://drive.google.com/file/d/1QlKCM3ZF5oSkYXKDJ08fau4raLNHJLyW/view?usp=sharing
https://drive.google.com/file/d/1X0EV32GCcl_-OHakVxpr-SkU4fDQgq7y/view?usp=sharing

**Comment by HeroCoder76** [comment]
Here are my pc specs, what do you think?
Device name	DESKTOP-987QJVA
Processor	Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz   3.30 GHz
Installed RAM	16.0 GB
Device ID	729EE6FC-80C0-47C9-9603-D3F097A792A5
Product ID	00330-50000-00000-AAOEM
System type	64-bit operating system, x64-based processor

Also, this is becoming unacceptable, you devs helping out other people on this forum but not me.

**Comment by HeroCoder76** [comment]
This Dump is from Extreme Mode New Game. It still crashes.
https://drive.google.com/file/d/10_c3cksFiWcjfwETSO5cBddgLwgS4fER/view?usp=sharing
https://drive.google.com/file/d/1pUPbxL9mUubGnMN-eBRZbdKM9JALdf0H/view?usp=sharing

**Comment by HeroCoder76** [comment]
Hello! anyone here?!

**Comment by LegoLoco7** [comment]
You seem young. Also, I don't know whether you actually have a GPU or not, but if you don't, then I have no idea how you're running Sonic Frontiers in the first place. I get the feeling this is an issue with your PC.

**Comment by HeroCoder76** [comment]
I'm sorry for my behavior.
Will someone modify the code to for CPU compatibility?

**Comment by LegoLoco7** [comment]
It's... not that simple.

**Comment by RagdollClash** [comment]
Please use the HMMCodes repo for code issues.

https://github.com/hedge-dev/HMMCodes
