### ISSUE TITLE
[Bug] Sonic Frontiers runs in background and crashes if mod loader is installed

### ISSUE THREAD

**Issue by YousifAlkhalaf** [thesupersonic16/HedgeModManager#667]
## Describe the issue/bug
After beating the final boss on my save file, when I try to use mods through HMM, the game runs in the background according to Task Manager, fills up memory, causes the computer to freeze for a bit, then crashes.

This happens regardless of what mods/codes are enabled and even when the mod loader is disabled in settings.

The only way Frontiers runs successfully is if the mod loader is entirely uninstalled.

## Expected Behaviour
Run the game with mods

## Additional Context
Debug console only shows the Game's ID and then reports nothing else.

**Comment by YousifAlkhalaf** [comment]
I found a fix! I deleted the d3d11.dll file in my Sonic Frontiers game directory, and everything works now.

**Comment by thesupersonic16** [comment]
Thanks for letting us know of the issue. This appears to be the same issue reported in #653. Please check that issue as I will be closing this one for being a duplicate.
