### ISSUE TITLE
Trying to use HMM throws an exception when trying to play Frontiers

### ISSUE THREAD

**Issue by SFMG2001** [thesupersonic16/HedgeModManager#668]
Hello The most recent HMM update now throws an exception error when trying to launch the game with anything installed, codes or mods or both doesnt matter Hedgemodmanager throws an exception regardless. looking at the error it throws seems it's looking for "Sonic" in some context but can't find it in the missing directory "E:\Git\hedgemodmanager\HedgeModManager\CodeProvider.cs:line113"
"E:\Git\hedgemodmanager\HedgeModManager\CodeProvider.cs:line71"

seems like I can't play the game with HMM installed so Imma just play something else

here is the pastebin where I've saved the error
https://pastebin.com/KZSCBSQT

**Comment by Sajidur78** [comment]
@SFMG2001 seems like there's an  error in one of the codes you're using, try updating community codes

**Comment by SFMG2001** [comment]
sadly I have done that multiple times HMM just says all codes are up to date

I don't even have anything under "incompatible (1.30)" enabled.

I'm completely at a loss I've disabled all codes still happens. disabled all mods alongside that still happens. I uninstall the modloader from the Game's Executable and it runs so I'm at a loss here.

**Comment by Sajidur78** [comment]
Can you upload a HMM snapshot? Press Shift+F1 on the main page and upload the generated file.

**Comment by SFMG2001** [comment]
sure here it is

[HMM_Snapshot_00072023080421.txt](https://github.com/thesupersonic16/HedgeModManager/files/12110915/HMM_Snapshot_00072023080421.txt)

here it is.

**Comment by Sajidur78** [comment]
You appear to have some codes enabled, disable "Super Stomp" and it'll save properly.

**Comment by SFMG2001** [comment]
ah really?

okay I'll try it

**Comment by SFMG2001** [comment]
omg thank you! it worked it even started the game your the best!

**Comment by Sajidur78** [comment]
The code has been fixed on [cac120b](https://github.com/thesupersonic16/HedgeModManager/commit/cac120b2f5ac836365b58d965813e371826bb486). You can enable super stomp back again after updating community codes.
