### ISSUE TITLE
[Bug] One-click install fails if the program is already running

### ISSUE THREAD

**Issue by OrionNavattan** [thesupersonic16/HedgeModManager#669]
## Describe the issue/bug
Surprised this hasn't been reported, since this initially led me to believe the feature was completely broken.

When attempting to install or update a mod using the one-click install feature or otherwise using a hedgemmrangers URL, the installation or update outright fails if the main program is already running. The instance of the program that handles such URLs launches, the expected UI prompts all appear, the mod is downloaded, and appears to complete successfully, but the install/update does not actually take effect. 

## Expected Behaviour
The program should be able to handle hedgemmrangers URLs in all instances, including if it's already running.

## Additional Context
While I'm not a high-level programmer by any means, my guess would be that the special instance of the program that's launched to handle hedgemmrangers URLs might not be aware that the main program is already running.

**Comment by thesupersonic16** [comment]
So installation works perfectly fine if you close the current instance then run the one-click?

**Comment by OrionNavattan** [comment]
Yes. In fact, after looking more closely, the issue only occurs if the main program is running when the download is complete. If you launch the one-click while the main program is running, but close it before starting the download, the install will complete successfully.

**Comment by OrionNavattan** [comment]
Not sure when, but it appears this bug has been fixed. :>
