### ISSUE TITLE
[Bug] Localization Bug: String ID [SettingsUIUpdateCodesOnLaunch] does not change with the switching of language settings

### ISSUE THREAD

**Issue by at-wr** [thesupersonic16/HedgeModManager#671]
## Describe the issue/bug
String ID [SettingsUIUpdateCodesOnLaunch] does not change with the switching of language settings

## Expected Behaviour
While changing the Language settings in Settings tab, the Localization strings should match the chosen language.

## Additional Context
Images: 
![image](https://github.com/thesupersonic16/HedgeModManager/assets/45558679/6ef14cf8-6baf-45ca-8521-66fa8070d6cd)
![image](https://github.com/thesupersonic16/HedgeModManager/assets/45558679/41a9fd29-0cf7-475c-9b25-19d66dc8d234)
![image](https://github.com/thesupersonic16/HedgeModManager/assets/45558679/4dbe9c89-1dfb-4517-9383-5228c248271c)

**Comment by at-wr** [comment]
Additional images:
![image](https://github.com/thesupersonic16/HedgeModManager/assets/45558679/1f395826-a098-420d-ae1e-fc92e18abab7)
![image](https://github.com/thesupersonic16/HedgeModManager/assets/45558679/58f880c9-19e1-45fd-b567-7d3554138bdf)

**Comment by thesupersonic16** [comment]
I cannot reproduce this issue.

EDIT: My bad, I may have to look into this further, please ignore my old message I had removed.

**Comment by thesupersonic16** [comment]
Yeah cannot reproduce, it is appearing just fine on my end. Maybe you have an old language file. Still my old point of zh-TW being old is true.

**Comment by at-wr** [comment]
Well it seems that this problem only appears on the Release channel
After switching to Development channel, the issue does not appear any more.

Btw, this is zh_CN, not zh_TW lol
![image](https://github.com/thesupersonic16/HedgeModManager/assets/45558679/4cce4828-3e87-4e9e-9b2a-60929334e7ec)

**Comment by thesupersonic16** [comment]
> Btw, this is zh_CN, not zh_TW lol

Yeah my bad, I saw one missing the line, and I see moonrunes, so I think they are the same.

> Well it seems that this problem only appears on the Release channel

The release version might have an older version of the translation, which could be missing the changes, also the Japanese translation was always missing the line.

So it appears what I said wrong was mixing up the two Chinese lol

**Comment by thesupersonic16** [comment]
Anyways I will see if I can get anyone to review your newest PR.
