### ISSUE TITLE
cpkredir.ini not automatically created when not detected

### ISSUE THREAD

**Issue by slashiee** [thesupersonic16/HedgeModManager#7]
Why doesn't it do this at all? It should create it when it detects that it's not there.

**Comment by thesupersonic16** [comment]
You should by supplying the file if you are using the Appveyor version, Adding the file to the exe would be a good idea.

**Comment by thesupersonic16** [comment]
HedgeModManager now comes with cpkredir.ini, So this shouldn't be an issue anymore, Reopen if it continues.
