### ISSUE TITLE
[Suggestion] [Frontiers] 60 FPS Cutscenes Code

### ISSUE THREAD

**Issue by BrochachoTheBro** [thesupersonic16/HedgeModManager#709]
I KNOW there's already the "Disable Framerate Limiter in Cutscenes" code, but I feel like this would be a code better paired with the global "Disable Framerate Limiter" code to remedy issues such as audio desync and the semifinal Wyvern QTE stall bug (I remember hearing that the QTE plays out like normal if you don't allow the game to go over 60FPS, this could be the case for other issues the code brings too).

**Comment by DeaTh-G** [comment]
Codes for HedgeModManager now have a new home at: https://github.com/hedge-dev/HMMCodes. If the issue/suggestion is still relevant please open an issue on that repository as code related issues are no longer being tracked on the main HedgeModManager repository.

Thank you, and sorry for the inconvenience.
