### ISSUE TITLE
Uh...Is this only occurs with me?

### ISSUE THREAD

**Issue by genesis0428** [thesupersonic16/HedgeModManager#71]
When I played Unleashed Project mod, I sometimes change the scene effect file in #stage.ar file from adventure pack or Original Sonic Unleashed. But I realized that changes does not work because sonic's colors didn't changed definitely. Before I knew HMM, I used it very well with SonicGMI and it worked well. 

I tried many times like installing HMM or changing scene effect file, but the changes did not applied. I don't know what is the reason. Can you help me please?

**Comment by thesupersonic16** [comment]
I don't think this is a bug with HMM at all. Did you make sure GCL is installed? GCL is needed to load up CPKREDIR which that will load up all your mods.

**Comment by genesis0428** [comment]
You mean Generations Code loader, right? Well, because I'm on outside so I cannot confirm right now. But I used various cheats from HMM code until I found this problem, so maybe I can say GCL is installed properly. I will check it later when I get back home and will leave a comment again.

**Comment by thesupersonic16** [comment]
Well it must be a issue with your `mod.ini`. Many mods were incorrectly written and relied on a bug in CPKREDIR. Can you also make sure your first include points to `.` ?

**Comment by genesis0428** [comment]
Um...sorry but can you explain what is the meaning of your last word  'Can you also make sure your first include points to . ?' easily??

**Comment by thesupersonic16** [comment]
Can you make sure your file looks something like this
```ini
[Main]
IncludeDir0="."
IncludeDirCount=1
```

**Comment by genesis0428** [comment]
Ah I got it. I will check it as soon as I get home and leave a comment. Thank you.

**Comment by genesis0428** [comment]
I've founded what was the problem. It's not a problem with HMM, but it was with fxpipeline mod. I handled it and it works correctly now. Thanks. :)
