### ISSUE TITLE
Mod manager detected as virus (Trojan:Win32/AgentTesla!ml) on windows defender [Bug] 

### ISSUE THREAD

**Issue by sonicdemo** [thesupersonic16/HedgeModManager#716]
## Describe the issue/bug

After i tried to update the mod manager, a pop up from windows defender popped up saying "Threats detected" and i put it to quarantine. Then i checked the mod manager and it still stayed on the old version (03.09.2023) because of the manager being deleted by defender
## Expected Behaviour

Mod manager should update normally without windows defender detecting it
## Additional Context

Happens after the recent commit.

**Comment by Sajidur78** [comment]
Not much we can do from HMM's side. Microsoft  sometimes flags HMM as a false positive. I'll try submitting a sample to them.
