### ISSUE TITLE
Anti-Virus detecting HedgeModManager as Malware

### ISSUE THREAD

**Issue by TendTheMemeGuy** [thesupersonic16/HedgeModManager#72]
Almost everytime I download hedgemod manager, without disabling the kaspersky anti-virus it will ALWAYS delete it.

**Comment by thesupersonic16** [comment]
Its a false positive. dw HedgeModManager is safe. You can check yourself as the code is all public.

I guess the best I can help you is to find a way to add it to the exceptions list.
