### ISSUE TITLE
[SonicOrigins] 

### ISSUE THREAD

**Issue by MegAmi24** [thesupersonic16/HedgeModManager#733]
This is a separate PC from my regular setup. Error seems to happen regardless of active mods or codes. HMM exe filepath is `C:/Stuff/HedgeModManager.exe`.

[HMM_Snapshot_00092023091239.txt](https://github.com/thesupersonic16/HedgeModManager/files/12661766/HMM_Snapshot_00092023091239.txt)

HMM Info:
```
    Version: 7.10-3
    Args: 
    StartDir: C:\Program Files (x86)\Steam\steamapps\common\SonicOrigins\build\main\projects\exec\
    Process Level: User
    Game: Sonic Origins
    GameInstall: Sonic Origins
    Update Status: Up To Date
```

Exception:
```
    Type: Win32Exception
    Message: The system cannot find the file specified
    Source: System
    Function: Boolean StartWithShellExecuteEx(System.Diagnostics.ProcessStartInfo)
    StackTrace: 
       at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
       at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
       at HedgeModManager.MainWindow.StartGame() in F:\Git\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 677
       at HedgeModManager.MainWindow.<SaveConfig>d__54.MoveNext() in F:\Git\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 1002
    InnerException: 
```

**Comment by thesupersonic16** [comment]
> Failed to compute game hash. Could not find file 'C:\Program Files (x86)\Steam\steamapps\common\SonicOrigins\build\main\projects\exec\SonicOrigins.exe'.

The game is missing?

> HMM exe filepath is C:/Stuff/HedgeModManager.exe

Report shows you also have `hedgemodmanager.exe` in the exec folder. Just want to be sure you didn't confuse it.

Can you confirm if the game exe exists? HMM shouldn't even beable to select the game with it missing, possible it got moved or deleted after you started HMM.

**Comment by MegAmi24** [comment]
Oh, Origins wasn't installed on this system, I don't remember uninstalling it and Steam said it was installed (it showed the Play button) so I thought it was installed.
Also yeah there was an older HMM exe in the exec folder, apparently I also forgot I already installed HMM before I uninstalled Origins.
