### ISSUE TITLE
Sonic colors don't boot on steam deck

### ISSUE THREAD

**Issue by KokkichiOma** [thesupersonic16/HedgeModManager#738]
I tryed to mod sonic colors ultimate on steam deck. I menaged to instal hmm, but i can't open game. I tryed mscoree.dll and dotnet48 methods. 
Turning off mod loader don't make this run.
Sonic generarions mods are working.

**Comment by wof8317** [comment]
try clearing the proton files, either through the game entry on gaming mode, or manually deleting the 2055290 folder from the compatdata directory in your steam directory. Either way, you will need to run the game at least once to recreate the deleted folder. Then run the mod manager to make it, how do I say it, work it's magic.

**Comment by DeaTh-G** [comment]
Please report Linux/Steam Deck issues to #219.
