### ISSUE TITLE
[Sonic Generations] (Super Mario Generations and Real Tails Mod not loading)

### ISSUE THREAD

**Issue by SykkNyzz** [thesupersonic16/HedgeModManager#74]
![2020-02-28 12_29_54-Window](https://user-images.githubusercontent.com/33635415/75576927-81227e80-5a26-11ea-9ae3-2c1072dba80a.png)
![2020-02-28 12_30_48-SEGA - Sonic Generations](https://user-images.githubusercontent.com/33635415/75576928-81bb1500-5a26-11ea-888d-834c2e380881.png)
![2020-02-28 12_32_17-Window](https://user-images.githubusercontent.com/33635415/75576931-82ec4200-5a26-11ea-885e-abdb7ef453d5.png)
Trying to get these to load (I have the mods in their proper folder) but it isn't working

**Comment by SykkNyzz** [comment]
![2020-02-28 12_36_07-Hedge Mod Manager (7 0-7) - Sonic Generations](https://user-images.githubusercontent.com/33635415/75577144-f8581280-5a26-11ea-8a4d-5c6b86087d12.png)

**Comment by thesupersonic16** [comment]
Not a HedgeModManager bug. Closing.. 

Note to this issue, Most/All of Daku Neko and UltimateDarkman mods contain a malformed mod.ini file which is incompatible with the newest version of CPKREDIR. Right clicking it and Pressing Edit mod then OK, may fix this issue.

**Comment by SykkNyzz** [comment]
How would I go about doing that?

Never mind, that made it work perfectly. Thank you so much.

Is there a way to add that instruction to the next update?

**Comment by thesupersonic16** [comment]
Not very sure. Really the modders should be fixing the issue, not relying on HMM to do it.
