### ISSUE TITLE
"SettingsUICheckCLUpdate" - code loader instead of mod loader(?)

### ISSUE THREAD

**Issue by MichMajster** [thesupersonic16/HedgeModManager#743]
Shouldn't line 104 "<system:String x:Key="SettingsUICheckCLUpdate"      >Automatically check for mod loader updates</system:String>" refer to code loader instead of mod loader?

**Comment by RagdollClash** [comment]
It used to say code loader but was changed to mod loader since it applied to both. (https://github.com/thesupersonic16/HedgeModManager/commit/4e0282c902307c073ac2a484e8b86b0a85902671)

Additionally, the last 2 code loaders will be made obsolete once HE1ML makes it into a release build.

**Comment by MichMajster** [comment]
Oh, alright! Thank you.
