### ISSUE TITLE
[Bug] Always unlocked spindash not working after latest Update

### ISSUE THREAD

**Issue by irrelevantpelican** [thesupersonic16/HedgeModManager#746]
## Describe the issue/bug

Sonic Frontiers - Always unlocked spindash doesn't seem to work anymore

## Expected Behaviour

Spindash was working before

## Additional Context

Could be related to the update that came out yesterday

**Comment by DeaTh-G** [comment]
Codes for HedgeModManager now have a new home at: https://github.com/hedge-dev/HMMCodes. If the issue/suggestion is still relevant please open an issue on that repository as code related issues are no longer being tracked on the main HedgeModManager repository.

Thank you, and sorry for the inconvenience.

PS: The update just came out and codes are under investigation for compatibility, please express some patience as codes get updated.
