### ISSUE TITLE
[Bug]  Sonic Frontiers - Crash while using the "Disable In-game Letterboxing" code

### ISSUE THREAD

**Issue by Qhn-bncyqy** [thesupersonic16/HedgeModManager#747]
## Describe the issue/bug
Disabling in game letterboxing crashes the game on startup

## Expected Behaviour
Sonic Frontiers should boot up as normal

## Additional Context
Probably the latest update broke it, as I tested a couple weeks ago and it worked fine, though I found it weird nobody has submitted this yet and I find it very hard to be just my PC

**Comment by RagdollClash** [comment]
Please use the HMMCodes repo to report issues with codes: https://github.com/hedge-dev/HMMCodes.

Additionally, Update 3 *just* came out last night. Give it time for the codes to be fixed.
