### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by CODEX0827** [thesupersonic16/HedgeModManager#749]
[sonic frontiers] the game run poorly when the code "retain velocity from bounce" is enabled With the new characters specifically

**Comment by DeaTh-G** [comment]
Codes for HedgeModManager now have a new home at: https://github.com/hedge-dev/HMMCodes. If the issue/suggestion is still relevant please open an issue on that repository as code related issues are no longer being tracked on the main HedgeModManager repository.

Thank you, and sorry for the inconvenience.
