### ISSUE TITLE
[Bug] [SonicFrontiers] Game crashes when I manually load a save file

### ISSUE THREAD

**Issue by Shadowfan81** [thesupersonic16/HedgeModManager#751]
## Describe the issue/bug

The game crashes when I manually load a save file while using codes.

## Expected Behaviour

The game shouldn't crash on manual load.

## Additional Context

Codes used (tried having only one active at once) : 
- Patch "[Amy] Disable Card Spin Boost Transition" in "Animation" by "Hyper"
- Patch "[Knuckles] Disable Gliding Transition" in "Animation" by "Hyper"
- Patch "[Knuckles] Disable Stomp Transition" in "Animation" by "Hyper"
- Patch "[Tails] Disable Cyclone Transition" in "Animation" by "Hyper"
- Patch "[Tails] Disable Stomp Transition" in "Animation" by "Hyper"
- Code "Character Swapper (experimental)" in "Gameplay" by "Hyper, Skyth & Gordon Ramsay"

**PS:** If it's not the right place to report this bug, would you happen to know how I can contact the codes author ?

**Comment by DeaTh-G** [comment]
Codes for HedgeModManager now have a new home at: https://github.com/hedge-dev/HMMCodes. If the issue/suggestion is still relevant please open an issue on that repository as code related issues are no longer being tracked on the main HedgeModManager repository.

Thank you, and sorry for the inconvenience.
