### ISSUE TITLE
Physics Codes Break Frontiers 1.40 [Bug] 

### ISSUE THREAD

**Issue by RinMaru** [thesupersonic16/HedgeModManager#754]
On the first island when you active the dialog "Thats just begging to be climbed, imagine the View" all movement controls are locked. I had Reduced homing delay and tighter drop dash and jump rotation enabled. I tried narrowing it down to the 3 but the issue never stopped unless i had them disabled period.

**Comment by DeaTh-G** [comment]
Codes for HedgeModManager now have a new home at: https://github.com/hedge-dev/HMMCodes. If the issue/suggestion is still relevant please open an issue on that repository as code related issues are no longer being tracked on the main HedgeModManager repository.

Thank you, and sorry for the inconvenience.
