### ISSUE TITLE
[Bug] Editing a mod removes include dirs from the ini

### ISSUE THREAD

**Issue by mahougomi** [thesupersonic16/HedgeModManager#756]
As the title says, I was editing a mod (for Sonic Frontiers, but I don't know whether it's game-specific) to bump the version number. Lo and behold, I load the mod, only to find that one of the include dirs is being ignored - I check the ini just to be safe, and the second include dir has vanished from the ini. I was able to manually edit the ini to fix this problem since I had an older mod version on hand, so it seems to just be directly related to the edit mod window in HMM.

I'm on the development channel, the window title says 7.11-1-a8e2a7d. If this bug has already been noticed and fixed then I apologize for the inconvenience

**Comment by thesupersonic16** [comment]
Can you please send the mod.ini file in question?
