### ISSUE TITLE
[SonicOrigins] Constant error compiling codes

### ISSUE THREAD

**Issue by woodmanisnicemid** [thesupersonic16/HedgeModManager#757]
I have been trying to install 3 mods for Sonic Origins, and they straight up error every time despite me following the install instructions perfectly. I'm on the latest version of the manager, using the latest versions of the mods, with community codes updated. I even put the decompiled source code into my Origins Steam folder for Sonic 1, 2, and CD. The mods I am currently trying to install are [Fix timing and restore SFX for CD ending,](https://gamebanana.com/mods/387296) [Original remaster music pack,](https://gamebanana.com/sounds/69806) and [Original SFX pack.](https://gamebanana.com/sounds/61847) The restored CD ending mod worked perfectly fine for me in the past, but now ever since I deleted the old version and updated it, it doesn't work anymore. I have never used the remaster music or SFX mods before, so they're the latest version. The mod manager keeps telling me to attach the folder below on here.
[HMM_Snapshot_00102023143916.txt](https://github.com/thesupersonic16/HedgeModManager/files/12849396/HMM_Snapshot_00102023143916.txt)

This is the error I get from the mod manager whenever I try to launch Sonic Origins:
HMM Info:
    Version: 7.11-1
    Args: 
    StartDir: C:\Program Files (x86)\Steam\steamapps\common\SonicOrigins\build\main\projects\exec
    Process Level: User
    Game: Sonic Origins
    GameInstall: Sonic Origins

Exception:
    Message: Error Compiling Codes
    - Sonic CD - Fix timing and restore SFX for CD Ending\Clear CD Credits
        Error @(2,33) CS0103: The name 'Reflection' does not exist in the current context
        Error @(8,1) CS0103: The name 'RFL_SET_PARAM' does not exist in the current context
        Error @(8,42) CS0103: The name 'stringData' does not exist in the current context

    - Original Remaster SFX Pack\Original Remaster SFX Pack RFL Edits
        Error @(2,25) CS0103: The name 'Reflection' does not exist in the current context
        Error @(6,1) CS0103: The name 'RFL_SET_PARAM' does not exist in the current context
        Error @(6,34) CS0103: The name 'm_RetroSfxSonic2' does not exist in the current context
        Error @(7,1) CS0103: The name 'RFL_SET_PARAM' does not exist in the current context
        Error @(7,34) CS0103: The name 'm_RetroSfxSonicCD' does not exist in the current context

    - Original Remaster Music Pack\Original S1/S2 Remaster Fast Music Speeds
        Error @(2,25) CS0103: The name 'Reflection' does not exist in the current context
        Error @(9,1) CS0103: The name 'RFL_SET_PARAM' does not exist in the current context
        Error @(9,34) CS0103: The name 'm_RetroMusicSonic1' does not exist in the current context
        Error @(11,1) CS0103: The name 'RFL_SET_PARAM' does not exist in the current context
        Error @(11,34) CS0103: The name 'm_RetroMusicSonic1' does not exist in the current context
        Error @(13,1) CS0103: The name 'RFL_SET_PARAM' does not exist in the current context
        Error @(13,34) CS0103: The name 'm_RetroMusicSonic1' does not exist in the current context
        Error @(15,1) CS0103: The name 'RFL_SET_PARAM' does not exist in the current context
        Error @(15,34) CS0103: The name 'm_RetroMusicSonic1' does not exist in the current context
        Error @(17,1) CS0103: The name 'RFL_SET_PARAM' does not exist in the current context
        Error @(17,34) CS0103: The name 'm_RetroMusicSonic1' does not exist in the current context
        Error @(19,1) CS0103: The name 'RFL_SET_PARAM' does not exist in the current context
        Error @(19,34) CS0103: The name 'm_RetroMusicSonic1' does not exist in the current context
        Error @(21,1) CS0103: The name 'RFL_SET_PARAM' does not exist in the current context
        Error @(21,34) CS0103: The name 'm_RetroMusicSonic1' does not exist in the current context
        Error @(26,1) CS0103: The name 'RFL_SET_PARAM' does not exist in the current context
        Error @(26,34) CS0103: The name 'm_RetroMusicSonic2' does not exist in the current context
        Error @(28,1) CS0103: The name 'RFL_SET_PARAM' does not exist in the current context
        Error @(28,34) CS0103: The name 'm_RetroMusicSonic2' does not exist in the current context
        Error @(30,1) CS0103: The name 'RFL_SET_PARAM' does not exist in the current context
        Error @(30,34) CS0103: The name 'm_RetroMusicSonic2' does not exist in the current context
        Error @(32,1) CS0103: The name 'RFL_SET_PARAM' does not exist in the current context
        Error @(32,34) CS0103: The name 'm_RetroMusicSonic2' does not exist in the current context
        Error @(34,1) CS0103: The name 'RFL_SET_PARAM' does not exist in the current context
        Error @(34,34) CS0103: The name 'm_RetroMusicSonic2' does not exist in the current context
        Error @(36,1) CS0103: The name 'RFL_SET_PARAM' does not exist in the current context
        Error @(36,34) CS0103: The name 'm_RetroMusicSonic2' does not exist in the current context
        Error @(38,1) CS0103: The name 'RFL_SET_PARAM' does not exist in the current context
        Error @(38,34) CS0103: The name 'm_RetroMusicSonic2' does not exist in the current context
        Error @(40,1) CS0103: The name 'RFL_SET_PARAM' does not exist in the current context
        Error @(40,34) CS0103: The name 'm_RetroMusicSonic2' does not exist in the current context
        Error @(42,1) CS0103: The name 'RFL_SET_PARAM' does not exist in the current context
        Error @(42,34) CS0103: The name 'm_RetroMusicSonic2' does not exist in the current context
        Error @(44,1) CS0103: The name 'RFL_SET_PARAM' does not exist in the current context
        Error @(44,34) CS0103: The name 'm_RetroMusicSonic2' does not exist in the current context
        Error @(46,1) CS0103: The name 'RFL_SET_PARAM' does not exist in the current context
        Error @(46,34) CS0103: The name 'm_RetroMusicSonic2' does not exist in the current context
        Error @(48,1) CS0103: The name 'RFL_SET_PARAM' does not exist in the current context
        Error @(48,34) CS0103: The name 'm_RetroMusicSonic2' does not exist in the current context
        Error @(50,1) CS0103: The name 'RFL_SET_PARAM' does not exist in the current context
        Error @(50,34) CS0103: The name 'm_RetroMusicSonic2' does not exist in the current context

**Comment by DeaTh-G** [comment]
Codes for HedgeModManager now have a new home at: https://github.com/hedge-dev/HMMCodes. If the issue/suggestion is still relevant please open an issue on that repository as code related issues are no longer being tracked on the main HedgeModManager repository.

Thank you, and sorry for the inconvenience.

P.S.: It also seems like your errors are coming from Mods, I would recommend contacting the mod author instead.
