### ISSUE TITLE
[Bug] Mods not applying to Sonic Forces

### ISSUE THREAD

**Issue by BrochachoTheBro** [thesupersonic16/HedgeModManager#759]
Despite HMM detecting the install and the mod loader supposedly being installed, Forces doesn't recognize my mods for some reason.
Tested both the Release and Development branches and the issue persisted.

**Comment by thesupersonic16** [comment]
Can you enable both "Enable mod loader" and "Enable debug console" and show me the top of the console log once you reach the title screen.

**Comment by BrochachoTheBro** [comment]
I thhhink it might be getting stuck on loading HE2ML?
![image](https://github.com/thesupersonic16/HedgeModManager/assets/128875586/cefd8280-faeb-4833-946f-b5bdb0fe4fdc)

**Comment by thesupersonic16** [comment]
Are you using a legit copy of the game from Steam?

**Comment by BrochachoTheBro** [comment]
No, but it's worked before by using the ExtraGameDirectories field in the Windows Registry Editor.

**Comment by DeaTh-G** [comment]
Only copies bought on PC storefronts (Steam, EGS, etc) are under support by HedgeModManager and the maintaining team as such we can not proceed with this issue.
