### ISSUE TITLE
[Sonic Frontiers] - Character Swapper soft-locks mission progress in Chaos Island if Emerald is accidentally collected by character other than Sonic

### ISSUE THREAD

**Issue by davewhiffen** [thesupersonic16/HedgeModManager#762]
## Describe the issue/bug

Chaos Island, softlocked at 'Collect the Chaos Emerald'.

Accidentally soft-locked myself with Character Swapper.

I collected the Green Emerald (which is that Tails mini-game where you bash open crates and collect screws)-- as Knuckles, 

So the Tails event has been registered as complete, but Knuckles has the green emerald (I can see when I switch to him and open my map)

So now I'm softlocked without a way to revert since I discovered too late.

Unless I can somehow spawn that enemy that steals emeralds, then have Knuckles lose it, and re-collect it as Sonic again.

Cheat Engine doesn't let you edit Emeralds, so that's out.

Will keep looking at a solution (and will backup my saves more often)

**Comment by DeaTh-G** [comment]
Codes for HedgeModManager now have a new home at: https://github.com/hedge-dev/HMMCodes. If the issue/suggestion is still relevant please open an issue on that repository as code related issues are no longer being tracked on the main HedgeModManager repository.

Thank you, and sorry for the inconvenience.

**Comment by davewhiffen** [comment]
Perfect! Thanks!
