### ISSUE TITLE
[Bug] After a restart of the game, HedgeModManager will rarely write into to your codes and pac files or just straight up refuse to read them correctly

### ISSUE THREAD

**Issue by DuckDealer1** [thesupersonic16/HedgeModManager#763]
## Describe the issue/bug
This first started prior to Update 3. I had to reinstall Combat DX 6 times due to an issue where after restarting the game, HMM would either write to the pac files or downgrade them to a previous version, causing issues where cameras would break, Supreme's boss fight would crash, Super Sonic's ring count would be set to 0, etc. I thought it was just a Combat DX issue until it started happening to other codes and mods... I can't even start the game now due to this issue. 5 minutes ago everything was working fine but after a restart, Super Sonic 2, Extended Photo Mode, Island Tweaker, Unleashed Sweepkick, and other codes are now instantly crashing the game even if I restart my pc, restart HMM, reinstall HMM, etc.

## Expected Behaviour
I was expecting it to not corrupt my files lol

## Additional Context
Not much more context I can give beyond what I've put here and sent to Hyper.

**Comment by thesupersonic16** [comment]
Sounds like it might be user error. Only times HMM should be able to access your files and making changes to them are updating. My guess is that you may have made a change and then you accidentally updated the mod making it downgrade, and with the downgraded file causes the game to crash. 

As for other codes, maybe you need to redownload the game and ensure all codes are updated (avoid mods with codes when doing this)
