### ISSUE TITLE
Framerate limits dont work

### ISSUE THREAD

**Issue by AnniIsHere** [thesupersonic16/HedgeModManager#766]
whenever i use the "29.97 FPS cap" code on sonic generations, it just doesn't work and the game keeps trying to go past

.

**Comment by DeaTh-G** [comment]
Codes for HedgeModManager now have a new home at: https://github.com/hedge-dev/HMMCodes. If the issue/suggestion is still relevant please open an issue on that repository as code related issues are no longer being tracked on the main HedgeModManager repository.

Thank you, and sorry for the inconvenience.
