### ISSUE TITLE
Make it modify files in a .pac

### ISSUE THREAD

**Issue by H-A-M-G-E-R** [thesupersonic16/HedgeModManager#772]
That makes merging mods for Frontiers so much easier
just create a folder named the same as the .pac in the .pac's folder and put files that are modded from the original

**Comment by DeaTh-G** [comment]
Feature requests that affect the Hedgehog Engine 2 Mod Loader should go to https://github.com/hedge-dev/HE2ModLoader.
This repository only deals with the HedgeModManager front end, not the mod loaders themselves.
