### ISSUE TITLE
[Bug] 7.12-2 release being detected as malware by Windows Defender

### ISSUE THREAD

**Issue by H-A-M-G-E-R** [thesupersonic16/HedgeModManager#781]
## Describe the issue/bug

when i try to download it it gives an error
## Expected Behaviour

not detected as malware

**Comment by RagdollClash** [comment]
False positive. Just tell Windows Defender to allow the program. Closing.

**Comment by thesupersonic16** [comment]
You can also send the exe as a sample to your AV if it offers the option to you.

**Comment by H-A-M-G-E-R** [comment]
I just build my own
my build is not detected as malware
