### ISSUE TITLE
[Bug] Disable Thorn Cylinders code also affect one of the Koco challenges on Kronos

### ISSUE THREAD

**Issue by Optimus-Bull** [thesupersonic16/HedgeModManager#784]
## Describe the issue/bug
The code "Disable Thorn Cylinders" which is supposed to remove the thorn cylinders that are placed in inconvenient locations in Cyber Space also affects one of the Koco challenges that is on Kronos Island.

The one near Big's fishing portal where you have to quick step on platforms in order to get one of the bigger Kocos that increase the Boost Gauge.

Turning it off does resolves this, though the code should ideally only affect the thorn cylinders in Cyber Space and not in the Open Zones. At least not affect that particular Koco challenge as it renders too easy and trivial compared to other challenges.

**Comment by DeaTh-G** [comment]
Codes for HedgeModManager now have a new home at: https://github.com/hedge-dev/HMMCodes. If the issue/suggestion is still relevant please open an issue on that repository as code related issues are no longer being tracked on the main HedgeModManager repository.

Thank you, and sorry for the inconvenience.
