### ISSUE TITLE
[Bug] Cant install mod loader for sonic generations

### ISSUE THREAD

**Issue by joes-basement** [thesupersonic16/HedgeModManager#786]
When hitting save or save and play, I'm asked to install a mod loader for Sonic Generations. After selecting yes, it shows that it's downloading it, but it really isn't. When the window disappears, and I click save again, it still says there's no mod loader.
I'm on version 7.12-4

**Comment by thesupersonic16** [comment]
When you go into the Settings tab, on the right, does it say `Install Mod Loader` or `Uninstall Mod Loader`, if it says `Install Mod Loader` does it change to `Uninstall Mod Loader` or stay the same?

**Comment by joes-basement** [comment]
When I first open hedgemod, it says "install mod loader." After "installing" it, it says "uninstall mod loader." But if I close and reopen hedgemod, it says "install mod loader" again.

**Comment by thesupersonic16** [comment]
Might be possible your Anti-Virus is preventing the installation of the mod loader, can you check your AV for any logs of it being deleted?

If nothing is found, can you send a snapshot file? To generate one, open HedgeModmanager and hold Shift and press F1 and a popup and an explorer window should show up with a .txt file highlighted, send that here.

**Comment by joes-basement** [comment]
Actually, I think it is being deleted by my AV. It deletes dinput8.dll.
Is there a way for me to install it manually?

**Comment by thesupersonic16** [comment]
`dinput8.dll` is the modloader DLL, you should set it as an exception on your AV. As for manually installing you can download it [here](https://github.com/thesupersonic16/HedgeModManager/raw/rewrite/HedgeModManager/Resources/ModLoader/HE1ML.dll) and place it next to the game exe and name the file `dinput8.dll`

**Comment by joes-basement** [comment]
To do that, I will need the hash for that file. May I ask what the hash for dinput8.dll is?

**Comment by thesupersonic16** [comment]
SHA256: 9d366c760094fc531c3d0fa337b5cc24e7aa348f5523c6ef79999c3b7b66c01e
