### ISSUE TITLE
[SonicGenerations] 

### ISSUE THREAD

**Issue by GustavinhoXbox** [thesupersonic16/HedgeModManager#787]
Hello, I updated HedgeModManager on November 21st and deleted some sonic generations mods that I no longer like, and installed some new ones but this error appears when I click save and play, I tried to run Sonic Generations without mods and the error persisted, If you can help me I will be grateful, thank you.

![image](https://github.com/thesupersonic16/HedgeModManager/assets/87884055/1aeab526-6bc3-48c2-a4e7-f6b63cbf32d2)

[HMM_Snapshot_00112023180115.txt](https://github.com/thesupersonic16/HedgeModManager/files/13453428/HMM_Snapshot_00112023180115.txt)

HMM Info:
```
    Version: 7.12-4
[HMM_Snapshot_00112023180115.txt](https://github.com/thesupersonic16/HedgeModManager/files/13453424/HMM_Snapshot_00112023180115.txt)

    Args: 
    StartDir: C:\Games\Sonic Generations\
    Process Level: Administrator
    Game: Sonic Generations
    GameInstall: Sonic Generations
    Update Status: Up To Date
```

Exception:
```
    Type: InvalidOperationException
    Message: Cannot start process because a file name has not been provided.
    Source: System
    Function: Boolean Start()
    StackTrace: 
       at System.Diagnostics.Process.Start()
       at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
       at HedgeModManager.MainWindow.StartGame() in D:\GitHub\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 754
       at HedgeModManager.MainWindow.<SaveConfig>d__55.MoveNext() in D:\GitHub\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 1115
```

**Comment by RagdollClash** [comment]
We do not support non-Steam/pirated versions of Sonic Generations. Please install the game normally using Steam.

Closing.
