### ISSUE TITLE
[Bug] HMM on Linux won't find games installed through Steam

### ISSUE THREAD

**Issue by souljolt** [thesupersonic16/HedgeModManager#788]
## Describe the issue/bug

I installed HMM on Linux as normal, and when I ran HMM through Bottles, HedgeModManager said no games were detected, even though I have Sonic Lost World installed. I'm not sure if it's because maybe the code put in the terminal didn't work or something.
### Expected Behaviour

I had expected it to work normally, with HMM noticing that the game was installed.

**Comment by DeaTh-G** [comment]
Please keep Linux related issues to the already existing Linux/Steam Deck issue page that you can find at https://github.com/thesupersonic16/HedgeModManager/issues/219.

**Comment by souljolt** [comment]
Huh. I swear I put this on the Linux/Steam Deck page.
