### ISSUE TITLE
Steamtinkerlaunch stuck at "installing HedgeModManager 7.12-4" on Steam Deck [Bug] 

### ISSUE THREAD

**Issue by Velonox** [thesupersonic16/HedgeModManager#790]
## Describe the issue/bug
I am trying to install the HedgeModManager on the Steam Deck, have done it before on a different Deck, via ProtonUp-Qt and using steamtinkerlauncher. I go into the Konsole and do "steamtinkerlaunch hmm start" and it begins installing but then gets stuck at "installing HedgeModManager 7.12-4" and I have left it going for 20 mins close to my router just in case it is installing but it's not working. 

## Expected Behaviour
The process would continue and would install the Windows Dependency and eventually boot up the Mod loader.

## Additional Context
The Deck may have fallen asleep on a previous attempt, messing with the installation so it would also help to know where to uninstall the program to remove any installed files and redo the process.

**Comment by DeaTh-G** [comment]
Please keep Steam Deck related issues to the already existing Steam Deck issue page that you can find at #219
