### ISSUE TITLE
[Bug] steamdecm install no longer works

### ISSUE THREAD

**Issue by CorinthianReturns** [thesupersonic16/HedgeModManager#791]
## Describe the issue/bug
Running the steamtinkerlaunch hmm start script just hangs on installing for well over an hour 
Bottles can no longer see config files for some reason either 

## Expected Behaviour
Installation to complete

**Comment by DeaTh-G** [comment]
Please keep Steam Deck related issues to the already existing Steam Deck issue page that you can find at https://github.com/thesupersonic16/HedgeModManager/issues/219
