### ISSUE TITLE
Problem: program not opening

### ISSUE THREAD

**Issue by GabrieleGiacomelli** [thesupersonic16/HedgeModManager#795]
## Describe the issue/bug
Every time i try to open the program, after i click it, it won't open, there's just the animation of the cursor loading and then nothing append. I try other version but the problem still remain

## Expected Behaviour
It should open

**Comment by thesupersonic16** [comment]
Can you check your Anti-Virus to see if it is preventing HMM from launching?

**Comment by GabrieleGiacomelli** [comment]
> Can you check your Anti-Virus to see if it is preventing HMM from launching?

I do have think of that, I have Norton so to try to stop the scan and the firewall protection but it didn't work. I did even scan the file with Norton and it seems It didn't see the file as a threat.

**Comment by GabrieleGiacomelli** [comment]
If need I'll send proof

**Comment by GabrieleGiacomelli** [comment]
![immagine_2023-12-05_070931667](https://github.com/thesupersonic16/HedgeModManager/assets/56293277/0224b195-520b-4d0b-88a5-22c6ddead0bc)



https://github.com/thesupersonic16/HedgeModManager/assets/56293277/810e9072-bb1f-4698-a549-96ea382d38a3

**Comment by GabrieleGiacomelli** [comment]
Still got the problem

**Comment by thesupersonic16** [comment]
Can you check `%localappdata%\CrashDumps` for any files that start with `HedgeModManager.exe`?

Also don't run HedgeModManager as Administrator.

**Comment by Syro09** [comment]
[hedgemodmanager_9f441.exe.9196.dmp](https://github.com/thesupersonic16/HedgeModManager/files/13631441/hedgemodmanager_9f441.exe.9196.dmp)

**Comment by thesupersonic16** [comment]
Can you try updating to 7.12-4 using this [download](https://github.com/thesupersonic16/HedgeModManager/releases/download/7.12-4/HedgeModManager.exe)?

**Comment by Syro09** [comment]
i have just tried it didnt work either

**Comment by GabrieleGiacomelli** [comment]
I'll send my crash dump tonight, I was away from home these days

**Comment by thesupersonic16** [comment]
You can also try installing the .NET 4.8 runtime if it allows you. You can find a download [here](https://dotnet.microsoft.com/en-us/download/dotnet-framework/net48) ([Direct Download (English)](https://go.microsoft.com/fwlink/?linkid=2088631))

**Comment by GabrieleGiacomelli** [comment]
So i try again with the new download link, still not work, nothing appear in the crash dump folder, and i have already installed the .NET 4.8

**Comment by thesupersonic16** [comment]
> So i try again with the new download link, still not work, nothing appear in the crash dump folder, and i have already installed the .NET 4.8

Have you tried an older version?

**Comment by GabrieleGiacomelli** [comment]
I tried some old one even the 7.0.0 version, but nothing change

**Comment by thesupersonic16** [comment]
Can you look in Event Viewer under Windows Logs>Application and look for a .NET Runtime error. Make sure to do this right after trying to run HMM.

**Comment by GabrieleGiacomelli** [comment]
I don't see any NET Runtime error appear

**Comment by GabrieleGiacomelli** [comment]
it's like it just won't start but nothing seems to appear anywhere to explain why

**Comment by GabrieleGiacomelli** [comment]
if you want we can make a call on discord so maybe doing things in live can help us find what's happening

**Comment by thesupersonic16** [comment]
Give this unpacked build a try.

[HedgeModManager.zip](https://github.com/thesupersonic16/HedgeModManager/files/13648946/HedgeModManager.zip)

**Comment by GabrieleGiacomelli** [comment]
Oh man thank you, it work

**Comment by thesupersonic16** [comment]
You shouldn't stay on that build if possible since it cannot update itself properly (also I left some test code in that build by mistake). Can you also try this build which is packed.

[HedgeModManager.zip](https://github.com/thesupersonic16/HedgeModManager/files/13649184/HedgeModManager.zip)

If this build does not work, then it may be an issue with Fody.Costura on your PC.

**Comment by GabrieleGiacomelli** [comment]
No, the second download dosen't work

**Comment by thesupersonic16** [comment]
Does it work along with the other DLLs next to it?

**Comment by GabrieleGiacomelli** [comment]
Should i copy all the dll file from the first downlaod and paste in the folder of the second download?

**Comment by thesupersonic16** [comment]
Yeah, see if that helps.

**Comment by GabrieleGiacomelli** [comment]
no dosen't work

**Comment by thesupersonic16** [comment]
Then just use this for now. Keep in mind updating may cause issues. 

[HedgeModManager.zip](https://github.com/thesupersonic16/HedgeModManager/files/13649573/HedgeModManager.zip)

The only other suggestions I could give is look into other software on your PC that may interfere with Fody.Costura like AVs, or just try building the code yourself, but that would require installing Visual Studio with the .NET development pack which takes up storage space.

**Comment by Syro09** [comment]
I tried the unpacked one, it did not work either

**Comment by Syro09** [comment]
and when i go back to earlier versions like 7.3 i get the "a new guard page for the stack cannot  be created"

**Comment by thesupersonic16** [comment]
> and when i go back to earlier versions like 7.3 i get the "a new guard page for the stack cannot be created"

Can you show me a screenshot?
