### ISSUE TITLE
Sonic Frontiers crashes when trying to load level if modloader is enabled

### ISSUE THREAD

**Issue by getCursorsExe** [thesupersonic16/HedgeModManager#799]
If modloader is enabled, Sonic Frontiers will crash when it tries to load any level.

## Expected Behaviour
The game does not crash.

**Comment by Sajidur78** [comment]
Can you provide more information?

What mods and codes do you have on?

**Comment by getCursorsExe** [comment]
I tried to disable all mods. Nothing of them fixes this.

**Comment by getCursorsExe** [comment]
Alright, Steam Cloud Saves was causing this. After disabling it, everything is back to normal
