### ISSUE TITLE
forces exe not recognised

### ISSUE THREAD

**Issue by Swift-Winds** [thesupersonic16/HedgeModManager#8]
I have the hedge mod manager in the  same folder as the forces exe and when i click scan or install/uninstall in the settings tab it doesnt say forces not installed but generations not installed

![not installed](https://user-images.githubusercontent.com/33810706/32993622-b3688c82-cd28-11e7-8088-95af3e4a2550.png)

**Comment by thesupersonic16** [comment]
That issue is already fixed, Please go on 6.1-008.
