### ISSUE TITLE
[Bug] (Linux/Steam Deck) “Disable FSR” breaks HMM | Sonic Frontiers |

### ISSUE THREAD

**Issue by Earleybyrd** [thesupersonic16/HedgeModManager#801]
After enabling the “Disable FidelityFX Super Resolution” code for Frontiers, the game will not boot without it. 

I understand from the installation process alone that Steam Deck likely isn't high priority for HMM, so I understand if this is dismissed, though I can’t be certain that this is a hardware specific issue, and if not, a code that permanently alters your game, even after it is disabled, is a pretty damning issue.

It is to note that the game does still boot with HMM disabled.

**Comment by RagdollClash** [comment]
Code issues should go to the HMMCodes repository.
https://github.com/hedge-dev/HMMCodes/issues
