### ISSUE TITLE
[Bug] [Sonic Colors Ultimate] [Linux/Steam Deck] Lighting mods crash on steam deck

### ISSUE THREAD

**Issue by amso71** [thesupersonic16/HedgeModManager#803]
Every lighting mod, whether it’s Loco’s Reimagined Lighting, Environment Tweaks, or Enhanced Lighting, are prone to crashing on Steam Deck. The former don’t even make it to the title screen before crashing. This only happens for Colors Ultimate, and no other game I’ve tried on HMM has this issue.

**Comment by BrochachoTheBro** [comment]
Did you ever find a fix for this? This thread has been marked as closed, but I'm still having the same issue. The game gets to the initial loading screen with Yacker groovin' around, then after a second it stops and crashes. Hopefully if this gets fixed then that can bode well for Project ReRainbow...

**Comment by amso71** [comment]
Oh sorry, I left a fix on the Rainbow Mod Loader issues tab, but I should’ve left one here too.
Here are the steps that fixed the issue for me.
- install protontricks to your steam deck via the discover app
- open protontricks and click the sonic colors: ultimate prefix
- go to “install a dll or component”
- select d3dcompiler_47 and install
- now go to “run winecfg”
- add kerberos and msv1_0 as overrides
- i believe d3dcompiler is an override by default, but if it’s not, add it
it should run correctly now, if it doesn’t, reopen winecfg and set the overrides you just added as native (windows) by clicking on them and pressing edit
if the issue still persists, feel free to contact me on discord, my username is _amso71_ and you can talk to me via dm or through the hedgehog engine modding discord.

**Comment by BrochachoTheBro** [comment]
I'll be sure to check it out when I can

**Comment by BrochachoTheBro** [comment]
Late reply but can confirm this fixes it
