### ISSUE TITLE
[Bug] [SonicForces]

### ISSUE THREAD

**Issue by SEGFAULT3102** [thesupersonic16/HedgeModManager#807]
Attempting to launch sonic forces with mods yields two errors, game launches without mods installed. Steam copy, perfectly validated internal files.

![image](https://github.com/thesupersonic16/HedgeModManager/assets/77807627/dc406828-1f84-465d-a45c-bb03bd9f6093)

![image](https://github.com/thesupersonic16/HedgeModManager/assets/77807627/2fbc7e47-2a10-4a31-86b0-e6a0d8383f6e)

**Comment by SEGFAULT3102** [comment]
![image](https://github.com/thesupersonic16/HedgeModManager/assets/77807627/c45a9930-b576-4d69-b22a-4947e7fe9dc2)
Debug log:

**Comment by SEGFAULT3102** [comment]
Update: As of now I have tried

- Uninstalling and reinstalling HE2ML
- Uninstalling and reinstalling Sonic Forces
- Verifying file integrity via steam
- Installing all of the DLC
- Wiping every trace of Sonic Forces from my disk
- Uninstalling and reinstalling Hedgemodmanager
- Uninstalling HE2Loader *and* Forces, Reinstalling, running Forces in an unmodified state, then reinstalling HE2ML
- Using SFMI (still no avail)

And, to put it simply:

https://github.com/thesupersonic16/HedgeModManager/assets/77807627/c614eaa1-29c2-4f17-9055-64d9f8923c13

**Comment by Sajidur78** [comment]
Are you on HMM development or release channel?

**Comment by Sajidur78** [comment]
Also, try deleting dinput8.dll and d3d11.dll from the game's folder and installing the mod loader through HMM.

**Comment by SEGFAULT3102** [comment]
d3d11.dll was already not there, removing dinput8.dll did nothing, modloader was already installed.

**Comment by SEGFAULT3102** [comment]
also, I'm on HMM's release channel.

**Comment by SEGFAULT3102** [comment]
![image](https://github.com/thesupersonic16/HedgeModManager/assets/77807627/23dd9354-0ae0-4512-8ea4-8ed25c50010a)

More of the debug log. This is when the title screen loads, and shows the post-game title screen, though only lost valley is available due to the save being new.

**Comment by SEGFAULT3102** [comment]
And, my hardware, if that information helps in some way:

AMD Ryzen 5 7535HS CPU, Radeon 660m APU

NVidia RTX 2050 mobile discrete GPU

16GB 4800mhz DDR5 RAM

2tb space (NVMe, PCIe 4.0)

**Comment by SEGFAULT3102** [comment]
Another update: attempted to apply mods via HedgeModManager on a separate PC, mods worked perfectly with no issue, even though the same installation method was used.

**Comment by RagdollClash** [comment]
Could you try going to `%LOCALAPPDATA%\NeverFinishAnything\CommonLoader\.storage` and deleting the ini file with `Name=Sonic Forces.exe` in there? It sounds like the sig cache got corrupted.

**Comment by SEGFAULT3102** [comment]
That worked. Thank you.
