### ISSUE TITLE
[GEN] HedgeModManage Stopped Working error

### ISSUE THREAD

**Issue by MarceloTheRock** [thesupersonic16/HedgeModManager#82]
When i open the program without a Mod Directory appears the message to create de dir, but when i click yes the program stop to work and appear that "Stopped Working" message.

I tried everything and nothing, i reintaled the game, deleted all SonicGMI files and nothing, in my other computer the Manager is working, the 2 notebooks have the SAME version of the Windows, i don't know what is happening, maybe it's the lack of some update, but i don't know if this program ask for any specific windows app.

**Comment by thesupersonic16** [comment]
Does this issue also occur when you run HedgeModManager as admin?

**Comment by MarceloTheRock** [comment]
Yes

Em sáb, 28 de mar de 2020 21:41, SuperSonic16 <notifications@github.com>
escreveu:

**Comment by thesupersonic16** [comment]
Can you tell me where you have `HedgeModManager.exe` stored at (Full path like `D:\SteamLibrary\steamapps\common\Sonic Generations`), and
When you said you deleted all the SonicGMI files, did you make sure you removed the cpkredir.ini file and the mods folder.

**Comment by MarceloTheRock** [comment]
I have tried to put It in downloads dir and in Sonic Generations dir.

About Sonic GMI, i unistalled Sonic then deleted all left filés then
installed again, the SG dir was fully "virgin".

Em sáb, 28 de mar de 2020 21:53, SuperSonic16 <notifications@github.com>
escreveu:

**Comment by thesupersonic16** [comment]
Since you mentioned it saying "Stopped Working", it might be better to just send over the crash dump it would have made so I can see what kind of error you got.

You can find it by going to `%localappdata%\CrashDumps` and sending one of the files containing the name `HedgeModManager`

**Comment by MarceloTheRock** [comment]
1,"fusion","GAC",0
1,"WinRT","NotApp",1
3,"System, Version=4.0.0.0, Culture=neutral,
PublicKeyToken=b77a5c561934e089","C:\Windows\assembly\NativeImages_v4.0.30319_64\System\5d38433b42c8020426ab2fef33289985\System.ni.dll",0
3,"WindowsBase, Version=4.0.0.0, Culture=neutral,
PublicKeyToken=31bf3856ad364e35","C:\Windows\assembly\NativeImages_v4.0.30319_64\WindowsBase\02e261c71dbc7a1fb1e0bb393bc87268\WindowsBase.ni.dll",0
3,"PresentationCore, Version=4.0.0.0, Culture=neutral,
PublicKeyToken=31bf3856ad364e35","C:\Windows\assembly\NativeImages_v4.0.30319_64\PresentationCore\64054af93528146af01d8deb12de2384\PresentationCore.ni.dll",0
3,"PresentationFramework, Version=4.0.0.0, Culture=neutral,
PublicKeyToken=31bf3856ad364e35","C:\Windows\assembly\NativeImages_v4.0.30319_64\Presentatio5ae0f00f#\246d8c30b2c93d4d60210a4d601363be\PresentationFramework.ni.dll",0
3,"System.Xaml, Version=4.0.0.0, Culture=neutral,
PublicKeyToken=b77a5c561934e089","C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Xaml\679e4f72c74a9f1b6a8951134637b4f6\System.Xaml.ni.dll",0
3,"System.Core, Version=4.0.0.0, Culture=neutral,
PublicKeyToken=b77a5c561934e089","C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Core\33c6ece549f64f82d61d9a873cccb0b9\System.Core.ni.dll",0
3,"System.Configuration, Version=4.0.0.0, Culture=neutral,
PublicKeyToken=b03f5f7f11d50a3a","C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Configuration\9380d4841099f865836cff07d6dca435\System.Configuration.ni.dll",0
3,"System.Xml, Version=4.0.0.0, Culture=neutral,
PublicKeyToken=b77a5c561934e089","C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Xml\a467c3d70456914e477182a37dd9947a\System.Xml.ni.dll",0
3,"PresentationFramework.Aero2, Version=4.0.0.0, Culture=neutral,
PublicKeyToken=31bf3856ad364e35","C:\Windows\assembly\NativeImages_v4.0.30319_64\Presentatioaec034ca#\c361f0a3efdec358ef3214b583239e47\PresentationFramework.Aero2.ni.dll",0
2,"PresentationFramework-SystemXml, Version=4.0.0.0, Culture=neutral,
PublicKeyToken=b77a5c561934e089",0
2,"UIAutomationTypes, Version=4.0.0.0, Culture=neutral,
PublicKeyToken=31bf3856ad364e35",0

Em sáb., 28 de mar. de 2020 às 22:05, SuperSonic16 <notifications@github.com>
escreveu:

**Comment by thesupersonic16** [comment]
That tells me nothing. I need the stacktrace.

**Comment by MarceloTheRock** [comment]
There's no Crash Dumps, just that usagelog. I dont know why. The language
is portuguese, but the message is the same in any windows.

Em sáb, 28 de mar de 2020 22:28, SuperSonic16 <notifications@github.com>
escreveu:
