### ISSUE TITLE
[SonicGenerations] 

### ISSUE THREAD

**Issue by mariosbignuts** [thesupersonic16/HedgeModManager#825]
i havent played the game in a while, so when i opened the mod loader it asks me to update. once it was done, it thinks the game doesn't have a mod loader yet so i let it install one
and then it breaks i unno

[HMM_Snapshot_00012024181928.txt]
(https://github.com/thesupersonic16/HedgeModManager/files/13975880/HMM_Snapshot_00012024181928.txt)

HMM Info:
```
    Version: 7.12-4
    Args: 
    StartDir: D:\Games\Files\Sonic Generations\
    Process Level: User
    Game: Sonic Generations
    GameInstall: Sonic Generations
    Update Status: Up To Date
```

Exception:
```
    Type: InvalidOperationException
    Message: Cannot start process because a file name has not been provided.
    Source: System
    Function: Boolean Start()
    StackTrace: 
       at System.Diagnostics.Process.Start()
       at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
       at HedgeModManager.MainWindow.StartGame() in D:\GitHub\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 754
       at HedgeModManager.MainWindow.<SaveConfig>d__55.MoveNext() in D:\GitHub\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 1115
```

**Comment by Sajidur78** [comment]
Try disabling 'Use Game Launcher' from settings.

Closing as HedgeModManager doesn't condone piracy.

**Comment by RagdollClash** [comment]
We do not support non-Steam/pirated versions of Sonic Generations. Please install the game normally using Steam.
