### ISSUE TITLE
Divorced

### ISSUE THREAD

**Issue by Klemci** [thesupersonic16/HedgeModManager#826]
Hello, what does mean 7.11.x log's line :

**Divorced CPKREDIR**

?please?

**Comment by Sajidur78** [comment]
Haha, it's just a joke about how we discontinued using CPKREDIR the old mod loader for HE1ML the new and improved mod loader for Hedgehog Engine 1 titles like Generations and SLW.

**Comment by RagdollClash** [comment]
it's also a reference to Zig's "File for Divorce from LLVM"
https://github.com/ziglang/zig/issues/16270#event-9697646328
