### ISSUE TITLE
[SonicFrontiers] some decal/geometry textures disappear when HMM is enabled

### ISSUE THREAD

**Issue by Zizoplays1** [thesupersonic16/HedgeModManager#834]
## Describe the issue/bug
As the title says, for some weird reason, after I installed HMM for frontiers, some minor textures will just disappear, this includes grass, rocks, trees, bushes, some of the flowers in ouranos island and the vines at some of the ruins or structures in kronos island, a workaround for this is by pressing the pause menu and returning back to the game, the issue will be temporarily gone, but it will come back again after a cutscene, camera changing to another position or running at high speed for some time.

## Expected Behaviour
I initially expected it to be one of the mods or one of the codes I installed for the game, turns out none of them were the cause and it seems to be a bug within the mod loader files, I even uninstalled and disabled the mod loader in the settings page and this issue is still present, game was running great and never had this issue before I even downloaded HMM for frontiers

## Additional Context
Here are screenshots for what I mean

Without the issue:
![Screenshot 2024-01-28 113816](https://github.com/thesupersonic16/HedgeModManager/assets/80594096/95ca06ae-0edd-41f1-8106-6a8b1167f697)

With the issue:

![Screenshot 2024-01-28 113757](https://github.com/thesupersonic16/HedgeModManager/assets/80594096/14038e43-cd10-434c-93df-d7a0fe6dbb5b)

**Comment by RandomguywhlovesSonic** [comment]
Do you have any mods that can modify thr game's textures? Like something like the Low End Mod for Sonic Generations

**Comment by Zizoplays1** [comment]
Mods I currently :

> -island tweaker
-outfit fixes
-HE1 sonic (with unleashed animations)
-Trailer LUTs
-tracker's physics
-Dynamic lightdash

Even though I highly thought either that HE1 sonic or Trailer LUTs were the cause, disabling all mods still has this issue present for some reason

**Comment by DeaTh-G** [comment]
@thesupersonic16 @Sajidur78 please provide assistance.
Stale label removed.

**Comment by thesupersonic16** [comment]
Can you try pressing `Uninstall Mod Loader` then running the game from Steam? If the issue still occurs after that, then the issue is very likely your PC or corrupted game files.
