### ISSUE TITLE
[Bug] [SonicForces] Steam Input is non-functional if the Mod Loader is installed

### ISSUE THREAD

**Issue by DigitalStarSys** [thesupersonic16/HedgeModManager#841]
## Describe the issue/bug
When running Sonic Forces via HedgeModManager, my Switch Pro Controller does not function, even though Steam Input says it should. "Use Game Launcher" is enabled, and uninstalling the HE2 Mod Loader via "Uninstall Mod Loader" fixes it, and my Pro Controller begins to function again.

## Expected Behaviour
I expected Steam Input to work, as it does in un-modded Forces. For some reason, it doesn't seem to, despite being functional in the Steam overlay, where it tells me Steam Input is enabled.

## Additional Context
This happens whether mods or codes are enabled or not. The only thing that seems to fix it is uninstalling the mod loader. Launching it via Steam does nothing, launching it via "Save and Play" does nothing, and launching it via "Sonic Forces.exe" does nothing. The only way to get Steam Input to function again is to uninstall HE2 Mod Loader.

Using HMM version 7.12-4 on Windows 11 23H2, OS build 22631.3007. Controller being tested is a Switch Pro Controller connected via USB. Bluetooth did not seem to make a difference, nor did running it through DS4Windows.

**Comment by DeaTh-G** [comment]
As this seems to be an issue with HE2ModLoader please report this issue to the appropriate repository for it.
https://github.com/hedge-dev/HE2ModLoader/issues
