### ISSUE TITLE
[SonicFrontiers] [SteamDeck] Please reinstall the.NET framework 

### ISSUE THREAD

**Issue by StrayCatAnimations** [thesupersonic16/HedgeModManager#842]
I followed this guide to install HMM 7.12-4 on my steam deck for Sonic Frontiers:

https://linuxgamingcentral.com/posts/updated-sonic-frontiers-steam-deck-modding-guide/

HMM didn't work at first, but then I saw a note here that mentioned that adding an mscoree.dll file to the main folder the .exe is in. This made HMM work, but when turning mods on, Sonic Frontiers crashes when I try to turn it on with the following message:

"A fatal error occurred. However, mscorees.dll could not be loaded to display appropriate error message.  

Please reinstall the .NET framework"

I tried to uninstall the .NET framework through the following command:

"protontricks --no-background-wineserver 1237320 --force dotnet48"

but it fails to do so with the following message:
"Blocking Issues:
The .NET Framework 4 Client Profile and the .NET Framework 4 Extended must be removed separately. Please use Control Panel to uninstall these programs. For more information, see the Readme file."

Any ideas how to fix this? If there's another way to solve this or if there's a way to properly uninstall it.

**Comment by DeaTh-G** [comment]
Please keep Steam Deck related issues to the already existing Steam Deck issue page that you can find at https://github.com/thesupersonic16/HedgeModManager/issues/219.
