### ISSUE TITLE
[Unnamed Game] 

### ISSUE THREAD

**Issue by RandomguywhlovesSonic** [thesupersonic16/HedgeModManager#844]
HMM Info:
```
    Version: 7.2-4
    Args: 
    StartDir: C:\Users\Louambas\AppData\Local\Temp\Rar$EXa1900.5372\
    Process Level: Administrator
    Game: Unnamed Game
```

Exception:
```
    Type: NullReferenceException
    Message: Object reference not set to an instance of an object.
    Source: HedgeModManager
    Function: System.Collections.Generic.List`1[HedgeModManager.SteamGame] SearchForGames(System.String)
    StackTrace: 
       at HedgeModManager.Steam.SearchForGames(String preference)
       at HedgeModManager.App.Main(String[] args)
    InnerException: 
```

Please help me i really need Hedge Mod Manager to work
P.S: Im on Win 8

**Comment by Sajidur78** [comment]
Try extracting it instead of running it from an archive

**Comment by RandomguywhlovesSonic** [comment]
OK, im so dumb... Why i didn't thought of that
Sorry for the english, it's not my first language....

**Comment by RandomguywhlovesSonic** [comment]
Now it doesn't even wants to run....
It just jump scared me and says this:
HMM Info:
```
    Version: 7.2-4
    Args: 
    StartDir: C:\Users\Louambas\Downloads\HedgeModManageHERE\
    Process Level: Administrator
    Game: Unnamed Game
```

Exception:
```
    Type: NullReferenceException
    Message: Object reference not set to an instance of an object.
    Source: HedgeModManager
    Function: System.Collections.Generic.List`1[HedgeModManager.SteamGame] SearchForGames(System.String)
    StackTrace: 
       at HedgeModManager.Steam.SearchForGames(String preference)
       at HedgeModManager.App.Main(String[] args)
    InnerException: 
```
It's same right?

**Comment by thesupersonic16** [comment]
Can you please locate and upload the `libraryfolders.vdf` file? This file should be located within your `steamapps` folder on your OS drive.

If GitHub does not allow you to upload the file, then put the file in a ZIP file, and then upload that here.

**Comment by RandomguywhlovesSonic** [comment]
[libraryfolders.zip](https://github.com/thesupersonic16/HedgeModManager/files/14184198/libraryfolders.zip)
There it is. Im not familiar with Steam, and i don't have Sonic Generations on my PC because i changed it and my Steam account too, so i have the game files of Generations, but steam won't let me make i appear on my list of games. Thanks!

**Comment by thesupersonic16** [comment]
It needs to appear in Steam for it to work.

**Comment by RandomguywhlovesSonic** [comment]
Then how do it make it appear in Steam? I tried to move the game folder in the common folder, and tried the Non Steam game...

**Comment by thesupersonic16** [comment]
You need to be logged into an account that has access to the game. You should change to the account that has the game and install it from there or use family sharing to allow a second account to have access.

**Comment by RandomguywhlovesSonic** [comment]
But i don't have access to the account that has the game... I can't do anything right?

**Comment by thesupersonic16** [comment]
Even if you get it installed, you would not beable to play it. We only provide support to the latest legit Steam version.

There are other ways to install a backed up copy, but the proper way will require access to an account with the game including accounts with family sharing.

**Comment by RandomguywhlovesSonic** [comment]
Oh... It's an legit game, since i bought it from Steam.... But you said there was other ways, what are they?

**Comment by thesupersonic16** [comment]
Not sure how you can't log into that account. As for installation, just place the files in the same place as it was when you backed it up.

**Comment by RandomguywhlovesSonic** [comment]
I forgot the password, and can't recover it.
