### ISSUE TITLE
[Sonic Frontiers] [Steam Deck] Crashes on boot when Mod Loader is installed

### ISSUE THREAD

**Issue by BrochachoTheBro** [thesupersonic16/HedgeModManager#857]
Any time I try playing on Deck with mods and codes nowadays, it just crashes unexpectedly. I've disabled all codes and mods to see if any specific one of those were an issue, but it still crashed for me, so it might be related to the Mod Loader. I tried the Development update channel and it still crashes.

Frontiers is running with Proton Experimental, and HMM was installed using the Bottles method. I am using the OLED model (1TB LE) with SteamOS 3.5.7 if that's of any importance.

**Comment by thesupersonic16** [comment]
Any issues relating to getting HMM and the modloaders working on Linux should go to #219. Your issue sounds like you may not have .NET Framework installed in the game prefix. We do have a section in the guide for this [here](https://github.com/thesupersonic16/HedgeModManager/wiki/Running-on-Linux#installing-mod-loader-dependencies). If this does not work, ask in #219.

**Comment by BrochachoTheBro** [comment]
>We do have a section in the guide for this [here](https://github.com/thesupersonic16/HedgeModManager/wiki/Running-on-Linux#installing-mod-loader-dependencies).

Methods 1 and 2 are unwritten, and I'd gladly try Method 3 if the `windows.7z` file for extracting the dependencies wasn't no longer available.

**Comment by thesupersonic16** [comment]
I didn't notice the file is missing. I have updated the link.
