### ISSUE TITLE
Someone please help me get this working on steam deck.

### ISSUE THREAD

**Issue by BURGERKINGFARD** [thesupersonic16/HedgeModManager#862]
I have hmm installed perfectly and it works flawlessly with generations but it doesn't work at all with frontiers. I select mods, save and load the game and no mods or codes work at ALL.

**Comment by DeaTh-G** [comment]
Please keep Steam Deck related issues to the already existing Steam Deck issue page that you can find at https://github.com/thesupersonic16/HedgeModManager/issues/219.
