### ISSUE TITLE
bottles version cant find  a game even though i own it

### ISSUE THREAD

**Issue by notlunaryh** [thesupersonic16/HedgeModManager#864]
so, i was trying to mod sonic frontiers so i decided to install HMM thru bottles instead of steam tinker launch because tinker launcher leaves konsole to be stuck on "running configuration for sonic frontiers", but it can't find my game even though I literally own it. thanks in advance

>

**Comment by Caintastrophe** [comment]
Did you solve this? Im having the same issue, except HMM cant detect Origins or generations, and cant seem to find a remedy online

**Comment by DeaTh-G** [comment]
@thesupersonic16 @Sajidur78 please provide assistance.
Stale label removed.
