### ISSUE TITLE
[Bug] Profiles no longer apply changes to configurable mods

### ISSUE THREAD

**Issue by RagdollClash** [thesupersonic16/HedgeModManager#870]
## Describe the issue/bug
When changing profiles, HMM will no longer apply settings for configurable mods for the profile you selected.

## Expected Behaviour
Configurable mods should change to what they're set to in the selected profile.

## Additional Context
The issue was caused by 50dbb8c380aeb533286d86a2b072db2c707cb141.

**Comment by thesupersonic16** [comment]
Does the issue resolve itself after reverting that single commit?

**Comment by RagdollClash** [comment]
Yes.

**Comment by RagdollClash** [comment]
Re-opening because it's not properly fixed, that commit is just a hotfix.

**Comment by RagdollClash** [comment]
Properly fixed with ed3fac921e97eac6b16b559108298f61701cd661.

**Comment by Sajidur78** [comment]
I still want an egg
