### ISSUE TITLE
Preserving the original Sonic Generations in case of when SXSG Drops as a Update [Feature Request] 

### ISSUE THREAD

**Issue by hourai-branch** [thesupersonic16/HedgeModManager#876]
In case of Sonic X Shadow Generations dropping as a update for the original sonic generations,
the old version could be preserved by Making a feature in hedgemodmanager 
that downloads a old steam depot of the original game.
then for making the game work past 2038 (see Y2038 on wikipedia)
we could then gaslight the game into it being run at a date before 2038, so it can keep running on life support.

but still, im scared that microsoft by and around that time will try and kill off 32-bit support in windows,
so if the tools are available to make code injection mods for SXSG please do use them to create your mod for the new binary
and if you have some mods to be ported, or wanna have ported,  and the developer doesnt want to port the mod by him/her or itself, ask kindly for the source code in case the original developer doesnt want his mod open-source or port it using publicly available source code.
still, i dont expect this would go flawlessly, but i have seen some truely incredible mods, and i would be so sad to see them all fade away.
may the sonic generations modding scene be preserved for eternity, i wish everybody luck as i am illiterate in any programming languages. and i have heard that html/css dont count as programming languages.

still if there is anything i could do even if its after a few years of learning programming i would be glad to help.

i hope my idea to at least make sonic generations and its mods able to live in a time capsule will be useful of any kind,
and i hope we will successfully make the transition to 64-bit.

thanks people for making all these incredible mods for the last 10 years

Project Eternal-Generation, engage!

**Comment by DeaTh-G** [comment]
How people acquire the original, 2011 release of Sonic Generations has nothing to do with the mod manager. Closing.

**Comment by thesupersonic16** [comment]
I appreciate the effort on making the feature request, but like what DeaTH-G said, the way Sonic Generations is acquired has nothing to do with the manager (desides searching for the game).

Something I would like to mention is that I don't think MS will ever kill off 32-bit backwards compatiblity on the x86_64 builds of the OS, it would kill off far too many applications.

As for your worry with the remaster being an update for SG and Y2k38, I believe they would take the delist approach, they already made a new listing of the remaster afterall. For the date bug, chances are we will have a patch to solve that (if the bug even exists in the game).

**Comment by hourai-branch** [comment]
ah, ok! thanks @thesupersonic16 for your helpful information. have a nice day!
