### ISSUE TITLE
Where is the save file saved when you enable Save File Redirection in Sonic Generations?

### ISSUE THREAD

**Issue by CodeRiverFoxLife** [thesupersonic16/HedgeModManager#883]
Can someone answer please?

**Comment by thesupersonic16** [comment]
By default fallback save files are stored in the game directory, in the case of Sonic Generations, it is `cpkredir.sav`

https://github.com/thesupersonic16/HedgeModManager/blob/f071e0bfcbad78e31ecf2cdb07aa0b13ff92dacc/HedgeModManager/Game.cs#L22-L26
