### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Arhezzz** [thesupersonic16/HedgeModManager#885]
Hello, I have been trying to download mods for sonic generations but this happens and when I close the error I open the game but in a basic way, without any mod, I already tried with a steam version and it cracked, the problem persists having an old version or a new, could you give me a solution? please and thank you very much :D
![image](https://github.com/thesupersonic16/HedgeModManager/assets/136064344/e6e7bc8b-d59b-4a94-a625-adb710bb61cc)
![image](https://github.com/thesupersonic16/HedgeModManager/assets/136064344/7881d0c2-67cb-460e-baea-71cb4980848f)
I have the latest version of the game that was released for Steam, I still don't know why this problem persists :c

**Comment by Sajidur78** [comment]
@Arhezzz could you upload the SonicGenerations.exe file you have,and upload a HMM snapshot? The snapshot hotkey is Shift + F1 on the HMM window.

Also I suggest verifying integrity of game files from Steam.

**Comment by Arhezzz** [comment]
I reinstalled the game from steam, put in the mod installer and started the game from there and it worked. The problem was that I installed a fix for the game with, I suppose, an older version of the game. Thank you very much for answering so quickly, and thank you for allowing us to play with the mods with your program :D
