### ISSUE TITLE
Frontiers keeps crashing with HMM installed 

### ISSUE THREAD

**Issue by Jurg99** [thesupersonic16/HedgeModManager#886]
I went on frontiers yesterday and the game just kept crashing. I opened HMM to see if it was maybe a mod I had on or something but it wasn’t any of that it was HMM itself because when I uninstalled it the game wouldn’t crash. When I opened hmm the first time to see what was going on this message popped up (it never appeared again so this screenshot is all I got) 
![IMG_2724](https://github.com/thesupersonic16/HedgeModManager/assets/168982817/55ee8bd2-5070-4021-9db7-1edd4a766e87)

**Comment by DeaTh-G** [comment]
Please keep Linux related issues to the already existing Linux issue page that you can find at https://github.com/thesupersonic16/HedgeModManager/issues/219.
