### ISSUE TITLE
[Bug] Sonic Forces Controller Unresponsive

### ISSUE THREAD

**Issue by demonskunk** [thesupersonic16/HedgeModManager#888]
## Describe the issue/bug
When I launch Sonic Forces through the mod loader, my controller is unresponsive. Keyboard and mouse work fine.

## Expected Behaviour
I expect the game to read my controller inputs as normal.

## Additional Context
I discovered this while attempting to run Sonic Frontiers Overclocked. I tested the game with the mod unloaded just to be sure it wasn't the mod causing it. Simply launching the game through HedgeMod causes the game not to read controller inputs.

I have a wireless PS4 controller that is recognized by Steam and runs fine in the game when I don't run it through the mod loader. I'm running Windows 10. I own and am running Sonic Forces through Steam.

**Comment by thesupersonic16** [comment]
Do you have "Use game launcher" enabled in Hedge Mod Manager?

**Comment by demonskunk** [comment]
> Do you have "Use game launcher" enabled in Hedge Mod Manager?

I didn't, but I tried it with it enabled and disabled. If it's disabled, clicking "Save and Play" just launches Sonic Forces unmodified (which works fine), and it only runs Hedgemod's loader if I launch it from steam. If it's Enabled, it runs the loader every time (which causes the game not to recognize the controller, whether or not I am loading any mods)

**Comment by demonskunk** [comment]
Definitely don't want this to automatically close.

**Comment by thesupersonic16** [comment]
This is a known issue with the mod loader on Sonic Forces. It appears to not play well with Steam Input.

Can you try renaming `dinput8.dll` to `d3d11.dll` and see if both the modloader and your controller start working?

**Comment by demonskunk** [comment]
Changing dinput8.dll, disabling steaminput, then restarting the game does seem to fix the issue. Thank you!
