### ISSUE TITLE
Sonic generations don´t change at all 

### ISSUE THREAD

**Issue by Matias19056** [thesupersonic16/HedgeModManager#89]
when i downloaded the Hedgehog Mod Manager
I paste the application into the folder of sonic generations (Pirate)
and the Mod manager it´s able to recognize all my mods and codes  (i already unistalled every single file of the sonic GMI including the application itself) but when i press the "install mod loader" and i put save and play. Any of the mods or codes   
aren´t working ingame 
so can you help me???
 
![Screenshot (20200413-151132)](https://user-images.githubusercontent.com/63608381/79146990-9dda0200-7d99-11ea-8c3e-46e033b0a809.jpg)

![Screenshot (20200413-151615)](https://user-images.githubusercontent.com/63608381/79147164-e396ca80-7d99-11ea-8b3b-ed16a03ef7e7.jpg)

![Screenshot (20200413-151627)](https://user-images.githubusercontent.com/63608381/79147178-eb566f00-7d99-11ea-8602-16f7d1e19398.jpg)

![Screenshot (20200413-151639)](https://user-images.githubusercontent.com/63608381/79147193-f14c5000-7d99-11ea-8296-659884ceffec.jpg)

![Screenshot (20200413-151846)](https://user-images.githubusercontent.com/63608381/79147298-1b057700-7d9a-11ea-8bc1-e25c98b1d1f9.jpg)

**Comment by Matias19056** [comment]
for example when i run the game in the HMM this happens...
![Screenshot (20200413-153806)](https://user-images.githubusercontent.com/63608381/79149127-0aa2cb80-7d9d-11ea-86b7-f24dd4c47834.jpg)

![Screenshot (20200413-153922)](https://user-images.githubusercontent.com/63608381/79149135-1098ac80-7d9d-11ea-9e60-c4c4a122b4ad.jpg)

![Screenshot (20200413-153900)](https://user-images.githubusercontent.com/63608381/79149146-155d6080-7d9d-11ea-9a78-497974c9c924.jpg)

**Comment by thesupersonic16** [comment]
I can't really help you with Code Loader issues on pirated versions as I can not verify if the game has been tampered or is old and we straight up don't support it. (The game was 5 USD yesterday)

Also some DirectX injectors can cause some issues like ReShade maybe check if you have anything like that running.

All I can say is that the Code Loader isn't loading and the Code Loader lives in the d3d9.dll file in your Sonic Generations folder. You will need to make sure that file gets loaded, which I think your pirated version is preventing.

I'm sorry to say this, but we don't support issues that occur on pirated versions on the game.

**Comment by Matias19056** [comment]
No worries
But thanks anyways
