### ISSUE TITLE
Unable to change priority of mods 

### ISSUE THREAD

**Issue by SonicThomasGamer** [thesupersonic16/HedgeModManager#890]
## Describe the issue/bug
Dragging and dropping doesn't work, In order to even start dragging and dropping I have to drag my mouse outside the window, even then the mod won't move to where I drag it. 

## Expected Behaviour
Drag and drop mods to change priority

## Additional Context
this problem happens in Stable release and Development release

The mod I try to move becomes transparent and moves to the top of the window as if I was still holding it with my mouse

**Comment by thesupersonic16** [comment]
I cannot reproduce this issue, are you running this on Windows?

**Comment by SonicThomasGamer** [comment]
> I cannot reproduce this issue, are you running this on Windows?

Yes I am. It works for you though? could you send me a screenshot before and after if you could?

**Comment by SonicThomasGamer** [comment]
> I cannot reproduce this issue, are you running this on Windows?

I'll send what exactly happens to me when I CAN drag the mod through a "trick" I found (It's really weird how this 'came to be/ works' on my end)

Hopefully that can narrow down my problem

**Comment by SonicThomasGamer** [comment]
This is my mod loader
![Screenshot (456)](https://github.com/thesupersonic16/HedgeModManager/assets/133928350/87086f6f-ddc8-4e2e-b753-2e9dd846605b)


and this is what happens when I try to move a mod (it gets stuck like that) (Or my other case scenario where it seems to work ie. "move the mod"  and the mod still didn't move)
![Screenshot (455)](https://github.com/thesupersonic16/HedgeModManager/assets/133928350/9f4a2b20-1d50-4153-910b-ac4b72e135d5)

**Comment by thesupersonic16** [comment]
@Sajidur78 Are you able to help out on this drag and drop related issue?

**Comment by Sajidur78** [comment]
Not unless I can reproduce it

**Comment by SonicThomasGamer** [comment]
> Not unless I can reproduce it

I reinstalled Windows and it doesn't seem to happen anymore

**Comment by mateusvini13** [comment]
I'm having this problem, too. Dragging a mod makes it get stuck in the screen, even when changing tabs. Dragging the cursor outside the window "unstucks" it, but the mod order doess not change.

I'm on Windows 10, latest update, latest NVIDIA graphics driver. I'm wondering if maybe an NVIDIA overlay or something is what fucks up the drag action? It seems to be something very specific, as most users are not experiencing it.

The workaround for me now is dunno kinda trying to install the mods in the order needed :/

https://github.com/user-attachments/assets/d1fdff9e-abb5-4892-8389-e87f787b8198
