### ISSUE TITLE
[Question] How to add multiple games to ExtraGameDirectories at once?

### ISSUE THREAD

**Issue by BrochachoTheBro** [thesupersonic16/HedgeModManager#893]
Using HMM on Deck in a specific way, and the only way it can detect games is if I use the ExtraGameDirectories field in the Registry Editor in Bottles to point to folder shortcuts I put in a folder on the Desktop. Thing is, it can only detect one game at a time, and I've only been able to get it to recgonize Generations and Frontiers which is weird.

**This scenario above is an example and this question is not limited to Linux/Deck usage,** but how does one format multiple game directories? I tried putting all directories in the ExtraGameDirectories field with spaces in between them with no luck, then I added a comman between each directory without luck either; it only was able to see either Frontiers or Gens onr at a time.

(Excuse me if this is a noob question)

**Comment by thesupersonic16** [comment]
Seperate all paths with a semicolon `;`

I will need to look into why HMM is not detecting Steam libraries properly on Linux someday.

**Comment by BrochachoTheBro** [comment]
Gotcha, thanks

And that would be massively appreciated, though no need to break your back over it

**Comment by coatlessali** [comment]
Trying to add Forces right now and this doesn't seem to be working for me. HMM still only shows Generations. 
![image](https://github.com/user-attachments/assets/b8640c0b-0123-4eac-a54f-d8c0930b6778)
![image](https://github.com/user-attachments/assets/b8f6fbd7-7daa-413a-9c71-58bc83bcb9cf)
