### ISSUE TITLE
[Bug] Code enabling issues from Sonic Frontiers (using Epic Games Store version)

### ISSUE THREAD

**Issue by BlueprintBailey** [thesupersonic16/HedgeModManager#895]
## Describe the issue/bug
Enabling certain codes or mods (not sure which ones) to the Epic Games Store version of Sonic Frontiers causes issues. When turning these codes off, things go back to normal. However, turning some back on caused certain issues to reappear again.

I have found out some of the codes that can cause issues; I will continue to add to this list as I find which of the big ones are causing such things.

-Classic Jump Deceleration (causes some of the open-zone to get messed up on locations, as well as the characters not being able to play their animations correctly)
-Tutorial Skip (you can't boot up the game for Epic Games Launcher)

## Expected Behaviour
I'm expecting that the codes don't cause issues whjen playing the game. I'm unsure what happened to cause it, but I believe it can be fixed in the next version of HedgeModManager.

## Additional Context
Below is a link to the video showing the animation issue. I have the whole thing at 60 fps, mind you.

https://github.com/thesupersonic16/HedgeModManager/assets/85625864/73cb4c50-f723-4b26-ab1d-912f2811c5b1

**Comment by HerogonStudios** [comment]
Update: I have found out one of the codes that can cause animation issues; will continue to add to this list as I find which of the big ones are causing such thing.

-Classic Jump Deceleration

**Comment by RagdollClash** [comment]
This issue should be in [HMMCodes](https://github.com/hedge-dev/HMMCodes), not this repo. Additionally, all the codes made for Sonic Frontiers are for the Steam version of the game since that's the version most people own, so issues like this are to be expected on Epic.
