### ISSUE TITLE
[Bug] Sonic Origins causes HMM to crash on Steam Deck

### ISSUE THREAD

**Issue by martinsaenz96** [thesupersonic16/HedgeModManager#896]
Whenever I'm selecting Sonic Origins from the drop down menu, it causes HMM to crash instantly. Then causes HMM to not even open at all. I've tried uninstalling and installing both HMM and the game, and still shows the same result. And I have mods already in the mods folder, but can't access or configure them in anyway. This issue has been nagging me for about a week at this point, and can't find any solution.

[HMM_Snapshot_00062024235415.txt](https://github.com/user-attachments/files/15965001/HMM_Snapshot_00062024235415.txt)

**Comment by thesupersonic16** [comment]
Can you please check if this issue is reproducible on [7.12-9](https://github.com/thesupersonic16/HedgeModManager/releases/download/7.12-9/HedgeModManager.exe)?
