### ISSUE TITLE
[Bug] HedgeModManager not recognizing sonic games via Bottles

### ISSUE THREAD

**Issue by ndegug** [thesupersonic16/HedgeModManager#899]
## Describe the issue/bug

So I was finally able to run HedgeModManager on steam deck via the script found in [Issue 219](https://github.com/thesupersonic16/HedgeModManager/issues/219#issuecomment-1193167222) but not only was I unable to click most items in the menu (mods and codes tab, check boxes and directory fields in the "games and mod loader" section) but also, the manager wasn't recognizing Sonic Frontiers despite both the bottle and the game being in my internal drive. 
## Expected Behaviour

Sonic Frontiers should appear in the drop down menu at the bottom left.
## Additional Context

I followed every step in [this video](https://www.youtube.com/watch?v=uot8XeCv_nM) up to, and including "add 'HedgeModManager.exe' in the 'Programs' tab."

**Comment by thesupersonic16** [comment]
That video is old, I believe this is the current [method](https://github.com/thesupersonic16/HedgeModManager/wiki/Running-on-Linux).

I have recently released [7.12-9](https://github.com/thesupersonic16/HedgeModManager/releases/download/7.12-9/HedgeModManager.exe) which contains some changes to how Steam is detected using Bottles. Had confirmation from one user that it now works.
