### ISSUE TITLE
[Bug] Fatal Error When Downloading Mods from GameBanana

### ISSUE THREAD

**Issue by SilverSpireZ** [thesupersonic16/HedgeModManager#90]
After updating HedgeModManager, I cannot install mods from GameBanana using the URL installer. I just get a Fatal Error and this message. This happens with all three games.
> HMM Info:
> ```
>     Version: 7.1-3
>     Args: -gb hedgemmgens:https://gamebanana.com/mmdl/455806,Gamefile,10786
>     StartDir: D:\Games\steamapps\common\Sonic Generations\
>     Process Level: User
>     Game: Sonic Generations
>     SteamGame: Sonic Generations
> ```
> 
> Exception:
> ```
>     Type: IOException
>     Message: Access to the path 'D:\Games\steamapps\common\Sonic Generations\temp_install\mods\UnleashingUnleashedProjectMod\disk\bb2' is denied.
>     Source: mscorlib
>     Function: Void DeleteHelper(System.String, System.String, Boolean, Boolean, WIN32_FIND_DATA ByRef)
>     StackTrace: 
>        at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
>        at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
>        at HedgeModManager.ModsDB.InstallModArchiveUsingZipFile(String path, String root)
>        at HedgeModManager.ModsDB.InstallModArchive(String path, String root)
>        at HedgeModManager.UI.GBModWindow.<>c__DisplayClass5_0.<Download_Click>b__0()
>        at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
>        at System.Windows.Threading.Dispatcher.Invoke(Action callback)
>        at System.Net.WebClient.OnDownloadFileCompleted(AsyncCompletedEventArgs e)
>        at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>        at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
>        at System.Windows.Threading.DispatcherOperation.InvokeImpl()
>        at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
>        at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>        at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>        at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>        at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
>        at System.Windows.Threading.DispatcherOperation.Invoke()
>        at System.Windows.Threading.Dispatcher.ProcessQueue()
>        at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>        at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>        at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
>        at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>        at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
>        at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
>        at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
>        at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
>        at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
>        at System.Windows.Window.ShowHelper(Object booleanBox)
>        at System.Windows.Window.ShowDialog()
>        at HedgeModManager.DownloadWindow.Start()
>        at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>        at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
>        at System.Windows.Controls.Primitives.ButtonBase.OnClick()
>        at System.Windows.Controls.Button.OnClick()
>        at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
>        at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
>        at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
>        at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>        at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
>        at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
>        at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
>        at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
>        at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>        at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
>        at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
>        at System.Windows.Input.InputManager.ProcessStagingArea()
>        at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
>        at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
>        at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
>        at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>        at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>        at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>        at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
>        at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>        at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
>        at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
>        at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
>        at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
>        at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
>        at System.Windows.Window.ShowHelper(Object booleanBox)
>        at System.Windows.Window.ShowDialog()
>        at GameBananaAPI.GBAPI.ParseCommandLine(String line)
>        at HedgeModManager.App.Main(String[] args)
>     InnerException: 
> ```

**Comment by thesupersonic16** [comment]
Oh it looks like it is having troubles deleting the the old temp files from another mod. in all your Sonic games does deleting the temp_install folder fix your issue?

**Comment by SilverSpireZ** [comment]
Yep, that did it! Thanks!

**Comment by thesupersonic16** [comment]
Reopening since the bug still occurs.

**Comment by thesupersonic16** [comment]
Fixed in dd86bf823cacce879bdb2815f1f5c6d6689e4de3
