### ISSUE TITLE
[I can't install mods in Sonic Forces] 

### ISSUE THREAD

**Issue by iwanttomodforces** [thesupersonic16/HedgeModManager#900]
When i try to use the hedgemod manager for sonic forces it just doesn't work, first of all when i click "install mod manager" and run the game all my prgoress dissapears i need to uninstall it for it to work or uncheck the redirect default save file then the mods don't work i've tried downloading a few, and they don't work, and finally for some reason i can't use my controller (it's a DS4) please help

also i have to mention that it works perfeclty fine

**Comment by FactorRott37** [comment]
> When i try to use the hedgemod manager for sonic forces it just doesn't work, first of all when i click "install mod manager" and run the game all my prgoress dissapears i need to uninstall it for it to work or uncheck the redirect default save file then the mods don't work i've tried downloading a few, and they don't work, and finally for some reason i can't use my controller (it's a DS4) please help
> 
> also i have to mention that it works perfeclty fine

Go to settings and disable "Redirect Default Save File"

This worked for me.

**Comment by thesupersonic16** [comment]
This is a known issue with the mod loader on Sonic Forces. It appears to not load correctly with Steam Input.

Can you try renaming `dinput8.dll` to `d3d11.dll` and see if both the modloader and your controller start working?

As for your save file, just disable the default redirect, mods with save files will automatically enable the redirection.
