### ISSUE TITLE
[Bug] Steam Deck Crash that disables Mouse

### ISSUE THREAD

**Issue by Pokemiah** [thesupersonic16/HedgeModManager#908]
## Describe the issue/bug
Whenever I try to boot the game on Steam Deck using SteamTinkerLaunch, it disables the mouse and fails to boot the application. I don’t know why. It just started doing this.

## Expected Behaviour
App boots normally with mouse trackpad fully functional.

## Additional Context
I typically use Proton-GE 7-41 for HMM. This bug also disabled my left joystick and Steam Button and persists into Gaming Mode. I have tried a fresh install of SteamTinkerLaunch, but that made it worse. I don’t know how to make a clean new install of hmm using it.

**Comment by thesupersonic16** [comment]
We don't provide support on running Hedge Mod Manager on Linux outside of it's GitHub issue (#219). Please reply in there.

As for STL, I am not really sure if it is even being worked on for getting Hedge Mod Manager running. We do however have a guide which uses [Bottles](https://github.com/thesupersonic16/HedgeModManager/wiki/Running-on-Linux-(Bottles)).
