### ISSUE TITLE
[Bug]  Mods fail to load due DInput8.dll related error

### ISSUE THREAD

**Issue by Daddu3** [thesupersonic16/HedgeModManager#914]
## Describe the issue/bug

Attempting to load any mod with newest version of HedgeModManager gives me a following error:

![image](https://github.com/user-attachments/assets/3a728f05-61f7-41bb-ab92-34d1a4053a15)

It looks to do with the DInput8.dll generated upon loading them.

## Expected Behaviour

Load mods properly.

## Additional Context

I'm still using Windows 8.1, so I'm curious is this to do with me having outdated operating system to load mods with this manager.

**Comment by thesupersonic16** [comment]
It appears the functions the modloader uses were introduced in Windows 10. Please update to Windows 10 or newer. Also we do not support pirated versions of the games.
