### ISSUE TITLE
(Steam Deck) Frontiers won't launch if HMM has any codes active or any mods installed

### ISSUE THREAD

**Issue by Flannels** [thesupersonic16/HedgeModManager#916]
## Describe the issue/bug
I perfectly followed this guide https://github.com/thesupersonic16/HedgeModManager/wiki/Running-on-Linux-(Bottles)#setting-up-the-prefix but whenever I try to launch Sonic Frontiers with any mods installed or any codes activated, the game will close right before the Sega logo appears. The game will only launch if the mod list is empty and no codes are activated. After a mod is placed in the Mods folder, the game won't launch at all unless the Mods folder is removed. Unchecking the mod doesn't make a difference.

## Expected Behaviour
The game playing with mods/codes active.

## Additional Context
I attempted to follow the troubleshooting steps, but they didn't help. The game still closes before it can start.
Current version of HMM is 7.12-9.

**Comment by Flannels** [comment]
Closed because I give up.

**Comment by thesupersonic16** [comment]
At the monent we post Linux related issues in a single issue (#219) If you ever get back to this, send a proton log to that thread.
