### ISSUE TITLE
[Bug] Codes not working on Linux and EGS Colors Ultimate not detected - Is it normal ?

### ISSUE THREAD

**Issue by GuckicheLorraine** [thesupersonic16/HedgeModManager#918]
Hello !
I use the new bottles methods to install HMM on my Linux Mint and I planned on redoing it for Steam Deck but I never managed to make any HMM codes works : if I enable a HMM code, the games crashes at launch (both Gens and Frontiers, the two games I tested) which is pretty annoying.
Additionnally, I absolutely don't know how to force HMM to detect my EGS version of Sonic Colors Ultimate installed through Heroic Launcher, even tho HMM detects it on windows with the exact same installation of the game on the same drive.
Any idea on how to fix that ?

**Comment by thesupersonic16** [comment]
Please send proton logs for both games. You can Google how to create one.

As for not detecting EGS games on Linux make sure Bottles has permissions to the folder Heroic stores their games and configs. If it still doesn't work, look for your `installed.json` file which may be in a folder called "legendary". Once you find it, send me the file and where you found it.

**Comment by GuckicheLorraine** [comment]
[installed.json](https://github.com/user-attachments/files/17089251/installed.json)
So here is the installed.jsojn file found in this path : /home/linmatt/Games/Heroic/Prefixes/default/Sonic Colors Ultimate/drive_c/users/linmatt/Music/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary.

Here are Frontiers logs : 
[steam-1237320.log](https://github.com/user-attachments/files/17089365/steam-1237320.log)

As for gens, after reinstalling mono and adding the following command line : WINEDLLOVERRIDES="dinput8.dll=n,b","d3d11.dll=n,b" PROTON_LOG=1 %command% the codes now works. It's the only of my three problems I was able to solve.

**Comment by thesupersonic16** [comment]
How did you install Heroic in a location like that?

As for Frontiers, It appears the modloader hasn't loaded the HMMCodes yet, also it appears its trying to load mscoree.dll from the SonicFrontiers folder which is unusual. Not sure if you want to set d3d11 to native as I believe proton has its own implementation.

**Comment by GuckicheLorraine** [comment]
To be exact, Heroic is installed on my Linux Mint drive and the game is installed on another drive that I also use on Windows (I do dual booting).
How do I remove d3d11 to native also ? I remove the argument from this line WINEDLLOVERRIDES="dinput8.dll=n,b","d3d11.dll=n,b" PROTON_LOG=1 %command% ?
