### ISSUE TITLE
[SonicColorsUltimate] Steam Deck Crash with Re-Rainbow

### ISSUE THREAD

**Issue by jeffkrull** [thesupersonic16/HedgeModManager#922]
## Describe the issue/bug
Sonic Colors Ultimate is crashing when the Sonic Colors Project Re-Rainbow mod is enabled on the Steam Deck. The crash happens when entering Tropical Resort Act 1. The act title card appears, Sonic appears, the camera starts to pan around him, and the game crashes back to Steam. Oddly enough, I am able to play other acts of the game. Tropical Resort 2 and 3 both work fine (I have not unlocked further in my save), but Act 1 crashes every time. 

## Expected Behaviour
The stage should not crash with the mod enabled.

## Additional Context
The issue is specifically with the Re-Rainbow mod, although I am not entirely convinced the problem is a bug in the mod. It may very well be, but other users report being able to get it going without issue. I have set up the mod loader correctly for the Steam Deck (I think), since I can run other mods and HMM codes without issue. Disabling Project Re-Rainbow allows all stages to work. I suspect it's an issue with the Proton prefix. I used the guide to set up the prefix, installing .NET 4.8. As an experiment, I tried changing the Proton version to an older Proton 8 version instead of current, and doing that caused the game to crash as soon as the opening cutscene ended when the mod was enabled. I had to delete and recreate the prefix to get back to the state I was at before.

I attached some Proton logs. The log file was so big I split it in two for GitHub size restrictions. I wanted to generate debug logging from HMM, but clicking Save and Play from within HMM throws a "file not found" error, and the game does not launch. Games launch from Steam just fine with mods enabled. 

[steam-2055290.log](https://github.com/user-attachments/files/17134705/steam-2055290.log)

[steam-2055290-2.log](https://github.com/user-attachments/files/17134703/steam-2055290-2.log)

**Comment by RagdollClash** [comment]
This sounds like an issue with the mod itself, since the mod is being loaded into the game. I would contact the mod author regarding this issue. 

You can also try to reinstall the mod to see if that fixes the issue, a file may have potentially gotten corrupted.

**Comment by jeffkrull** [comment]
I managed to figure out the solution myself. For anyone who happens to find this issue, the solution was to go into Protontricks and install the Windows component "d3dcompiler_47" into the Sonic Colors Ultimate Proton prefix. Then the crashing issue I was seeing stopped. I don't know if it fixes crashing across the board, but I can load into the first stage now without issue.
