### ISSUE TITLE
[Bug] Any version of HedgeModManager past Ver. 7.9 will not even open properly on my computer

### ISSUE THREAD

**Issue by TidesSonic** [thesupersonic16/HedgeModManager#923]
Any time I try to open up the latest version of HedgeModManager, the program will automatically default to a transparent version of the Crash window, then automatically close after a few seconds with no error message or any other feedback, essentially locking me out of using the program anywhere past 7.9, as even at 7.10 will cause this same issue of immediately crash closing with no feedback whatsoever. What is going on???

![image](https://github.com/user-attachments/assets/aa3c221f-7ddd-49a5-b503-ce1c80f10555)
Pictured what happens when I open ver 7.9 of HMM.

![image](https://github.com/user-attachments/assets/3b99d8e0-54d0-4461-bc63-d25b7a0e6260)
Pictured what happens any time I try to open HMM ver 7.10 and above, even the latest version.

YThis renders me unable to even open Sonic Forces Overclocked, as it won't function properly on HMM ver. 7.9. Why is this program acting this way???

**Comment by thesupersonic16** [comment]
Try running a debug build then going to `%localappdata%\CrashDumps` and send me the newest file that has `HedgeModManager.exe` somewhere in its name.
[HedgeModManager.zip](https://github.com/user-attachments/files/17158451/HedgeModManager.zip)

**Comment by TidesSonic** [comment]
Now I'm even more confused.

The one you sent in your comment didn't even boot, and the CRashDumps folder doesn't even exist in my Roaming Folder.

But grabbing the one from the GitHub actions compile now somehow works.

I don't get it.

![image](https://github.com/user-attachments/assets/7b1055ac-b6af-4a69-9849-9758bd88ffb5)
