### ISSUE TITLE
[Bug] Frontiers crashing on loading screens with mods and/or codes enabled (Steam Deck)

### ISSUE THREAD

**Issue by Flannels** [thesupersonic16/HedgeModManager#929]
I was directed to a guide on Reddit by some lovely peeps on Twitter (I'm not calling it X) and it was thankfully, finally, the one I needed to get HMM running and functioning properly on my Steam Deck. The only problem is... the game likes to crash during loading screens despite every mod and code I have active seemingly working properly. I don't know where to locate crash logs or anything that could help me figure out what's causing these crashes, so I'm kinda stuck here. These images show what mods - in order - and codes I have active if that happens to be a component in this.
![ksnip_20241006-164946](https://github.com/user-attachments/assets/da40fb22-a659-4f88-b8f9-df960be25714)
![ksnip_20241006-165216](https://github.com/user-attachments/assets/c4f875c3-b828-4a8e-8d7a-cf128ab75d36)
![ksnip_20241006-165404](https://github.com/user-attachments/assets/3c32c0e6-154b-462a-a42a-1692464418cb)
![ksnip_20241006-165609](https://github.com/user-attachments/assets/050da731-07e2-4fee-8843-1f67337bb434)
![ksnip_20241006-165736](https://github.com/user-attachments/assets/aadf94b0-8a85-4078-856a-a3ab764abe68)
![ksnip_20241006-165914](https://github.com/user-attachments/assets/fe3bdf89-540e-4d3b-bb44-e3af818392c3)
![ksnip_20241006-170048](https://github.com/user-attachments/assets/7d73cce7-0065-425c-bdad-5c71fccb5040)

## Expected Behaviour
I was hoping the game would work with the mods and codes without issue now that I've installed them properly instead of the file replacement method, and these crashes don't seem to be common with other HMM Frontiers Deck players.

## Additional Context
I'm not sure what additional context I can provide here, I'm just hoping to fix whatever is causing the crashing because from what I've been able to play with these mods, this is the most fun I've EVER had with Sonic Frontiers. I just don't wanna deal with the game crashing almost every time I switch islands or go into a Cyberspace stage.

**Comment by thesupersonic16** [comment]
Sorry for not noticing this issue. Can you start by disabling all codes and mods (that contain the code icon) and see if the game starts up fine?

As for getting a log, in the case of crashes a log from Proton is needed, you can easily find information on how to create one and locate it.

by the way, custom code support (which some mods uses) does not play well on Linux at times. The cause for this issue is still unknown.
