### ISSUE TITLE
[Bug] Hedgemodmanager not opening

### ISSUE THREAD

**Issue by MrBxcx** [thesupersonic16/HedgeModManager#933]
## Describe the issue/bug
When I try to open the program it only makes my cursor play the loading animation and just doesnt open

## Expected Behaviour
Opens

## Additional Context
I have already tried solutions from [this bug report  ](https://github.com/thesupersonic16/HedgeModManager/issues/795) that had the same issue, however none worked. I have already installed to the latest .NET

**Comment by LongSkull3739** [comment]
I also seem to be having the same problem as you, where the cursor plays the loading animation but the application never loads, and I cannot fix it either. thing is it only happened when I installed the DLC
