### ISSUE TITLE
Error to add game

### ISSUE THREAD

**Issue by ExcelionWolf** [thesupersonic16/HedgeModManager#937]
New release of hedgemodmanager doesnt locates my sonic frontiers and if i add it i get this error
![image](https://github.com/user-attachments/assets/e89762e9-848c-4ef6-b177-8471fb2043f0)

**Comment by PeterP-nut** [comment]
i just made this account for the sole purpose of posting here, hello everyone working on this project. i have the same issue, i have bought sonic x shadow from the epic game store and it does not recognize either games. i would be forever thankful if anyone got this issue solved.

![mercury_U7vcsUyEct](https://github.com/user-attachments/assets/a69e3539-9cd1-4303-8dc5-1fac4802f0f9)

**Comment by hyperbx** [comment]
The mod manager *should* detect the Epic Games Store version, but the ID could be wrong. Add Game is likely failing due to the timestamp being different between the Steam and EGS version.

None of us currently own the EGS version of the game, so we can't confirm, nor guarantee that the mod loader would work with it otherwise.

I would highly recommend getting the Steam version instead, as that will be maintained more in terms of code mod support.

**Comment by thesupersonic16** [comment]
@ExcelionWolf Where is Sonic Frontiers located and does Hedge Mod Manager detect any other games?

@PeterP-nut Going to need your `LauncherInstalled.dat` file. 
The file is found by navigating to `HKEY_CURRENT_USER\SOFTWARE\Epic Games\\EOS` in the registry and getting the `ModSdkMetadataDir` value, then in file explorer go to that value and then navigating `..\..\..\UnrealEngineLauncher\LauncherInstalled.dat`

**Comment by ExcelionWolf** [comment]
its on a external drive, but weirdly enough the previous version of hedgemodmanager does auto detects it, the new version doesnt and if i add it myself it gives that error i showed
@thesupersonic16

**Comment by thesupersonic16** [comment]
Have you previously manually added the game into HMM? Is this the Steam version of the game?

**Comment by ExcelionWolf** [comment]
@thesupersonic16 this is the first time actually and my sonic frontiers is from Epic Games, but again, previous HMM worked fine

**Comment by thesupersonic16** [comment]
Can you check if this fixes the game detection?
[HedgeModManager.zip](https://github.com/user-attachments/files/17528878/HedgeModManager.zip)

**Comment by ExcelionWolf** [comment]
will do when i turn on the pc tomorrow, is a bit late here

**Comment by Hookkitiri** [comment]
> Can you check if this fixes the game detection? [HedgeModManager.zip](https://github.com/user-attachments/files/17528878/HedgeModManager.zip)

No, it unfortunately doesn't fix the issue. Same problem as OP for me, same pop-up for eg.store version.

If it isn't too much to ask (which I'm 90% sure it is, no pressure :3) but could someone on the team get the Epic Games version? I accidentally bough that version while trying to test a credit card that wasn't working, it ended up working lol

**Comment by Hookkitiri** [comment]
(P.S: It also stopped auto detecting Frontiers off of the eg.store, I might have to move things back to my internal SSD not my external HDD, but I don't have enough storage for it on there, which is why it's on the external in the first place.)

**Comment by thesupersonic16** [comment]
Was Frontiers being detected before the build I sent or the release build?

**Comment by Hookkitiri** [comment]
It was working on 7.12.9, but 7.13 and the build you sent both didn't detect (or work when manually chosen) Frontiers or SxS Gens.

**Comment by thesupersonic16** [comment]
Its hard for me to test as I don't use EGS myself.

Does this help?
[HedgeModManager.zip](https://github.com/user-attachments/files/17530313/HedgeModManager.zip)

**Comment by Hookkitiri** [comment]
> Its hard for me to test as I don't use EGS myself.
> 
> Does this help? [HedgeModManager.zip](https://github.com/user-attachments/files/17530313/HedgeModManager.zip)

Nope, doesn't change a thing unfortunately. 
Side Note: appreciate the work and effort put in to HMM, keep it up!

**Comment by PeterP-nut** [comment]
> @PeterP-nut Going to need your `LauncherInstalled.dat` file. The file is found by navigating to `HKEY_CURRENT_USER\SOFTWARE\Epic Games\\EOS` in the registry and getting the `ModSdkMetadataDir` value, then in file explorer go to that value and then navigating `..\..\..\UnrealEngineLauncher\LauncherInstalled.dat`


is this what you were looking for ?   
`{
			"InstallLocation": "F:\\EpicLibrary/SonicxShadowGenerations",
			"NamespaceId": "a195e51c853d46038d13c49b882a9215",
			"ItemId": "12436886228c4753b6e479efcb848356",
			"ArtifactId": "a88805d3fbec4ca9bfc248105f6adb0a",
			"AppVersion": "1.1.0.0.14",
			"AppName": "a88805d3fbec4ca9bfc248105f6adb0a"
		}`

i did find the LauncherInstalled.dat , but not where u said i would find it. thought i would mention it

**Comment by thesupersonic16** [comment]
Where was it located? Also is there two exe files in the SonicxShadowGenerations folder?

**Comment by thesupersonic16** [comment]
I used the wrong separator, try this.

[HedgeModManager.zip](https://github.com/user-attachments/files/17530336/HedgeModManager.zip)

**Comment by Hookkitiri** [comment]
IT WORKED! I SEE SXSG, OG ENS, AND FRONTIERS! TYSM <3

**Comment by Hookkitiri** [comment]
(OG GENS, not OG ENS lol)

**Comment by thesupersonic16** [comment]
Good to hear it now working.

**Comment by PeterP-nut** [comment]
> Where was it located? Also is there two exe files in the SonicxShadowGenerations folder?

yes, isn't steam the same ? `SONIC_GENERATIONS` and `SONIC_X_SHADOW_GENERATIONS`



> I used the wrong separator, try this.
> 
> [HedgeModManager.zip](https://github.com/user-attachments/files/17530336/HedgeModManager.zip)

great news, it detected shadow generations !!

sonic generations isn't detected yet for some reason


![HedgeModManager_IqIrVzBw4H](https://github.com/user-attachments/assets/e6abe969-6147-4b2f-8514-2f1eb6203d43)

**Comment by thesupersonic16** [comment]
I wanted to be sure the file name is the same. As for Sonic Generations (2024) being missing, the mod loader is not yet ready for release so for now it is just Shadow Generations.

**Comment by Hookkitiri** [comment]
Hold up, whenever I boot Shad Gens, an error pops up, the game loads into a black screen, then crashes.
![Screenshot 2024-10-26 225339](https://github.com/user-attachments/assets/7aefd40f-9d55-4a09-8a39-bef3558dc3a4)

**Comment by Hookkitiri** [comment]
I should probably go to sleep now, it's like 11pm where I am.

**Comment by thesupersonic16** [comment]
> Hold up, whenever I boot Shad Gens, an error pops up, the game loads into a black screen, then crashes. ![Screenshot 2024-10-26 225339](https://private-user-images.githubusercontent.com/182474788/380420607-7aefd40f-9d55-4a09-8a39-bef3558dc3a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5NDM5NTYsIm5iZiI6MTcyOTk0MzY1NiwicGF0aCI6Ii8xODI0NzQ3ODgvMzgwNDIwNjA3LTdhZWZkNDBmLTlkNTUtNGEwOS04YTM5LWJlZjM1NThkYzNhNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNlQxMTU0MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ODY0ODYxYzNiOGE1YWQ5OWVkOWU2MWE4NWM0ZjRkY2JkYTI2NzQxYzZjYTEyMTk0MTI2MjJlMTIzYzc5ZjI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ZoojUNpOhHdeVnh_qSDGe3mj5JrjkoVTmuqyAnJOIw8)

I am going to need the whole exe file to beable to look into that. If you can please upload it on a site like Google Drive so I can take a look. The exe is roughly 500 MB.

**Comment by PeterP-nut** [comment]
> > Hold up, whenever I boot Shad Gens, an error pops up, the game loads into a black screen, then crashes. ![Screenshot 2024-10-26 225339](https://private-user-images.githubusercontent.com/182474788/380420607-7aefd40f-9d55-4a09-8a39-bef3558dc3a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5NDM5NTYsIm5iZiI6MTcyOTk0MzY1NiwicGF0aCI6Ii8xODI0NzQ3ODgvMzgwNDIwNjA3LTdhZWZkNDBmLTlkNTUtNGEwOS04YTM5LWJlZjM1NThkYzNhNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNlQxMTU0MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ODY0ODYxYzNiOGE1YWQ5OWVkOWU2MWE4NWM0ZjRkY2JkYTI2NzQxYzZjYTEyMTk0MTI2MjJlMTIzYzc5ZjI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ZoojUNpOhHdeVnh_qSDGe3mj5JrjkoVTmuqyAnJOIw8)
> 
> I am going to need the whole exe file to beable to look into that. If you can please upload it on a site like Google Drive so I can take a look. The exe is roughly 500 MB.



i report having the same error as he does.

here is shadow generations EXE as you requested

[https://mega.nz/file/7o033IbK#IZvJb_SFsrkxJr9ddNMddyCVDjR42my595LohZffIno](url)

**Comment by thesupersonic16** [comment]
Do you get any other popups besides the GetStatus?

**Comment by thesupersonic16** [comment]
I am going to need someone to enable the debug console and take a screenshot of the console window as the error message appears.

**Comment by PeterP-nut** [comment]
> I am going to need someone to enable the debug console and take a screenshot of the console window as the error message appears.

![image](https://github.com/user-attachments/assets/a55df500-96e5-4131-978b-8d822449c93e)
![image](https://github.com/user-attachments/assets/6d8ec6b3-0bef-4392-a2c8-7313041c8ff5)

> Do you get any other popups besides the GetStatus?

the game pops up fullscreen then poof, nothing else

**Comment by PeterP-nut** [comment]
> Do you get any other popups besides the GetStatus?

the game pops out then crashes, fullscreen then poof

**Comment by thesupersonic16** [comment]
Try placing the dll file next to the game exe and see if mods start workining.
[d3d11.zip](https://github.com/user-attachments/files/17530634/d3d11.zip)

**Comment by PeterP-nut** [comment]
> Try placing the dll file next to the game exe and see if mods start workining. [d3d11.zip](https://github.com/user-attachments/files/17530634/d3d11.zip)

it wokred, i even downloaded a mod to replace the main menu to test it.

![image](https://github.com/user-attachments/assets/a6a47e4e-1c2a-4277-9dd6-6e6b3cc54e7d)

**Comment by thesupersonic16** [comment]
All the fixes should now be pushed.

**Comment by SonicIranianFan** [comment]
> New release of hedgemodmanager doesnt locates my sonic frontiers and if i add it i get this error ![image](https://github.com/user-attachments/assets/e89762e9-848c-4ef6-b177-8471fb2043f0)

i have this problem and i use hedgemodmanager 7.13.0 to add game but i cant add sonic forces/lost world and my games are pirate, also i add sonic generation and this game also pirate, pls help
