### ISSUE TITLE
[Bug] (Linux & potentially Steam Deck) Sonic X Shadow Generations crashes when installing the HE2 mod loader

### ISSUE THREAD

**Issue by BNDays27** [thesupersonic16/HedgeModManager#941]
## Describe the issue/bug
When installing the HE2 mod loader, the game will not open and will crash on startup

my launch options right now are:
`SteamDeck=1 PROTON_LOG=1 prime-run gamemoderun %command%`

If you require a log, [here's one i made](https://github.com/user-attachments/files/17531826/steam-2513280.log)

(This is through Proton GE but this still happens when using proton experimental and potentially other versions of proton)

**Comment by thesupersonic16** [comment]
You need .NET 4.8 installed in the game prefix. Please move to #219 if you need further help as we usually keep Linux support in one issue.
