### ISSUE TITLE
[Bug] [ShadowGenerations] [codes]

### ISSUE THREAD

**Issue by CODEX0827** [thesupersonic16/HedgeModManager#947]
## Describe the issue/bug
disable ring magnetism code make the ring collecting challenges impossible
## Expected Behaviour
ring that are collected for some reason are not counting for the challenge

**Comment by hyperbx** [comment]
Which challenges specifically? I haven't been able to reproduce this behaviour.

**Comment by CODEX0827** [comment]
the challenges that make you collect a certain amount of rings (try this one)
![image_2024-10-30_221355315](https://github.com/user-attachments/assets/2e599670-c0d8-4ebe-9d31-91cc8f9eefe2)

**Comment by CODEX0827** [comment]
the white space challenges

**Comment by hyperbx** [comment]
Ah those ones, yeah they do seem to be broken. Will look into it.

**Comment by CODEX0827** [comment]
thank you and Quick question when is Sonic Generations (SXSG/2024) going to be add to the manager if you can say of course

**Comment by hyperbx** [comment]
Fixed in commit https://github.com/hedge-dev/HMMCodes/commit/b65b516416cd6d309d0716c1452b285c3eb47b20.

You can find the latest news about Sonic Generations (2024) integration [here](https://x.com/radfordhound/status/1848726232436822333).

**Comment by CODEX0827** [comment]
thanks
