### ISSUE TITLE
[Shadow Generations] [Code] Restore Stomp Bounce bug?

### ISSUE THREAD

**Issue by CODEX0827** [thesupersonic16/HedgeModManager#952]
when using the Restore Stomp Bounce in game it locks the double jump after using it (if im using the Stomp Bounce i cant double jump after) but i can boost from it and then double jump so i think it a bug but I'm not sure

**Comment by thesupersonic16** [comment]
This repo is for Hedge Mod Manager program itself, for game codes, please report the issue to [hedge-dev/HMMCodes](https://github.com/hedge-dev/HMMCodes).

Closing.

**Comment by CODEX0827** [comment]
ok
