### ISSUE TITLE
[Shadow Generations]  Adjust Aspect Ratio To Resolution code doesn't work

### ISSUE THREAD

**Issue by RostovShev03** [thesupersonic16/HedgeModManager#954]
## Describe the issue/bug
The game launches but without applying this code even it enabled (Horizontal black bars still presents)

## Expected Behaviour
When this code enabled it should adjust the game display to non-16:9 resolution display

## Additional Context
none

**Comment by thesupersonic16** [comment]
This repo is for the Hedge Mod Manager program itself. For game codes, please report the issue to [hedge-dev/HMMCodes](https://github.com/hedge-dev/HMMCodes).

Closing.

**Comment by RostovShev03** [comment]
Sorry for my mistake. I picked wrong repository to report that.
