### ISSUE TITLE
Steam Deck/Linux [Bottles] guide trobleshooting clarification

### ISSUE THREAD

**Issue by Enrik987** [thesupersonic16/HedgeModManager#955]
This question may have been answered before, but im not sure what specifically to do when to install .NET on bottles? HedgModManager? For use to mod games like Sonic Colors Ultimate and Frontiers and Origins, if there is a detailed guide on this topic, I would like it to be directed for me.

**Comment by thesupersonic16** [comment]
Discussions related to HMM on Linux should go to #219. To quickly answer your question, the simplest method is to follow the `Manually installing libraries from another system.` method. If any of the steps within the method is unclear to you, please post a comment in the issue mentioned above.

EDIT: If you are asking for installing the framework for Bottles, you will need to create the bottle using the config yml file which is linked in the guide.
