### ISSUE TITLE
[Bug] Failed to Download Mod: Illegal characters in path.

### ISSUE THREAD

**Issue by TheRealRebeg2** [thesupersonic16/HedgeModManager#961]
## Describe the issue/bug
this happens every time i try to download a mod, i have to manually download all mods

## Expected Behaviour
it should download and unpack the mod automatically

![image_2024-11-04_193202977](https://github.com/user-attachments/assets/cbca0e04-e1bc-4533-b49d-5e7d0189da29)

**Comment by thesupersonic16** [comment]
Are you able to run Hedge Mod Manager normally and select the game?

**Comment by TheRealRebeg2** [comment]
yeah, it's just the 1-click install that's screwing up.

**Comment by thesupersonic16** [comment]
What mod are you installing?
