### ISSUE TITLE
[Bug] Save Redirect is not working in Sonic X Shadow Generation

### ISSUE THREAD

**Issue by JohnSmith774** [thesupersonic16/HedgeModManager#963]
## Describe the issue/bug

I have save redirect enabled, but it updates the savedata in the following directory.
C:\Users\(UserName)\AppData\Roaming\Sega\SONIC_X_SHADOW_GENERATIONS\steam\(ID)

## Expected Behaviour

I want you to create another savedata in the following directory.
~\steamapps\common\SONIC_X_SHADOW_GENERATIONS

**Comment by thesupersonic16** [comment]
Since you are reporting an issue with the mod loader and not the manager software itself, you will need to recreate the issue on [this repo](https://github.com/hedge-dev/HE2ModLoader/issues) instead.
