### ISSUE TITLE
[Bug] sound after rolling from slide doesn't ever stop

### ISSUE THREAD

**Issue by JavierASecas** [thesupersonic16/HedgeModManager#965]
## Describe the issue/bug

Since the codes were updated, some issues arose. Sound from spin state into anything doesn't stop, mainly from slide into dropdash INTO boost
## Expected Behaviour

It would be for the sound to stop after the spin state is over (maybe it doesn't check if it's over or not)
## Additional Context

Last update fixed a lot of gameplay issues with rolling but added this and makes the codes unusable for me, I suggest reverting to a previous iteration of the codes if this isn't solved.

**Comment by thesupersonic16** [comment]
Issues relating to the codes do not belong on this repo, please post your issue at [hedge-dev/HMMCodes](https://github.com/hedge-dev/HMMCodes).

**Comment by JavierASecas** [comment]
sorry i saw it later, didn't know
