### ISSUE TITLE
[Bug] Shadow Generations - Disable HUD Code Not Working Properly on 4k monitors

### ISSUE THREAD

**Issue by throwaway1908** [thesupersonic16/HedgeModManager#970]
## Describe the issue/bug
As the title states, the disable HUD code for Shadow Generations does not completely disappear on 4k monitors. Some boost textures remain in the top left corner, along with boss health bars etc. 

## Expected Behaviour
Enable the disable HUD code on a 4k monitor. 

## Additional Context
-

**Comment by thesupersonic16** [comment]
All code issues need to be posted in https://github.com/hedge-dev/HMMCodes
