### ISSUE TITLE
[Bug] Illegal Characters In Path

### ISSUE THREAD

**Issue by CalmEnergy2125** [thesupersonic16/HedgeModManager#975]
## Describe the issue/bug
Every time I hit one click install from gamebanana, it downloads then stops, saying "Illegal Characters In Path. I don't know what could be causing it, as it was doing this since first downloading it. This is happening with both shadow generations and sonic forces, and happens with every mod I try to download. It works fine with manual installs, however.

## Additional Context
An image of the error. I don't know if there's a way to get a log for this, but if there is a way then tell me and I'll upload it.
![image](https://github.com/user-attachments/assets/16692c35-57f3-4290-b311-5c5bdf9bd1c6)

**Comment by thesupersonic16** [comment]
Can you paste the link address of the 1-click button surrounded with \`. Like \`LINK\`
Link should start with `hedgemm`.

**Comment by CalmEnergy2125** [comment]
FIgured out the issue, seems like something was up with winrar not correctly unzipping the files, I installed 7zip for something unrelated but it opened when using one click install and now it works fine.
