### ISSUE TITLE
[GEN] Help my soul

### ISSUE THREAD

**Issue by VegQuick1** [thesupersonic16/HedgeModManager#98]
Hello, sorry, but I don't really know what to do anymore, I installed the zip files, extracted them into the Generations folder, also did this with HedgeModManager.exe, but apparently it just crashes? I am not sure but I made sure to delete the cpkredir files and the Mod folder itself, thats the only way the .exe opens without crashing, and so this happends: 
![Hmm](https://user-images.githubusercontent.com/64242436/81919751-db4ecc80-959d-11ea-8a96-69d6c2ff9de0.png)

Then, when I try to open the .exe (Always as an admin), it crashes and doesn't do anything.
I also have the Gens in a folder that isn't C, in a flash memory.
I don't know what to do.
sorry for inconveniences

**Comment by thesupersonic16** [comment]
Can you try make sure .Net Framework is installed properly by [downloading and installing this](https://go.microsoft.com/fwlink/?linkid=2088631).

If that does not help, can you send your crash dump so I can take a look at it. Here is how you can do that:
1. Navigate to `%localappdata%\CrashDumps\` using File Explorer
2. Delete all the files in the folder
3. Run HMM again
4. Zip the file that should appear right after HMM crashes
5. Send the zip as an attachment.

**Comment by VegQuick1** [comment]
I found this file: "WERCE01.tmp.WERInternalMetadata" is a .xml file and it appears when I execute the program, but dissappears.
Although it does that for some reason (And I found it quite strange), I could get to open it, I will try to leave it here:
[WERCE01.tmp.WERInternalMetadata.zip](https://github.com/thesupersonic16/HedgeModManager/files/4631676/WERCE01.tmp.WERInternalMetadata.zip)

Or here is a link: https://www.mediafire.com/file/omg4wk8qmbtfg1o/WERCE01.tmp.WERInternalMetadata.7z/file

 And it shows this:
<?xml version="1.0" encoding="UTF-16"?>
<WERReportMetadata>
	<OSVersionInformation>
		<WindowsNTVersion>6.2</WindowsNTVersion>
		<Build>9200 </Build>
		<Product>(0x30): Windows 8 Pro</Product>
		<Edition>Professional</Edition>
		<BuildString>9200.17581.amd64fre.win8_gdr.151112-0600</BuildString>
		<Revision>Unknown</Revision>
		<Flavor>Multiprocessor Free</Flavor>
		<Architecture>X64</Architecture>
		<LCID>3082</LCID>
	</OSVersionInformation>
	<ProcessInformation>
		<Pid>1268</Pid>
		<ImageName>HedgeModManager.exe</ImageName>
		<CmdLineSignature>00000000</CmdLineSignature>
		<Uptime>2964</Uptime>
		<ProcessVmInformation>
			<PeakVirtualSize>716574720</PeakVirtualSize>
			<VirtualSize>716447744</VirtualSize>
			<PageFaultCount>47272</PageFaultCount>
			<PeakWorkingSetSize>134115328</PeakWorkingSetSize>
			<WorkingSetSize>134115328</WorkingSetSize>
			<QuotaPeakPagedPoolUsage>536808</QuotaPeakPagedPoolUsage>
			<QuotaPagedPoolUsage>536808</QuotaPagedPoolUsage>
			<QuotaPeakNonPagedPoolUsage>38832</QuotaPeakNonPagedPoolUsage>
			<QuotaNonPagedPoolUsage>38320</QuotaNonPagedPoolUsage>
			<PagefileUsage>124891136</PagefileUsage>
			<PeakPagefileUsage>124895232</PeakPagefileUsage>
			<PrivateUsage>124891136</PrivateUsage>
		</ProcessVmInformation>
		<ParentProcess>
			<ProcessInformation>
				<Pid>1756</Pid>
				<ImageName>explorer.exe</ImageName>
				<CmdLineSignature>00000000</CmdLineSignature>
				<Uptime>30558127</Uptime>
				<ProcessVmInformation>
					<PeakVirtualSize>1312100352</PeakVirtualSize>
					<VirtualSize>1073016832</VirtualSize>
					<PageFaultCount>1541417</PageFaultCount>
					<PeakWorkingSetSize>337997824</PeakWorkingSetSize>
					<WorkingSetSize>234913792</WorkingSetSize>
					<QuotaPeakPagedPoolUsage>2430168</QuotaPeakPagedPoolUsage>
					<QuotaPagedPoolUsage>1854464</QuotaPagedPoolUsage>
					<QuotaPeakNonPagedPoolUsage>316336</QuotaPeakNonPagedPoolUsage>
					<QuotaNonPagedPoolUsage>282096</QuotaNonPagedPoolUsage>
					<PagefileUsage>164651008</PagefileUsage>
					<PeakPagefileUsage>403181568</PeakPagefileUsage>
					<PrivateUsage>164651008</PrivateUsage>
				</ProcessVmInformation>
			</ProcessInformation>
		</ParentProcess>
	</ProcessInformation>
	<ProblemSignatures>
		<EventType>CLR20r3</EventType>
		<Parameter0>HedgeModManager.exe</Parameter0>
		<Parameter1>1.0.0.0</Parameter1>
		<Parameter2>db4d48a0</Parameter2>
		<Parameter3>HedgeModManager</Parameter3>
		<Parameter4>1.0.0.0</Parameter4>
		<Parameter5>db4d48a0</Parameter5>
		<Parameter6>1cc</Parameter6>
		<Parameter7>6</Parameter7>
		<Parameter8>System.TypeLoadException</Parameter8>
	</ProblemSignatures>
	<DynamicSignatures>
		<Parameter1>6.2.9200.2.0.0.256.48</Parameter1>
		<Parameter2>3082</Parameter2>
		<Parameter22>3abf</Parameter22>
		<Parameter23>3abfa17ab7f2a7b48d436c7bd23932c2</Parameter23>
		<Parameter24>1fd4</Parameter24>
		<Parameter25>1fd4540327b64d819bd596f46c9a2382</Parameter25>
	</DynamicSignatures>
	<SystemInformation>
		<MID>73DA1FC1-CDF6-4CFD-9585-DB8492623D26</MID>
		<SystemManufacturer>ECS</SystemManufacturer>
		<SystemProductName>NM70-I2</SystemProductName>
		<BIOSVersion>4.6.5</BIOSVersion>
		<OSInstallDate>1587659350</OSInstallDate>
	</SystemInformation>
	<DAMInformation>
	</DAMInformation>
	<Integrator>
		<Flags>00000000</Flags>
		<SuspensionTimeDelta>31</SuspensionTimeDelta>
		<ExemptionTimeDelta>NULL</ExemptionTimeDelta>
	</Integrator>
</WERReportMetadata>

Does it say something?

**Comment by thesupersonic16** [comment]
Its not the file I need. Should have HedgeModManager in it's name.

**Comment by VegQuick1** [comment]
there: https://www.mediafire.com/file/tblet436br0zy11/HedgeModManager.zip/file

**Comment by thesupersonic16** [comment]
Thanks for sending the crash dump. It shows you are running .NET Framework version 4.6 which is not supported and pretty sure will not work. Did you make sure you installed .NET Framework 4.8 using the link I sent you?

**Comment by thesupersonic16** [comment]
Just an update to your issue, I have notice that you are running Windows 6.2(Windows 8) which is discontinued at .NET Framework 4.6, because of this HMM will not work on your OS unless you update to Windows 8.1 or newer.

Since this is an OS issue which is unrelated to HMM I will be closing this issue. Thanks for letting us know.

**Comment by VegQuick1** [comment]
I've had some troubles, I couldn't install the .NET Framework 4.8, it said It was not compatible with my operating system, so I installed a Service Pack, and changed .Net Framework to 4.8 and I think I got everything correct, but the error keeps happening, so maybe it didn't work or something else is happening, here is the new crash dump file anyways: https://www.mediafire.com/file/14txanzm70n63y0/HedgeModManager.zip/file

**Comment by Sajidur78** [comment]
.Net Framework 4.8 is not supported on Windows 8. Support for it has ended a long time ago, you have to update to Windows 8.1.

**Comment by thesupersonic16** [comment]
Again, You need to update your OS to Windows 8.1 or higher (Windows 10 is recommended).

Also the crash dump you sent still shows you are running Windows 8 with .NET Framework 4.6.

**Comment by VegQuick1** [comment]
It completely works now, thank you so much!
