### ISSUE TITLE
Stomp Keeps Horizontal Velocity code, crashes game

### ISSUE THREAD

**Issue by epic-bruh-moment** [thesupersonic16/HedgeModManager#99]
I expected the manager, to load the code up properly, the game boots up just fine, but whenever I stomp, the game just crashes, no error messages, it just shuts down

**Comment by Sajidur78** [comment]
Have you tried disabling all codes and just keeping the stomp code?

**Comment by epic-bruh-moment** [comment]
yes

**Comment by epic-bruh-moment** [comment]
Issue fixed, new update made it work
